import { mountShell } from "../src/ui/shell.js";
import { invokeFunction } from "../src/backend/invoke.js";
import { notify } from "../src/ui/toast.js";
import { escapeHtml, formatCount } from "../src/ui/format.js";
import { confirmDialog } from "../src/ui/dialog.js";
mountShell({page:"seasons",base:"../"});
const $=id=>document.getElementById(id);let state=null,busy=false;
const potionNames={"lucky-potion-1":"Lucky Potion I","lucky-potion-2":"Lucky Potion II","lucky-potion-3":"Lucky Potion III","speed-potion-1":"Speed Potion I","speed-potion-2":"Speed Potion II","speed-potion-3":"Speed Potion III","fortune-potion-1":"Fortune Potion I","fortune-potion-2":"Fortune Potion II","fortune-potion-3":"Fortune Potion III","mass-potion-1":"Mass Potion I","mass-potion-2":"Mass Potion II","mass-potion-3":"Mass Potion III","legendary-potion":"Legendary Potion","mythic-potion":"Mythic Potion"};
function rewardText(items=[]){return items.map(r=>r.type==="money"?`$${formatCount(r.amount)}`:r.type==="relic"?`${r.quantity>1?`${r.quantity}× `:""}${r.id}`:r.type==="cosmetic"?`${r.id==="first-light"?"First Light":"Season Zero"} ${r.cosmeticType}`:`${r.quantity>1?`${r.quantity}× `:""}${potionNames[r.id]??r.id}`).join(" + ");}
function claimed(lane,tier){return (state.progress.claimed_tiers??[]).includes(`${lane}:${tier}`);}
function currentTier(){const tiers=state.season.tiers;let level=1;for(const t of tiers)if(Number(state.progress.xp)>=Number(t.xp))level=t.tier;return level;}
function renderTrack(){const xp=Number(state.progress.xp);$("track").innerHTML=state.season.tiers.map(t=>{const unlocked=xp>=Number(t.xp);const freeClaimed=claimed("free",t.tier),premiumClaimed=claimed("premium",t.tier);return `<article class="tier-card ${unlocked?"is-unlocked":""} ${t.tier%5===0?"is-milestone":""}"><header><span>Tier ${t.tier}</span><strong>${formatCount(t.xp)} XP</strong></header><div class="reward reward--free"><small>FREE</small><b>${escapeHtml(rewardText(t.free))}</b><button data-claim="free" data-tier="${t.tier}" ${!unlocked||freeClaimed?"disabled":""}>${freeClaimed?"Claimed":unlocked?"Claim":"Locked"}</button></div><div class="reward reward--premium"><small>PREMIUM</small><b>${escapeHtml(rewardText(t.premium))}</b><button data-claim="premium" data-tier="${t.tier}" ${!unlocked||!state.progress.premium||premiumClaimed?"disabled":""}>${premiumClaimed?"Claimed":!state.progress.premium?"Premium":unlocked?"Claim":"Locked"}</button></div></article>`;}).join("");}
function missionHtml(m){const final=m.thresholds.length,reroll=m.cadence==="daily"&&m.progress===0&&m.awarded_tiers===0&&!state.dailyRerollUsed;return `<article class="mission"><header><div><small>${m.cadence.toUpperCase()}</small><h4>${escapeHtml(m.title)}</h4></div>${reroll?`<button data-reroll="${m.slot}">Reroll</button>`:""}</header><div class="mission-tiers">${m.thresholds.map((target,i)=>{const done=m.awarded_tiers>i;return `<div class="mission-tier ${done?"done":""}"><span>Tier ${i+1}</span><b>${formatCount(Math.min(Number(m.progress),Number(target)))} / ${formatCount(target)}</b><small>+${formatCount(m.xp_rewards[i])} XP${i+1===final?` · ${escapeHtml(rewardText([m.item_reward]))}`:""}</small></div>`;}).join("")}</div></article>`;}
function render(){const xp=Number(state.progress.xp),level=currentTier(),tiers=state.season.tiers,next=tiers.find(t=>Number(t.xp)>xp),previous=[...tiers].reverse().find(t=>Number(t.xp)<=xp);$("status").textContent="LIVE";$("level").textContent=`${level} / ${tiers.length}`;$("xpLabel").textContent=`${formatCount(xp)} XP`;$("nextLabel").textContent=next?`${formatCount(Number(next.xp)-xp)} to Tier ${next.tier}`:"Track complete";const start=Number(previous?.xp??0),end=Number(next?.xp??start);$("xpBar").style.width=`${next?Math.max(0,Math.min(100,(xp-start)/(end-start)*100)):100}%`;$("rollCap").textContent=`Daily roll XP: ${formatCount(state.progress.roll_xp_today)} / 1,500`;$("premium").textContent=state.progress.premium?"Premium owned":"Unlock Premium";$("premium").disabled=state.progress.premium;renderTrack();const daily=state.missions.filter(m=>m.cadence==="daily"),weekly=state.missions.filter(m=>m.cadence==="weekly");$("dailyMissions").innerHTML=daily.map(missionHtml).join("");$("weeklyMissions").innerHTML=weekly.map(missionHtml).join("");updateClock();}
function updateClock(){if(!state)return;const ms=new Date(state.season.ends_at)-Date.now();if(ms<=0){$("countdown").textContent="Claim period";return;}const days=Math.floor(ms/86400000),hours=Math.floor(ms%86400000/3600000);$("countdown").textContent=`${days}d ${hours}h remaining`;}
async function call(action,body={}){if(busy)return null;busy=true;const result=await invokeFunction("seasons",{action,...body});busy=false;if(result.error){notify.error("Season action failed",result.error.message);return null;}return result.data;}
async function load(){const data=await call("list");if(!data){$("status").textContent="OFF";return;}state=data;const daily=state.missions.find(m=>m.cadence==="daily");state.dailyRerollUsed=(state.rerolls??[]).some(r=>daily&&new Date(r.period_start).getTime()===new Date(daily.period_start).getTime());render();}
$("refresh").onclick=load;$("premium").onclick=async()=>{const choice=await confirmDialog({title:"Unlock Season Zero Premium?",body:"<p>This permanently unlocks the Premium track for Season Zero and immediately deducts $5,000,000.</p><p>Previously reached Premium tiers become claimable.</p>",confirmLabel:"Unlock for $5,000,000"});if(choice!=="confirm")return;if(await call("purchase-premium",{seasonId:state.season.id})){notify.success("Premium unlocked");await load();}};document.addEventListener("click",async e=>{const claim=e.target.closest("[data-claim]");if(claim&&await call("claim-tier",{seasonId:state.season.id,tier:Number(claim.dataset.tier),lane:claim.dataset.claim})){notify.success("Reward claimed");await load();}const reroll=e.target.closest("[data-reroll]");if(reroll&&await call("reroll-daily",{seasonId:state.season.id,slot:Number(reroll.dataset.reroll)})){notify.success("Mission rerolled");await load();}});setInterval(updateClock,60000);load();
