import { mountShell } from "../../src/ui/shell.js";
import { deepcoreRequest, loadDeepcoreSpecimens, requestId } from "../../src/backend/cloudDeepcore.js";
mountShell({ page: "limited-events", base: "../../" });

const $ = (id) => document.getElementById(id);
const fmt = (n) => Number(n || 0).toLocaleString("en-US", { maximumFractionDigits: 2 });
const money = (n) => `$${fmt(n)}`;
const esc = (s) => String(s ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const PHASES = {
  1:["Phase 1 · Survey",500e6,"Raise $500M effective funding."],
  2:["Phase 2 · Construction",1.5e9,"Reach $1.5B and sacrifice 50,000 Legendary specimens."],
  3:["Phase 3 · Descent",3e9,"Reach $3B, 250,000 event rolls, and $1B sacrificed specimen value."],
  4:["Phase 4 · Pressure",5e9,"Reach $5B, sacrifice 5,000 Mythic specimens, including one ≥10× weight."],
  51:["Phase 5.1 · Fracture",6e9,"Raise $6B effective funding to expose the split passage."],
  52:["Phase 5.2 · Route Race",7.5e9,"Complete either passage first. The losing route remains part of total funding."],
  6:["Phase 6 · The Breach",10e9,"Reach $10B and deliberately sacrifice one Transcendent specimen."],
  7:["Stretch · The Heart",25e9,"Every full $1B improves Heart odds by 5%, capped at ×1.75 at $25B."]
};
const RESEARCH = [[5,"2 Deepcore Catalysts"],[10,"1 Pressurized Catalyst"],[20,"2 Deepcore Catalysts + 1 Pressurized"],[30,"Deepcore Researcher title"],[40,"1 Deepcore Crate"],[50,"1 Seismic Potion"],[60,"1 Deepcore Crate"],[70,"1 Mythic Potion"],[75,"Deepcore Field Research background + achievement"]];
const SUPPLY = [["Reinforced Drill Bits",5e6,"×1.05"],["Heavy Transport Fleet",10e6,"×1.10"],["Industrial Excavation Gear",20e6,"×1.15"],["Deep-Bore Machinery",30e6,"×1.20"],["Geological Systems",50e6,"×1.25"],["Deepcore Industrial Complex",75e6,"×1.30"]];
const SHOP = [
  ["deepcore-catalyst","Deepcore Catalyst",5e6,"Next 25 rolls: ×1.5 Weight Luck",5,1],
  ["pressurized-catalyst","Pressurized Catalyst",15e6,"60s: ×2 Weight Luck and ×1.15 Weight Multiplier",3,2],
  ["seismic-potion","Seismic Potion",40e6,"60s: ×5 Luck, ×2 mutation chance, ×1.25 Deepcore chance",2,6],
  ["unstable-core","Unstable Core",100e6,"Next 10 rolls: ×25 Deepcore chance and ×5 Special chance",1,7]
];
const LEADERBOARD_REWARDS = [
  ["🥇 #1",10,6,3,1],
  ["🥈 #2",8,5,2,1],
  ["🥉 #3",6,4,2,0],
  ["#4",5,3,1,0],
  ["#5",4,2,1,0]
];
let snapshot, specimens = [], timer;

function notice(message, error=false){const node=$("notice");node.textContent=message;node.className=`dc-notice show${error?" error":""}`;clearTimeout(notice.t);notice.t=setTimeout(()=>node.className="dc-notice",3500);}
function duration(ms){if(ms<=0)return "00d 00h 00m 00s";const s=Math.floor(ms/1000),d=Math.floor(s/86400),h=Math.floor(s/3600)%24,m=Math.floor(s/60)%60;return `${String(d).padStart(2,"0")}d ${String(h).padStart(2,"0")}h ${String(m).padStart(2,"0")}m ${String(s%60).padStart(2,"0")}s`;}
function startClock(){clearInterval(timer);const tick=()=>{const server=Date.parse(snapshot?.serverNow||new Date())+(Date.now()-(snapshot?._loadedAt||Date.now()));const status=snapshot?.status;const target=status==="preview"?Date.parse("2026-09-20T00:00:00Z"):Date.parse("2026-10-04T00:00:00Z");if((status==="preview"||status==="active")&&server>=target){clearInterval(timer);load();return;}$("countdown").textContent=status==="archived"?"OPERATION COMPLETE":duration(target-server);$("clockLabel").textContent=status==="preview"?"OPERATIONS BEGIN IN":status==="active"?"OPERATION ENDS IN":"FINAL ARCHIVE";};tick();timer=setInterval(tick,1000);}
function phaseInfo(){return PHASES[Number(snapshot.event.phase)]||PHASES[1];}
function phaseProgress(){const [,,]=phaseInfo(), e=snapshot.event, phase=Number(e.phase), goal=PHASES[phase][1], prior=({1:0,2:500e6,3:1.5e9,4:3e9,51:5e9,52:6e9,6:7.5e9,7:10e9})[phase]||0;return Math.max(0,Math.min(100,(Number(e.effective_funding)-prior)/(goal-prior)*100));}
function phaseRequirementCopy(){const e=snapshot.event,phase=Number(e.phase);if(phase===2)return `Reach $1.5B and sacrifice ${fmt(e.legendary_sacrificed)} / 50,000 Legendary specimens.`;if(phase===4)return `Reach $5B and sacrifice ${fmt(e.mythic_sacrificed)} / 5,000 Mythic specimens, including one ≥10× weight.`;return phaseInfo()[2];}
function renderPhaseObjectives(){const e=snapshot.event,phase=Number(e.phase),rows=phase===2?[["Effective funding",Number(e.effective_funding),1.5e9,money],["Legendary specimens sacrificed",Number(e.legendary_sacrificed),50000,fmt]]:phase===4?[["Effective funding",Number(e.effective_funding),5e9,money],["Mythic specimens sacrificed",Number(e.mythic_sacrificed),5000,fmt]]:[];const node=$("phaseObjectives");node.classList.toggle("hidden",!rows.length);node.innerHTML=rows.map(([label,current,target,format])=>{const pct=Math.max(0,Math.min(100,current/target*100));return `<div class="phase-objective"><div><strong>${label}</strong><span>${format(current)} / ${format(target)}</span></div><div class="progress" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="${target}" aria-valuenow="${Math.min(current,target)}"><i style="width:${pct}%"></i></div></div>`;}).join("")+(phase===4?`<div class="phase-objective phase-objective--status"><strong>≥10× weight Mythic specimen</strong><span>${e.heavy_specimen_met?"COMPLETE":"PENDING"}</span></div>`:"");}
function button(label,action,key,disabled=false){return `<button class="btn" data-action="${action}" data-key="${esc(key)}" ${disabled?"disabled":""}>${esc(label)}</button>`;}
function renderRoute(){const e=snapshot.event, show=Number(e.phase)>=52||e.route_winner;if(!show){$("routeRace").classList.add("hidden");return;}$("routeRace").classList.remove("hidden");$("routeRace").innerHTML=`<div class="route ${e.route_winner==="crystalline"?"winner":""}"><strong>Crystalline Passage</strong><p>${money(e.crystalline_funding)} / $1.5B · ${fmt(e.crystalline_specimens)} / 4,000 Exotic+</p></div><div class="route ${e.route_winner==="anomalous"?"winner":""}"><strong>Anomalous Passage</strong><p>${money(e.anomalous_funding)} / $1.5B · ${fmt(e.anomalous_specimens)} / 10 ≥1M-rarity specimens</p></div>`;}
function renderRewards(){const eligible=Boolean(snapshot.player?.eligible_at);$("rewards").innerHTML=(snapshot.rewards||[]).map(r=>`<div class="reward-row"><div><strong>${esc(r.label||r.reward_key)}</strong><p>${r.claimed?"Claimed":eligible?"Ready to claim":"Requires $1M actual funding and 1,000 event rolls before event end"}</p></div>${button(r.claimed?"Claimed":"Claim","claimReward",r.reward_key,r.claimed||!eligible)}</div>`).join("")||'<p class="muted">Rewards appear as community phases are completed.</p>';}
function renderQuests(){const all=[...(snapshot.quests?.daily||[]),...(snapshot.quests?.project||[])];$("quests").innerHTML=all.map(q=>`<div class="reward-row"><div><strong>${esc(q.label)}</strong><p>${fmt(q.progress)} / ${fmt(q.target)} · ${q.data} Research Data</p></div>${button(q.claimed?"Claimed":"Claim","claimQuest",q.key,q.claimed||Number(q.progress)<Number(q.target)||snapshot.status!=="active")}</div>`).join("")||'<p class="muted">Quest progress is available during active operations.</p>';const claimed=new Set(snapshot.researchClaims||[]),data=Number(snapshot.player?.research_data||0);$("researchData").textContent=fmt(data);$("researchTrack").innerHTML=RESEARCH.map(([n,label])=>`<div class="reward-row"><div><strong>${n} Data</strong><p>${label}</p></div>${button(claimed.has(n)?"Claimed":"Claim","claimResearch",n,claimed.has(n)||data<n)}</div>`).join("");const found=snapshot.discoveries||{};$("rareFindings").innerHTML=[["pathfinder","Pathfinder","Recover the winning passage specimen"],["blacksite","Blacksite Clearance","Recover Blacksite Crystal"],["heart","From the Deep","Recover Heart of the Deep"]].map(([key,name,copy])=>`<div class="reward-row"><div><strong>${found[key]?"✓ ":"◇ "}${name}</strong><p>${copy}</p></div><span>${found[key]?"RECOVERED":"UNDISCOVERED"}</span></div>`).join("");}
function renderSupply(){const level=Number(snapshot.player?.supply_level||0);$("supplyShop").innerHTML=SUPPLY.map(([name,cost,multi],i)=>`<div class="supply-item"><p class="eyebrow">LEVEL ${i+1}</p><h3>${name}</h3><strong>${multi} efficiency</strong><p>${money(cost)} actual cash</p>${button(i<level?"Installed":i===level?"Purchase":"Sequentially locked","buySupply",i+1,i!==level||snapshot.status!=="active")}</div>`).join("");}
function renderShop(){const inventory=snapshot.player?.inventory||{},e=snapshot.event,unlocked=id=>id==="deepcore-catalyst"?[51,52,6,7].includes(Number(e.phase)):id==="pressurized-catalyst"?[6,7].includes(Number(e.phase)):id==="seismic-potion"?Number(e.phase)===7&&Number(e.effective_funding)>=15e9:Number(e.phase)===7&&Number(e.effective_funding)>=25e9;$("consumableStatus").textContent=snapshot.status==="archived"?"Operations are archived and purchases are closed. Your remaining consumables and Deepcore Crates are still usable.":"Purchases reset daily at 00:00 SGT. Owned items remain usable after the event ends.";$("consumables").innerHTML=SHOP.map(([id,name,cost,desc,limit])=>`<div class="supply-item"><p class="eyebrow">OWNED · ${fmt(inventory[id])}</p><h3>${name}</h3><p>${desc}</p><p>${money(cost)} · ${limit}/day</p>${button("Buy","buyConsumable",id,snapshot.status!=="active"||!unlocked(id))} ${button("Use","useConsumable",id,!Number(inventory[id]))}</div>`).join("")+`<div class="supply-item"><p class="eyebrow">OWNED · ${fmt(inventory["deepcore-crate"])}</p><h3>Deepcore Crate</h3><p>Weighted primary reward plus an independent 1/250 Deepcore Roll Card chance.</p>${button("Open crate","openCrate","deepcore-crate",!Number(inventory["deepcore-crate"]))}</div>`;}
function renderLeaderboardRewards(){$("leaderboardRewards").innerHTML=`<table><thead><tr><th>Placement</th><th>Deepcore Catalyst</th><th>Pressurized Catalyst</th><th>Seismic Potion</th><th>Unstable Core</th></tr></thead><tbody>${LEADERBOARD_REWARDS.map(([rank,catalyst,pressurized,seismic,unstable])=>`<tr><th>${rank}</th><td>${catalyst}×</td><td>${pressurized}×</td><td>${seismic}×</td><td>${unstable?`${unstable}×`:"—"}</td></tr>`).join("")}</tbody></table>`;}
function renderBoard(id,rows){const a=new Set((snapshot.leaderboards?.actual||[]).filter(r=>Number(r.rank)<=5).map(r=>r.player_id)),dual=new Set((snapshot.leaderboards?.effective||[]).filter(r=>Number(r.rank)<=5&&a.has(r.player_id)).map(r=>r.player_id));$(id).innerHTML=(rows||[]).map(r=>`<div class="board-row ${Number(r.rank)<=5?"top-five":""}"><strong>#${r.rank}</strong><span>${dual.has(r.player_id)?"♛ ":""}${esc(r.username||"Unknown")}</span><strong>${money(r.amount)}</strong></div>${Number(r.rank)===5?'<p class="cutoff">TOP 5 REWARD CUTOFF</p>':""}`).join("")||'<p class="muted">No contributions recorded.</p>';}
function renderLog(){const final=snapshot.event.final_report,details=l=>{const b=l.body||{};if(l.entry_key==="route-winner")return `${b.winner} passage breached. Losing-route progress was permanently frozen.`;if(l.entry_key==="phase-6")return `${b.username||"A project contributor"} sacrificed ${b.gemName||"a Transcendent specimen"} · 1 in ${fmt(b.rarity)} · ${fmt(b.finalWeight)}g (${fmt(b.weightMultiplier)}×).`;if(l.entry_key==="first-heart")return `${b.username||"A player"} recovered the first Heart of the Deep.`;if(b.effectiveFunding)return `Effective funding: ${money(b.effectiveFunding)}.`;return "Recorded by the Deepcore operations server.";};$("projectLog").innerHTML=(snapshot.log||[]).map(l=>`<div class="log-entry"><small>${new Date(l.occurred_at).toLocaleString("en-SG",{timeZone:"Asia/Singapore"})} SGT</small><h3>${esc(l.title)}</h3><p>${esc(details(l))}</p></div>`).join("")+(final?`<div class="log-entry"><h3>FINAL REPORT</h3><p>${money(final.actualFunding)} actual · ${money(final.effectiveFunding)} effective · ${fmt(final.participants)} participants · ${fmt(final.communityRolls)} genuine rolls · winning passage: ${esc(final.routeWinner||"none")}</p></div>`:"");}
function objectiveOptions(){const p=Number(snapshot.event.phase),options=p===2?[["legendary","Legendary objective"]]:p===3?[["value","Sacrificed value"]]:p===4?[["mythic","Mythic / heavy objective"]]:p===52?[["crystalline","Crystalline passage"],["anomalous","Anomalous passage"]]:p===6?[["key","Phase 6 Transcendent breach"]]:[];$("objective").innerHTML=options.map(([v,l])=>`<option value="${v}">${l}</option>`).join("");$("sacrifice").disabled=!options.length||snapshot.status!=="active";}
function render(){const e=snapshot.event,p=snapshot.player,status=snapshot.status;document.body.classList.toggle("archived",status==="archived");$("statusLabel").textContent=status.toUpperCase();$("preview").classList.toggle("hidden",status!=="preview");$("dashboard").classList.toggle("hidden",status==="preview");$("heroCopy").textContent=status==="preview"?"A large-scale geological excavation has been approved. Community operations begin at the scheduled time.":status==="active"?"The community excavation is live. Every contribution pushes the project deeper.":"The excavation is archived. Final standings, the Project Log, and your remaining consumables stay accessible.";startClock();if(status==="preview")return;const info=phaseInfo();$("phaseName").textContent=info[0];$("phaseRequirements").textContent=phaseRequirementCopy();$("phaseBar").style.width=`${phaseProgress()}%`;renderPhaseObjectives();$("effectiveFunding").textContent=money(e.effective_funding);$("actualFunding").textContent=money(e.actual_funding);$("communityRolls").textContent=fmt(e.community_rolls);$("eligibility").textContent=p?.eligible_at?"ELIGIBLE":`${money(p?.actual_funding)} / $1M · ${fmt(p?.event_rolls)} / 1,000 rolls`;$("depthLabel").textContent=info[0].toUpperCase();$("layers").innerHTML=Array.from({length:Math.min(8,({1:0,2:1,3:2,4:3,51:4,52:5,6:6,7:7})[e.phase]||0)},(_,i)=>`<i style="--layer-height:${35+i*8}%"></i>`).join("");$("fundTargetWrap").classList.toggle("hidden",Number(e.phase)!==52||e.route_winner);$("fundForm").querySelector("button").disabled=status!=="active";renderRoute();renderRewards();renderQuests();renderSupply();renderShop();renderLeaderboardRewards();renderBoard("actualBoard",snapshot.leaderboards?.actual);renderBoard("effectiveBoard",snapshot.leaderboards?.effective);renderLog();objectiveOptions();$("specimen").innerHTML=specimens.map(g=>`<option value="${g.id}">${esc(g.gem_name)} · ${money(g.value)} · 1 in ${fmt(g.rarity)}</option>`).join("")||'<option>No eligible unlocked specimens</option>';$("autoEnabled").checked=Boolean(p?.auto_contribute);}
async function load(){try{[snapshot,specimens]=await Promise.all([deepcoreRequest(),loadDeepcoreSpecimens()]);snapshot._loadedAt=Date.now();render();}catch(e){if(Date.now()<Date.parse("2026-09-20T00:00:00Z")){snapshot={status:"preview",serverNow:new Date().toISOString(),event:{phase:1},_loadedAt:Date.now()};specimens=[];render();return;}notice(e.message,true);}}
async function act(action,payload={}){try{snapshot=await deepcoreRequest(action,payload);snapshot._loadedAt=Date.now();render();notice("Deepcore records updated.");}catch(e){notice(e.message,true);}}
document.addEventListener("click",e=>{const tab=e.target.closest("[data-tab]");if(tab){document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===tab));document.querySelectorAll("[data-panel]").forEach(x=>x.classList.toggle("hidden",x.dataset.panel!==tab.dataset.tab));return;}const b=e.target.closest("[data-action]");if(!b)return;const map={claimReward:{rewardKey:b.dataset.key},claimQuest:{questKey:b.dataset.key},claimResearch:{milestone:Number(b.dataset.key)},buySupply:{requestId:requestId()},buyConsumable:{itemId:b.dataset.key,requestId:requestId()},useConsumable:{itemId:b.dataset.key,requestId:requestId()},openCrate:{requestId:requestId()}};act(b.dataset.action,map[b.dataset.action]);});
$("fundForm").addEventListener("submit",e=>{e.preventDefault();act("contribute",{amount:Number($("fundAmount").value),target:$("fundTargetWrap").classList.contains("hidden")?"global":$("fundTarget").value,requestId:requestId()});});
$("sacrifice").addEventListener("click",()=>act("sacrifice",{specimenId:Number($("specimen").value),objective:$("objective").value,requestId:requestId()}).then(()=>load()));
$("saveAuto").addEventListener("click",()=>act("setAutoContribute",{enabled:$("autoEnabled").checked,minRarity:Number($("autoMin").value||1),maxValue:$("autoMaxValue").value?Number($("autoMaxValue").value):null}));
load();
