import assert from "node:assert/strict";import fs from "node:fs";
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
const legacy=read("supabase/migrations/20260819000003_expeditions_v090_beta.sql"),migration=read("supabase/migrations/20260827133021_abandoned_mine_expeditions.sql"),roll=read("supabase/functions/roll/index.ts"),client=read("src/backend/cloudExpeditions.js"),html=read("expeditions/index.html"),page=read("expeditions/expeditions.js");
assert.match(legacy,/create table if not exists public\.player_expeditions/);assert.doesNotMatch(migration,/drop table.*player_expeditions|truncate.*player_expeditions/is);assert.match(migration,/daily\/weekly tables and functions are intentionally retained/i);
for(const table of ["abandoned_mine_runs","abandoned_mine_funding","museum_artifact_registrations"])assert.match(migration,new RegExp(`create table public\\.${table}`));
assert.match(migration,/abandoned_mine_one_open_run[\s\S]*where status <> 'settled'/);assert.match(migration,/alter table public\.abandoned_mine_runs enable row level security/);assert.match(migration,/revoke all on public\.abandoned_mine_runs[\s\S]*authenticated/);
assert.match(migration,/array\[100000,175000,300000,500000,800000,1250000,2000000,3250000,5000000,7500000\]/);assert.match(migration,/p_depth<>v_run\.depth\+1/);assert.match(migration,/set money=money-v_cost where id=v_uid and money>=v_cost/);assert.match(migration,/insert into public\.abandoned_mine_funding/);
assert.match(roll,/"record_abandoned_mine_roll"/);assert.doesNotMatch(roll,/"record_expedition_roll"/);assert.equal((roll.match(/player_research_effects\(/g)||[]).length,1);assert.match(roll,/researchNumber\("luck_multiplier"\)/);assert.match(migration,/create or replace function public\.record_abandoned_mine_roll/);assert.match(migration,/progress=progress\+1/);
for(const severity of ["minor","major","critical"])assert.match(migration,new RegExp(`'${severity}'`));for(const field of ["danger","secured_cargo","unsecured_cargo","protected_discoveries","incident_log"])assert.match(migration,new RegExp(field));
assert.match(migration,/depth not in \(3,6,9\)/);assert.match(migration,/secured_cargo=secured_cargo\|\|unsecured_cargo,unsecured_cargo='\[\]'/);for(const route of ["reinforced_tunnel","rich_vein","supply_line","unstable_descent"])assert.match(migration,new RegExp(route));assert.match(migration,/depth in \(4,7\) then 'awaiting_route'/);
assert.match(migration,/create or replace function public\.extract_abandoned_mine/);assert.match(migration,/case when status='forced_extraction' then secured_cargo else secured_cargo\|\|unsecured_cargo end/);assert.match(migration,/status=case when status='forced_extraction' then 'forced_extraction' else 'extracted' end/);assert.match(migration,/create or replace function public\.settle_abandoned_mine/);assert.match(migration,/on conflict\(player_id,artifact_key\) do nothing/);assert.match(migration,/v_duplicate_value:=v_duplicate_value\+/);assert.match(migration,/lifetime_earnings=lifetime_earnings\+v_cargo_value\+v_duplicate_value/);assert.match(migration,/create or replace function public\.continue_mine_overdepth/);assert.match(migration,/overdepth=overdepth\+1/);
for(const name of ["Crystal Caverns","Volcanic Depths","Ancient Ruins","Lost Jungle"]){assert.match(html,new RegExp(name));const card=html.match(new RegExp(`<article class="card destination destination--wip"[^>]*>[\\s\\S]*?<h2>${name}<\\/h2>[\\s\\S]*?<\\/article>`))?.[0];assert.ok(card,`${name} WIP card missing`);assert.doesNotMatch(card,/<button|<a /,`${name} must be completely inaccessible`);}
assert.equal((html.match(/destination--active/g)||[]).length,1);for(const rpc of ["get_abandoned_mine_dashboard","fund_abandoned_mine","choose_abandoned_mine_route","build_abandoned_mine_camp","continue_mine_overdepth","extract_abandoned_mine","settle_abandoned_mine"])assert.match(client,new RegExp(rpc));assert.doesNotMatch(client,/daily|weekly|reroll|enter_expedition/i);assert.match(page,/Build Supply Camp/);assert.match(page,/Continue into Mine Overdepth/);assert.match(page,/Extract voluntarily/);
console.log("Abandoned Mine expedition redesign tests passed.");
