import assert from "node:assert/strict";
import fs from "node:fs";

const migration=fs.readFileSync(new URL("../supabase/migrations/20260819000003_expeditions_v090_beta.sql",import.meta.url),"utf8");
const roll=fs.readFileSync(new URL("../supabase/functions/roll/index.ts",import.meta.url),"utf8");
const updates=fs.readFileSync(new URL("../updates/index.html",import.meta.url),"utf8");
const rebalance=fs.readFileSync(new URL("../supabase/migrations/20260819000004_expedition_price_reward_rebalance.sql",import.meta.url),"utf8");
const client=fs.readFileSync(new URL("../src/backend/cloudExpeditions.js",import.meta.url),"utf8");
const page=fs.readFileSync(new URL("../expeditions/expeditions.js",import.meta.url),"utf8");

assert.match(migration,/daily'.*standard'.*200000/s);
assert.match(migration,/daily'.*deep'.*1000000/s);
assert.match(migration,/daily'.*3500000/s);
assert.match(migration,/weekly'.*standard'.*2000000/s);
assert.match(migration,/rerolls_max/);
assert.match(migration,/record_expedition_roll/);
assert.match(migration,/record_expedition_relic_spend/);
assert.match(migration,/status='completed'/);
assert.match(roll,/record_expedition_roll/);
assert.match(updates,/v0\.9\.0 Beta/);
assert.doesNotMatch(updates,/Daily Standard Expedition/);
assert.match(rebalance,/daily' and p_difficulty='standard' then 100000/);
assert.match(rebalance,/daily' and p_difficulty='deep' then 500000/);
assert.match(rebalance,/when p_cadence='daily' then 2000000/);
assert.match(rebalance,/when p_difficulty='standard' then 750000/);
assert.match(rebalance,/when p_difficulty='deep' then 3000000/);
assert.match(rebalance,/else 10000000 end/);
assert.match(rebalance,/reward_choice/);
assert.match(rebalance,/v_choice='default'/);
assert.match(client,/get_expedition_dashboard_v2/);
assert.match(client,/enter_expedition_v2/);
assert.match(page,/REWARD_CHOICES/);
assert.match(page,/rewardChoice/);
console.log("Expedition tests passed.");
