import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const migration = read("supabase/migrations/20260825131301_furnace_v1.sql");
const page = read("global-cash-graph/index.html");
const client = read("global-cash-graph/graph.js");
assert.match(migration, /lifetime_money_burned double precision not null default 0/);
assert.match(migration, /select money[\s\S]*for update/);
assert.match(migration, /money = greatest\(0, money - v_amount\)/);
assert.match(migration, /lifetime_money_burned = lifetime_money_burned \+ v_amount/);
assert.doesNotMatch(migration, /lifetime_earnings\s*=/);
assert.match(migration, /perform public\.snapshot_global_cash\(\)/);
assert.match(migration, /leaderboard_hidden = false/);
assert.match(page, /data-furnace-quick="1000000"/);
assert.match(page, /data-furnace-quick="10000000"/);
assert.match(page, /data-furnace-quick="100000000"/);
assert.match(page, /data-furnace-max/);
assert.match(client, /confirmDialog/);
assert.match(client, /tone: "danger"/);
console.log("Furnace V1 tests passed.");
