import{mountShell}from"../src/ui/shell.js";
import{loadCrystalDashboard,startCrystalCaverns,fundCrystalDepth,setCrystalIntensity,resolveCrystalDecision,continueCrystalOverdepth,extractCrystalCaverns,settleCrystalCaverns}from"../src/backend/cloudExpeditions.js";
import{formatMoney,escapeHtml}from"../src/ui/format.js";
import{confirmDialog}from"../src/ui/dialog.js";
import{CRYSTAL_INTENSITIES,crystalArtifactMultiplier,crystalSeverityProbabilities}from"../src/logic/crystalCaverns.js";
mountShell({page:"expeditions",base:"../"});
const $=id=>document.getElementById(id),money=n=>formatMoney(Number(n||0)),sum=a=>(a||[]).reduce((s,x)=>s+Number(x.value||0),0),pct=n=>`${(n*100).toFixed(1)}%`;let data,busy=false;
const btn=(label,action,plain=false)=>`<button type="button" class="btn ${plain?"":"btn--primary"}" data-action="${action}" ${busy?"disabled":""}>${label}</button>`;
const artifact=k=>(data.artifacts||[]).find(x=>x.key===k)||{};

function finds(items,secured){return(items||[]).map(x=>{const meta=artifact(x.key),fresh=!meta.registered;return`<li class="artifact-find ${fresh&&!secured?"artifact-find--risk":""}"><span><strong>${escapeHtml(x.name)}</strong> <em>${fresh?"NEW":"Duplicate"}</em>${fresh&&!secured?" <b>AT RISK</b>":""}<small>${fresh?"Museum discovery":`Extract for ${money(x.duplicateValue)}`}</small></span><strong>${secured?"Secured":"Unsecured"}</strong></li>`}).join("");}
function cargoGroup(label,cargo,artifacts,secured){const rows=(cargo||[]).map(x=>`<li><span>${escapeHtml(x.name||"Crystal treasure")}</span><strong>${money(x.value)}</strong></li>`).join("")+finds(artifacts,secured);return`<div class="cargo-group"><h4>${label}</h4>${rows?`<ul>${rows}</ul>`:"<p class=\"empty-note\">None</p>"}</div>`;}
function cargo(r){return`<section class="console-panel"><div class="panel-heading"><h3>Expedition Cargo</h3><span>${money(sum(r.secured_cargo)+sum(r.unsecured_cargo))} treasure</span></div><div class="cargo-columns">${cargoGroup("Secured",r.secured_cargo,r.secured_artifacts,true)}${cargoGroup("Unsecured",r.unsecured_cargo,r.unsecured_artifacts,false)}</div></section>`;}
function intensity(r){return`<section class="console-panel"><div class="panel-heading"><h3>Extraction Intensity</h3><span>Switch freely between rolls</span></div><div class="intensity-grid">${Object.entries(CRYSTAL_INTENSITIES).map(([key,m])=>`<button type="button" data-action="intensity:${key}" class="intensity-card ${r.intensity===key?"is-active":""}" ${r.status!=="active"||busy?"disabled":""}><strong>${m.label}</strong><span>×${m.progressMultiplier.toFixed(2)} progress</span><small>+${m.instabilityPer50} Instability / 50 base progress</small></button>`).join("")}</div></section>`;}
function cavernStatus(r){const s=crystalSeverityProbabilities(r.instability),a=crystalArtifactMultiplier(r.instability);return`<section class="console-panel"><div class="panel-heading"><h3>Cavern Status</h3><span>Instability is permanent and uncapped</span></div><div class="status-grid"><div><span>Danger</span><strong>${r.danger}%</strong><small>Incident chance</small></div><div><span>Instability</span><strong>${Math.floor(r.instability)}</strong><small>${Number(r.instability).toFixed(2)} internal</small></div><div><span>Artifact chance</span><strong>×${a.toFixed(2)}</strong><small>Final chance capped at 100%</small></div></div><div class="severity"><span>Severity if an incident occurs</span><div><b class="minor">Minor ${pct(s.minor)}</b><b class="major">Major ${pct(s.major)}</b><b class="critical">Critical ${pct(s.critical)}</b></div></div></section>`;}
function log(r){const entries=[...(r.event_log||[])].slice(-8).reverse();return`<section class="console-panel"><div class="panel-heading"><h3>Recent Expedition Log</h3><span>Meaningful events only</span></div>${entries.length?`<ol class="expedition-log">${entries.map(x=>`<li data-kind="${escapeHtml(x.kind||"event")}"><i></i><div><strong>${escapeHtml(x.message)}</strong><small>${x.at?new Date(x.at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"This run"}</small></div></li>`).join("")}</ol>`:"<p class=\"empty-note\">The expedition log is quiet.</p>"}</section>`;}

const formationCost=r=>r.pending.type==="od_formation"?Number(data.overdepthFormationCost||0):({4:750000,7:2000000,9:4500000}[r.depth]);
const outpostCosts=d=>({3:[250000,500000],6:[1000000,1750000],9:[3500000,5500000]}[d]);
function paid(label,choice,cost,effect){return`<span class="paid-option">${btn(`${label} · ${money(cost)}`,`paid:${choice}`)}<small>${effect}</small></span>`;}
function decision(r){const t=r.pending?.type;if(t==="minor_event")return`<div class="decision-card"><h3>Crystal event · ${escapeHtml(r.pending.event)}</h3><div class="decision-actions">${btn("Leave","choose:leave",true)}${r.pending.event==="pocket"?btn("Excavate · +5 Instability","choose:excavate"):r.pending.event==="resonance"?btn("Trigger Resonance · +8 Instability","choose:trigger"):btn("Break Open · +3 Instability","choose:break")}</div></div>`;if(t==="formation"||t==="od_formation")return`<div class="decision-card"><h3>Crystal formation</h3><p>Instability applies before artifact opportunities.</p><div class="decision-actions">${btn("Leave","choose:leave",true)}${paid("Careful extraction","careful",formationCost(r),"Higher-quality artifact search")}${btn("Shatter formation","choose:shatter")}</div></div>`;if(t==="outpost"){const c=outpostCosts(r.depth);return`<div class="decision-card"><h3>Stabilisation Outpost</h3><p>Both services secure all treasure and artifacts. <strong>Instability is unchanged.</strong></p><div class="decision-actions paid-grid">${paid("Secure","secure",c[0],"Secure all expedition cargo")}${paid("Reinforce","reinforce",c[1],"Secure all cargo and reduce Danger by 15")}</div></div>`;}if(t==="d10_choice")return`<div class="decision-card"><h3>The Crystal Heart is exposed</h3><p>Fracturing adds +30 Instability after the independent D10 checks.</p><div class="decision-actions">${btn("Extract","choose:extract",true)}${btn("FRACTURE THE HEART","choose:fracture")}</div></div>`;return"";}
function actions(r){if(r.status==="awaiting_funding"){const d=r.depth+1;return`<div class="next-action">${btn(`Fund D${d} · ${money(data.funding[d-1])}`,`fund:${d}`)}<small>Next Danger ${data.danger[d-1]}% · confirmation required</small></div>`;}if(r.status==="active")return`<p class="roll-prompt">Make genuine gem rolls to advance Extraction Progress.</p>`;if(r.status==="decision")return decision(r);if(r.status==="ready_to_extract")return`<div class="decision-actions">${btn("Extract safely","extract",true)}${r.pending?.fractured||r.overdepth?btn(`Fund OD${r.overdepth+1} · ${money(data.nextOverdepthCost)}`,"overdepth"):""}</div>`;if(r.status==="forced_extraction")return btn("Recover secured cargo","extract");if(r.status==="extracted")return btn("Settle expedition","settle");return"";}

function render(){const r=data.run;$("status").innerHTML=`<strong>Wallet ${money(data.money)}</strong><span>Danger controls incident occurrence; Instability controls artifact chance and conditional severity.</span>`;if(!r)$("console").innerHTML=btn("Begin Crystal Caverns","start");else{const p=Math.min(Number(r.progress),Number(r.target)),width=r.target?p/r.target*100:0;$("console").innerHTML=`<section class="run-overview"><div><span>Location</span><strong>D${r.depth}${r.overdepth?` · OD${r.overdepth}`:""}</strong></div><div class="progress-wrap"><div><span>Extraction Progress</span><strong>${Math.floor(p)} / ${r.target}</strong></div><div class="progress-track" role="progressbar" aria-label="Extraction Progress" aria-valuemax="${r.target}" aria-valuenow="${Math.floor(p)}"><i style="width:${Math.min(100,width)}%"></i></div></div></section>${actions(r)}<div class="dashboard-grid"><div>${intensity(r)}${cargo(r)}</div><div>${cavernStatus(r)}${log(r)}</div></div>`;}$("artifacts").innerHTML=(data.artifacts||[]).map(a=>`<div class="artifact-row ${a.registered?"is-owned":""}"><strong>${a.registered?"✓ ":""}${escapeHtml(a.name)}</strong><small>${escapeHtml(a.passive_name)}: ${escapeHtml(a.passive_description)}</small></div>`).join("");}

function risk(r,danger){return`<dl class="confirmation-summary"><div><dt>Next Danger</dt><dd>${danger}%</dd></div><div><dt>Current Instability</dt><dd>${Math.floor(r.instability)}</dd></div><div><dt>Unsecured cargo</dt><dd>${(r.unsecured_cargo||[]).length} treasure · ${(r.unsecured_artifacts||[]).length} artifacts</dd></div></dl>`;}
async function confirmSpend(title,effect,cost,danger=data.run.danger){return await confirmDialog({title,body:`<p>${effect}</p><dl class="confirmation-summary"><div><dt>Cost</dt><dd>${money(cost)}</dd></div><div><dt>Current balance</dt><dd>${money(data.money)}</dd></div><div><dt>Balance after</dt><dd>${money(Number(data.money)-cost)}</dd></div></dl>${risk(data.run,danger)}`,confirmLabel:`Spend ${money(cost)}`,cancelLabel:"Cancel",defaultAction:"cancel",preventEnter:true})==="confirm";}
async function act(a){const r=data.run;if(a==="start")return startCrystalCaverns();if(a.startsWith("intensity:"))return setCrystalIntensity(r.id,a.split(":")[1]);if(a.startsWith("fund:")){const d=Number(a.split(":")[1]),c=Number(data.funding[d-1]);if(await confirmSpend(`Fund D${d}?`,`Fund and enter Depth ${d}.`,c,data.danger[d-1]))return fundCrystalDepth(r.id,d);return null;}if(a.startsWith("paid:")){const choice=a.split(":")[1],outpost=r.pending.type==="outpost",c=outpost?outpostCosts(r.depth)[choice==="secure"?0:1]:formationCost(r),effect=outpost?(choice==="secure"?"Secure all cargo and artifacts.":"Secure all cargo and artifacts and reduce Danger by 15."):"Perform a higher-quality artifact extraction.";if(await confirmSpend("Confirm paid expedition action",effect,c))return resolveCrystalDecision(r.id,choice);return null;}if(a.startsWith("choose:"))return resolveCrystalDecision(r.id,a.split(":")[1]);if(a==="overdepth"){const c=Number(data.nextOverdepthCost);if(await confirmSpend(`Fund OD${r.overdepth+1}?`,`Enter Overdepth ${r.overdepth+1} and leave this safe extraction point.`,c,data.nextOverdepthDanger))return continueCrystalOverdepth(r.id);return null;}if(a==="extract")return extractCrystalCaverns(r.id);if(a==="settle")return settleCrystalCaverns(r.id);}
async function refresh(){const x=await loadCrystalDashboard();if(x.error){$("status").textContent=x.error.message;return;}data=x.data;render();}
document.addEventListener("click",async e=>{const a=e.target.closest("[data-action]")?.dataset.action;if(!a||busy)return;busy=true;render();try{const x=await act(a);if(x?.error)alert(x.error.message);}finally{busy=false;await refresh();}});refresh();
