export type GemdlePrimary = "Real" | "Fictional" | "Stupid" | "Anomalous";
export type GemdleSemantic =
  | "Aquatic" | "Celestial" | "Fiery" | "Frozen" | "Radioactive" | "Bloody"
  | "Golden" | "Radiant" | "Dark/Void" | "Organic/Living" | "Ancient/Fossil"
  | "Toxic" | "Corrupted/Glitched";

export type CanonicalGemTags = {
  primary: GemdlePrimary;
  semantic: GemdleSemantic[];
};

// Canonical 296-gem map finalized for Gemdle. Do not infer tags from names or descriptions.
export const GEMDLE_GEM_TAGS: Record<string, CanonicalGemTags> = {
  "Incandescity": { primary: "Fictional", semantic: ["Radiant"] },
  "Reminiscite": { primary: "Fictional", semantic: [] },
  "Heat Death": { primary: "Fictional", semantic: ["Dark/Void"] },
  "Finality": { primary: "Fictional", semantic: [] },
  "Glitched Gem": { primary: "Fictional", semantic: ["Corrupted/Glitched"] },
  "Heart of the Deep": { primary: "Fictional", semantic: ["Organic/Living"] },
  "almost secret": { primary: "Stupid", semantic: [] },
  "tonalite-trondhjemite-granodiorite": { primary: "Real", semantic: [] },
  "Ore+": { primary: "Fictional", semantic: ["Celestial","Organic/Living"] },
  "Cat ore": { primary: "Stupid", semantic: ["Organic/Living"] },
  "sutoronchiumushahouhoakinseki": { primary: "Real", semantic: [] },
  "one singular grain of sand": { primary: "Stupid", semantic: [] },
  "ton 618": { primary: "Stupid", semantic: ["Celestial","Dark/Void"] },
  "Tranquillityite": { primary: "Real", semantic: ["Celestial"] },
  "Reality Fragment": { primary: "Fictional", semantic: [] },
  "Aurorite": { primary: "Fictional", semantic: ["Radiant"] },
  "Liminalite": { primary: "Fictional", semantic: [] },
  "Serpentite": { primary: "Real", semantic: [] },
  "False Vacuum": { primary: "Fictional", semantic: ["Dark/Void"] },
  "Netherwrong": { primary: "Stupid", semantic: [] },
  "Armalcolite": { primary: "Real", semantic: ["Celestial"] },
  "Last Light": { primary: "Fictional", semantic: ["Radiant","Dark/Void"] },
  "where gem": { primary: "Stupid", semantic: [] },
  "Edscottite": { primary: "Real", semantic: ["Celestial"] },
  "Parallax": { primary: "Fictional", semantic: [] },
  "Blacksite Crystal": { primary: "Fictional", semantic: [] },
  "Hapkeite": { primary: "Real", semantic: ["Celestial"] },
  "Fluorotetraferriphlogopite": { primary: "Real", semantic: [] },
  "Thalassa": { primary: "Fictional", semantic: ["Aquatic"] },
  "Aurorium": { primary: "Fictional", semantic: ["Celestial","Radiant"] },
  "300": { primary: "Stupid", semantic: [] },
  "Yttrocolumbite-(Y)": { primary: "Real", semantic: [] },
  "Seraphite": { primary: "Real", semantic: [] },
  "Chronofracture": { primary: "Fictional", semantic: [] },
  "Panguite": { primary: "Real", semantic: ["Celestial"] },
  "the last gem": { primary: "Stupid", semantic: [] },
  "Crystalline Singularity": { primary: "Fictional", semantic: ["Celestial"] },
  "Ontological Shard": { primary: "Anomalous", semantic: [] },
  "Polaris": { primary: "Fictional", semantic: ["Celestial","Frozen","Radiant"] },
  "Chromaflux": { primary: "Fictional", semantic: [] },
  "Allendeite": { primary: "Real", semantic: ["Celestial"] },
  "Ascendentite": { primary: "Fictional", semantic: ["Celestial","Radiant"] },
  "Infernite": { primary: "Fictional", semantic: ["Fiery"] },
  "Asterism": { primary: "Fictional", semantic: ["Radiant"] },
  "Tistarite": { primary: "Real", semantic: ["Celestial"] },
  "Deadstar": { primary: "Fictional", semantic: ["Celestial","Dark/Void"] },
  "Eventide": { primary: "Fictional", semantic: ["Radiant"] },
  "Seifertite": { primary: "Real", semantic: [] },
  "Deepcore Geode": { primary: "Fictional", semantic: [] },
  "Tuite": { primary: "Real", semantic: ["Celestial"] },
  "Solarion": { primary: "Fictional", semantic: ["Celestial","Radiant","Fiery"] },
  "Unobtainium": { primary: "Fictional", semantic: [] },
  "Stishovite": { primary: "Real", semantic: [] },
  "noobium": { primary: "Stupid", semantic: [] },
  "First Light": { primary: "Fictional", semantic: ["Radiant"] },
  "Heart of Xy": { primary: "Fictional", semantic: [] },
  "Potassic-magnesio-fluoro-chloro-potassic-ferri-magnesiotaramite-potassic-chloro-ferri-magnesiotaramite": { primary: "Stupid", semantic: [] },
  "touch grass": { primary: "Stupid", semantic: [] },
  "Davemaoite": { primary: "Real", semantic: [] },
  "Frostspike": { primary: "Fictional", semantic: ["Frozen"] },
  "Osbornite": { primary: "Real", semantic: ["Celestial"] },
  "Verity": { primary: "Fictional", semantic: [] },
  "Bridgmanite": { primary: "Real", semantic: [] },
  "Griceite": { primary: "Real", semantic: [] },
  "Umbra shard": { primary: "Fictional", semantic: ["Celestial","Dark/Void"] },
  "Långbanshyttanite": { primary: "Real", semantic: [] },
  "Nullstone": { primary: "Fictional", semantic: ["Dark/Void"] },
  "Krotite": { primary: "Real", semantic: ["Celestial"] },
  "Akimotoite": { primary: "Real", semantic: [] },
  "Redcanyonite": { primary: "Real", semantic: [] },
  "Carmeltazite": { primary: "Real", semantic: [] },
  "Calmarite": { primary: "Fictional", semantic: [] },
  "Mantleheart": { primary: "Fictional", semantic: ["Fiery"] },
  "Majorite": { primary: "Real", semantic: [] },
  "Carbonado": { primary: "Real", semantic: [] },
  "Kochkarite": { primary: "Real", semantic: [] },
  "Fractured Reality": { primary: "Fictional", semantic: ["Corrupted/Glitched"] },
  "Haggertyite": { primary: "Real", semantic: [] },
  "Kuannersuite-(Ce)": { primary: "Real", semantic: [] },
  "Bazzite": { primary: "Real", semantic: [] },
  "Reidite": { primary: "Real", semantic: [] },
  "Zigrasite": { primary: "Real", semantic: [] },
  "Tazheranite": { primary: "Real", semantic: [] },
  "Totality": { primary: "Fictional", semantic: ["Radiant","Dark/Void"] },
  "Core of Oblivion": { primary: "Fictional", semantic: ["Celestial","Dark/Void"] },
  "22 karat diamond": { primary: "Stupid", semantic: [] },
  "Redshift Crystal": { primary: "Fictional", semantic: ["Celestial"] },
  "Loveringite": { primary: "Real", semantic: [] },
  "Hsianghualite": { primary: "Real", semantic: [] },
  "Ammolite": { primary: "Real", semantic: ["Ancient/Fossil"] },
  "Proustite": { primary: "Real", semantic: [] },
  "Sundown Crystal": { primary: "Fictional", semantic: ["Radiant"] },
  "Libyan Desert Glass": { primary: "Real", semantic: ["Ancient/Fossil"] },
  "False Diamond": { primary: "Fictional", semantic: [] },
  "Zirkelite": { primary: "Real", semantic: [] },
  "Peatite-(Y)": { primary: "Real", semantic: [] },
  "Neptunite": { primary: "Real", semantic: [] },
  "Londonite": { primary: "Real", semantic: [] },
  "Event Horizon": { primary: "Fictional", semantic: ["Celestial","Dark/Void"] },
  "Lanky Gem": { primary: "Fictional", semantic: [] },
  "Test Ore": { primary: "Fictional", semantic: [] },
  "Volcanic Achalite": { primary: "Fictional", semantic: [] },
  "Potassic-ferro-ferri-sadanagaite": { primary: "Real", semantic: [] },
  "Paradoxite": { primary: "Fictional", semantic: [] },
  "Nabesite": { primary: "Real", semantic: [] },
  "Presolar Moissanite": { primary: "Real", semantic: ["Celestial","Ancient/Fossil"] },
  "Routhierite": { primary: "Real", semantic: [] },
  "Beryllonite": { primary: "Real", semantic: [] },
  "Monochronite": { primary: "Fictional", semantic: [] },
  "Georgbarsanovite": { primary: "Real", semantic: [] },
  "Magnesiohögbomite": { primary: "Real", semantic: [] },
  "Ja-ore": { primary: "Fictional", semantic: [] },
  "Martian Opal": { primary: "Fictional", semantic: ["Celestial"] },
  "Holtite": { primary: "Real", semantic: [] },
  "Kornerupine": { primary: "Real", semantic: [] },
  "Jadarite": { primary: "Real", semantic: [] },
  "Hydroxycalciomicrolite": { primary: "Real", semantic: [] },
  "Borealite": { primary: "Fictional", semantic: [] },
  "Atlas Stone": { primary: "Fictional", semantic: [] },
  "Bismuth": { primary: "Real", semantic: [] },
  "Singularity Shard": { primary: "Fictional", semantic: ["Celestial","Dark/Void"] },
  "Crocoite": { primary: "Real", semantic: [] },
  "Nuummite": { primary: "Real", semantic: ["Ancient/Fossil"] },
  "Bobfergusonite": { primary: "Real", semantic: [] },
  "Chkalovite": { primary: "Real", semantic: [] },
  "π": { primary: "Stupid", semantic: [] },
  "Kurnakovite": { primary: "Real", semantic: [] },
  "Fluorcalciobritholite": { primary: "Real", semantic: [] },
  "e": { primary: "Stupid", semantic: [] },
  "Wulfenite": { primary: "Real", semantic: [] },
  "Raspite": { primary: "Real", semantic: [] },
  "Lunar Diamond": { primary: "Fictional", semantic: ["Celestial"] },
  "Afterglow": { primary: "Fictional", semantic: ["Radiant"] },
  "Hutchinsonite": { primary: "Real", semantic: [] },
  "Duolite": { primary: "Fictional", semantic: [] },
  "Twentiethite": { primary: "Fictional", semantic: [] },
  "Scheelite": { primary: "Real", semantic: [] },
  "Antimatter Crystal": { primary: "Fictional", semantic: ["Celestial"] },
  "Manganvesuvianite": { primary: "Real", semantic: [] },
  "Ekanite": { primary: "Real", semantic: ["Radioactive"] },
  "Moolooite": { primary: "Real", semantic: [] },
  "Sugilite": { primary: "Real", semantic: [] },
  "Pallasite Crystal": { primary: "Real", semantic: ["Celestial"] },
  "Vesuvianite": { primary: "Real", semantic: [] },
  "Paraershovite": { primary: "Real", semantic: [] },
  "Monthstone": { primary: "Stupid", semantic: [] },
  "cbf detected, loser!": { primary: "Stupid", semantic: [] },
  "Dark Matter": { primary: "Fictional", semantic: ["Celestial","Dark/Void"] },
  "Fate Crystal": { primary: "Fictional", semantic: [] },
  "Loading...": { primary: "Stupid", semantic: [] },
  "Ringwoodite": { primary: "Real", semantic: [] },
  "Rainbow Lattice Sunstone": { primary: "Real", semantic: ["Radiant"] },
  "Piemontite": { primary: "Real", semantic: [] },
  "Tremolite": { primary: "Real", semantic: [] },
  "Neutron Crystal": { primary: "Fictional", semantic: ["Celestial"] },
  "Corona Shard": { primary: "Fictional", semantic: ["Celestial","Radiant","Fiery"] },
  "Microlux": { primary: "Fictional", semantic: [] },
  "Hydrokenoelsmoreite": { primary: "Real", semantic: [] },
  "67": { primary: "Stupid", semantic: [] },
  "Jeromite": { primary: "Fictional", semantic: [] },
  "Meteorite Peridot": { primary: "Real", semantic: ["Celestial"] },
  "Axinite": { primary: "Real", semantic: [] },
  "Zektzerite": { primary: "Real", semantic: [] },
  "Weloganite": { primary: "Real", semantic: [] },
  "focus.": { primary: "Stupid", semantic: [] },
  "Stardust Crystal": { primary: "Fictional", semantic: ["Celestial","Ancient/Fossil"] },
  "Chronite": { primary: "Fictional", semantic: [] },
  "Papagoite": { primary: "Real", semantic: [] },
  "Seismic Crystal": { primary: "Fictional", semantic: [] },
  "Boleite": { primary: "Real", semantic: [] },
  "Chlorophoenicite": { primary: "Real", semantic: [] },
  "Sinhalite": { primary: "Real", semantic: [] },
  "Tugtupite": { primary: "Real", semantic: [] },
  "Fukalite": { primary: "Real", semantic: [] },
  "Fingerite": { primary: "Real", semantic: ["Toxic"] },
  "Ajoite": { primary: "Real", semantic: [] },
  "Probability Crystal": { primary: "Fictional", semantic: [] },
  "Void Opal": { primary: "Fictional", semantic: ["Dark/Void"] },
  "Euclase": { primary: "Real", semantic: [] },
  "Magnesiochloritoid": { primary: "Real", semantic: [] },
  "Black Diamond": { primary: "Real", semantic: [] },
  "Hibonite": { primary: "Real", semantic: ["Celestial"] },
  "Phenakite": { primary: "Real", semantic: [] },
  "Aether Quartz": { primary: "Fictional", semantic: [] },
  "Cryoshock": { primary: "Fictional", semantic: ["Frozen","Dark/Void"] },
  "Hackmanite": { primary: "Real", semantic: [] },
  "Natural Moissanite": { primary: "Real", semantic: [] },
  "97%": { primary: "Stupid", semantic: [] },
  "Carletonite": { primary: "Real", semantic: [] },
  "Scapolite": { primary: "Real", semantic: [] },
  "Kyawthuite": { primary: "Real", semantic: [] },
  "Chambersite": { primary: "Real", semantic: [] },
  "Umbrium": { primary: "Fictional", semantic: ["Dark/Void"] },
  "Red Diamond": { primary: "Real", semantic: [] },
  "Tinsleyite": { primary: "Real", semantic: [] },
  "Blue Garnet": { primary: "Real", semantic: [] },
  "Dioptase": { primary: "Real", semantic: [] },
  "Void Pearl": { primary: "Fictional", semantic: ["Dark/Void"] },
  "Charoite": { primary: "Real", semantic: [] },
  "Paraíba Tourmaline": { primary: "Real", semantic: [] },
  "Compression Quartz": { primary: "Fictional", semantic: [] },
  "error 404": { primary: "Stupid", semantic: ["Corrupted/Glitched"] },
  "Hauyne": { primary: "Real", semantic: [] },
  "Pallasite": { primary: "Real", semantic: ["Celestial"] },
  "Serendibite": { primary: "Real", semantic: [] },
  "Cummingtonite": { primary: "Real", semantic: [] },
  "Hemimorphite": { primary: "Real", semantic: [] },
  "Tsavorite": { primary: "Real", semantic: [] },
  "Diaspore": { primary: "Real", semantic: [] },
  "Moltenite": { primary: "Fictional", semantic: ["Fiery"] },
  "Star Fragment": { primary: "Fictional", semantic: ["Celestial"] },
  "Poudretteite": { primary: "Real", semantic: [] },
  "Eudialyte": { primary: "Real", semantic: [] },
  "Smithsonite": { primary: "Real", semantic: [] },
  "Uvarovite": { primary: "Real", semantic: [] },
  "Clinohumite": { primary: "Real", semantic: [] },
  "Amblygonite": { primary: "Real", semantic: [] },
  "Titanite": { primary: "Real", semantic: [] },
  "Eternal Glowstone": { primary: "Fictional", semantic: ["Radiant"] },
  "Nyx Obsidian": { primary: "Fictional", semantic: ["Dark/Void"] },
  "Jeremejevite": { primary: "Real", semantic: [] },
  "Danburite": { primary: "Real", semantic: [] },
  "hiding in your wifi": { primary: "Stupid", semantic: [] },
  "Pezzottaite": { primary: "Real", semantic: [] },
  "Amber": { primary: "Real", semantic: ["Ancient/Fossil","Organic/Living"] },
  "Rhodochrosite": { primary: "Real", semantic: [] },
  "Painite": { primary: "Real", semantic: [] },
  "unlucky gem": { primary: "Stupid", semantic: [] },
  "Musgravite": { primary: "Real", semantic: [] },
  "Taaffeite": { primary: "Real", semantic: [] },
  "Prehnite": { primary: "Real", semantic: [] },
  "Lodestone": { primary: "Real", semantic: [] },
  "Moonlit Quartz": { primary: "Fictional", semantic: ["Celestial","Frozen","Radiant"] },
  "Grandidierite": { primary: "Real", semantic: [] },
  "Demantoid": { primary: "Real", semantic: [] },
  "Mythril": { primary: "Fictional", semantic: [] },
  "Black Opal": { primary: "Real", semantic: [] },
  "Morganite": { primary: "Real", semantic: [] },
  "Red Beryl": { primary: "Real", semantic: [] },
  "Unakite": { primary: "Real", semantic: [] },
  "Uranium": { primary: "Real", semantic: ["Radioactive"] },
  "Drillstone": { primary: "Fictional", semantic: [] },
  "Benitoite": { primary: "Real", semantic: [] },
  "Kunzite": { primary: "Real", semantic: [] },
  "Alexandrite": { primary: "Real", semantic: [] },
  "Lapis Lazuli": { primary: "Real", semantic: [] },
  "Tektite": { primary: "Real", semantic: ["Celestial"] },
  "Howlite": { primary: "Real", semantic: [] },
  "Tanzanite": { primary: "Real", semantic: [] },
  "Larvikite": { primary: "Real", semantic: [] },
  "Iolite": { primary: "Real", semantic: [] },
  "Diamond": { primary: "Real", semantic: [] },
  "Lepidolite": { primary: "Real", semantic: [] },
  "Labradorite": { primary: "Real", semantic: [] },
  "The Bottom": { primary: "Anomalous", semantic: ["Dark/Void"] },
  "Emerald": { primary: "Real", semantic: [] },
  "Kyanite": { primary: "Real", semantic: [] },
  "Ruby": { primary: "Real", semantic: [] },
  "random rock I found outside": { primary: "Stupid", semantic: [] },
  "Rhodonite": { primary: "Real", semantic: [] },
  "Sapphire": { primary: "Real", semantic: [] },
  "Zephyrion": { primary: "Anomalous", semantic: [] },
  "Larimar": { primary: "Real", semantic: ["Aquatic"] },
  "Spinel": { primary: "Real", semantic: [] },
  "Eclipse Stone": { primary: "Fictional", semantic: ["Celestial","Radiant","Dark/Void"] },
  "Moonstone": { primary: "Real", semantic: [] },
  "Bloodstone": { primary: "Real", semantic: ["Bloody"] },
  "Zircon": { primary: "Real", semantic: [] },
  "Aventurine": { primary: "Real", semantic: [] },
  "the clock": { primary: "Fictional", semantic: [] },
  "Opal": { primary: "Real", semantic: [] },
  "Sunstone": { primary: "Real", semantic: ["Radiant"] },
  "Core Sample": { primary: "Fictional", semantic: [] },
  "Meteorite Fragment": { primary: "Real", semantic: ["Celestial"] },
  "Tourmaline": { primary: "Real", semantic: [] },
  "Azurite": { primary: "Real", semantic: [] },
  "Pyrite": { primary: "Real", semantic: [] },
  "Aquamarine": { primary: "Real", semantic: ["Aquatic"] },
  "Amazonite": { primary: "Real", semantic: [] },
  "Topaz": { primary: "Real", semantic: [] },
  "Jade": { primary: "Real", semantic: [] },
  "Tiger's Eye": { primary: "Real", semantic: [] },
  "Peridot": { primary: "Real", semantic: [] },
  "trashcan": { primary: "Stupid", semantic: [] },
  "Hadopelagic": { primary: "Anomalous", semantic: ["Aquatic","Dark/Void"] },
  "Citrine": { primary: "Real", semantic: [] },
  "Carnelian": { primary: "Real", semantic: [] },
  "Garnet": { primary: "Real", semantic: [] },
  "Sodalite": { primary: "Real", semantic: [] },
  "Amethyst": { primary: "Real", semantic: [] },
  "Chalcedony": { primary: "Real", semantic: [] },
  "Jasper": { primary: "Real", semantic: [] },
  "Malachite": { primary: "Real", semantic: [] },
  "Agate": { primary: "Real", semantic: [] },
  "Obsidian": { primary: "Real", semantic: [] },
  "Hematite": { primary: "Real", semantic: [] },
};

export function canonicalGemTags(name: unknown): CanonicalGemTags | null {
  return GEMDLE_GEM_TAGS[String(name ?? "")] ?? null;
}

