import { mountShell } from "../src/ui/shell.js";
import { supabase } from "../src/backend/supabase.js";
mountShell({page:"workbench",base:"../"});
const $=id=>document.getElementById(id); let recipes=[]; let selected=null; let inventory={materials:[],essence:[],gear:[]};
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
async function api(action,extra={}){const {data,error}=await supabase.functions.invoke("workbench",{body:{action,...extra}});if(error||data?.error)throw new Error(data?.message||data?.error||error?.message);return data;}
function have(name){return Number(inventory.materials.find(x=>x.material_name===name)?.quantity||0)}
function essence(t){return Number(inventory.essence.find(x=>x.essence_tier===t)?.quantity||0)}
function renderRecipes(){const q=$("recipeSearch").value.trim().toLowerCase();const list=recipes.filter(r=>!q||r.name.toLowerCase().includes(q)||String(r.tier).includes(q)).slice(0,300);$("recipes").innerHTML=list.map(r=>`<button class="recipe ${selected?.name===r.name?'active':''}" data-name="${esc(r.name)}"><span>T${r.tier}</span><b>${esc(r.name)}</b><small>${r.essence_cost} ${r.essence_tier} · ${Number(r.gem_power).toLocaleString()} GP</small></button>`).join("");$("recipes").querySelectorAll("button").forEach(b=>b.onclick=()=>selectRecipe(b.dataset.name));}
function selectRecipe(name){selected=recipes.find(r=>r.name===name);renderRecipes();renderRecipe();}
function renderRecipe(){if(!selected){$("recipeDetail").innerHTML=`<p class="muted">Select a recipe to see its exact PDF requirements.</p>`;return}const req=(selected.ingredients||[]).map(i=>{const h=(i.item==='TE'||i.item==='SE'||i.item==='LE'||i.item==='ME')?essence(i.item):have(i.item);return `<li class="${h>=i.qty?'ok':'missing'}"><span>${esc(i.item)}</span><b>${i.qty.toLocaleString()}</b><small>You have ${h.toLocaleString()}</small></li>`}).join("");$("recipeDetail").innerHTML=`<div class="recipe-title"><span>T${selected.tier}</span><h2>${esc(selected.name)}</h2></div><p>Essence cost: <b>${selected.essence_cost} ${selected.essence_tier}</b> · Gem Power: <b>${Number(selected.gem_power).toLocaleString()}</b></p><ul class="requirements">${req}</ul><button id="craft" class="btn btn--primary">Craft ${esc(selected.name)}</button><div id="craftStatus" class="status"></div>`;$("craft").onclick=craft;}
async function refresh(){inventory=await api("materials");$("essenceBar").innerHTML=["TE","SE","LE","ME"].map(t=>`<span>${t}: <b>${essence(t).toLocaleString()}</b></span>`).join("");renderInventory();renderRecipe();renderHistory();}
function renderInventory(){const rows=inventory.materials.slice(0,120);$("inventory").innerHTML=rows.map(x=>`<div class="inv-row"><span>${esc(x.material_name)}</span><b>${Number(x.quantity).toLocaleString()}</b></div>`).join("")||`<p class="muted">Dungeon materials appear here after you claim room rewards.</p>`;}
function renderHistory(){$("history").innerHTML=(inventory.gear||[]).map(g=>`<div class="gear-row"><b>${esc(g.stats?.recipe||g.source_enemy)}</b><span>${Number(g.gem_power||0).toLocaleString()} GP</span><small>${esc(g.quality)}</small></div>`).join("")||`<p class="muted">No crafted dungeon gear yet.</p>`;}
async function craft(){if(!selected)return;const status=$("craftStatus");$("craft").disabled=true;try{const d=await api("craft",{recipeName:selected.name});status.textContent=`Crafted ${selected.name} · ${Number(d.gemPower).toLocaleString()} Gem Power.`;await refresh();}catch(e){status.textContent=e.message;}finally{$("craft").disabled=false;}}
$("recipeSearch").addEventListener("input",renderRecipes);
(async()=>{try{const c=await api("catalog");recipes=c.recipes||[];renderRecipes();await refresh();}catch(e){$("status").textContent=e.message;}})();
