import { mountShell } from "../src/ui/shell.js";
import { supabase } from "../src/backend/supabase.js";
mountShell({ page: "dungeons", base: "../" });
const $=id=>document.getElementById(id); let roomIndex=[]; let currentRegion="Entrance"; let regionCache=new Map(); let run=null; let room=null;
const regions=["Entrance","Jungle","Beach & Sea","Mountain","Volcano","Hell","Dragon's Domain","Abyss","Sky Citadel","Time Rift","Genesis Core"];
const regionFile=r=>`./catalog/regions/${r.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/-$/,'')}.json`;
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
async function api(action,extra={}){const {data,error}=await supabase.functions.invoke("dungeons",{body:{action,...extra}});if(error||data?.error)throw new Error(data?.message||data?.error||error?.message);return data;}
async function loadIndex(){const r=await fetch("./catalog/index.json");roomIndex=await r.json(); $("roomCount").textContent=`${roomIndex.length.toLocaleString()} rooms`; renderRegionButtons(); renderRoomList();}
function renderRegionButtons(){const wrap=$("regions");wrap.innerHTML=regions.map(r=>`<button class="region-tab ${r===currentRegion?'active':''}" data-region="${esc(r)}">${esc(r)}</button>`).join("");wrap.querySelectorAll("button").forEach(b=>b.onclick=()=>{currentRegion=b.dataset.region;renderRegionButtons();renderRoomList();});}
function renderRoomList(){const q=$("roomSearch").value.trim().toLowerCase();const rooms=roomIndex.filter(r=>r.region===currentRegion&&(q===""||String(r.room).includes(q)||r.title.toLowerCase().includes(q)||r.zone.toLowerCase().includes(q))).slice(0,300);$("roomList").innerHTML=rooms.map(r=>`<button class="room-row" data-room="${r.room}"><span>#${String(r.room).padStart(4,'0')}</span><b>${esc(r.title.split(" — ")[0])}</b><em>${esc(r.zone)}</em><small>${esc(r.mob_level||'Boss encounter')}</small></button>`).join("")||`<p class="muted">No rooms match.</p>`;$("roomList").querySelectorAll("button").forEach(b=>b.onclick=()=>openRoom(Number(b.dataset.room)));}
async function loadRegionText(region){if(regionCache.has(region))return regionCache.get(region);const data=await (await fetch(regionFile(region))).json();regionCache.set(region,data);return data;}
async function openRoom(n){try{$("status").textContent="Loading room…";const region=roomIndex.find(x=>x.room===n)?.region||currentRegion;const data=await loadRegionText(region);const r=data.find(x=>x.room===n);if(!r)throw Error("Room catalog entry not found.");room=r;const server=await api("room",{roomNumber:n});renderRoom(r,server.boss);$("status").textContent="";}catch(e){$("status").textContent=e.message;}}
function renderRoom(r,boss){$("roomDetail").hidden=false;$("roomTitle").textContent=`Room ${String(r.room).padStart(4,'0')} · ${r.title.split(" — ")[0]}`;$("roomMeta").innerHTML=`<span>${esc(r.region)}</span><span>${esc(r.zone)} zone</span><span>Mob Lv ${esc(r.mob_level||'Boss')}</span><span>Key ${esc(r.key_chance||'—')}</span><span>Fog ${esc(r.fog_chance||'—')}</span>`;$("bossBadge").textContent=boss?`${boss.boss_name} · +${Number(boss.repeat_bonus)*100}% repeat bonus`:r.room_type?.startsWith("Boss")?"Boss room":"";$("pageOne").textContent=r.page1||"";$("pageTwo").textContent=r.page2||"";$("startRoom").onclick=()=>startRoom(r.room);$("roomDetail").scrollIntoView({behavior:"smooth",block:"start"});}
async function startRoom(n){try{$("combat").hidden=false;$('combatLog').textContent="Entering room…";const d=await api("start",{roomNumber:n});run=d.run;renderCombat(d.combatant);$('combat').scrollIntoView({behavior:"smooth",block:"start"});}catch(e){$('combatLog').textContent=e.message;}}
function renderCombat(enemy){if(!enemy){$('combatLog').textContent="Room cleared.";$('claim').hidden=false;return;}$('enemyName').textContent=enemy.name;$('enemyRank').textContent=`${enemy.rank}${enemy.mutated?` · ${enemy.mutationTier} mutated`:''}`;$('enemyHp').textContent=`${Math.max(0,Math.round(enemy.hp)).toLocaleString()} / ${Math.round(enemy.maxHp).toLocaleString()} HP`;$('hpFill').style.width=`${Math.max(0,Math.min(100,enemy.hp/enemy.maxHp*100))}%`;}
$('attack').onclick=async()=>{if(!run)return;try{$('attack').disabled=true;const d=await api("attack",{runId:run.id});run=d.run;$('combatLog').textContent=`Defeated ${d.defeated} · dealt ${Math.round(d.damage).toLocaleString()} damage.`;if(d.won){$('combatLog').textContent+=" Room cleared. Claim your rewards.";$('claim').hidden=false;}else if(d.lost){$('combatLog').textContent+=" You were defeated.";$('attack').disabled=true;}else renderCombat(d.combatant);}catch(e){$('combatLog').textContent=e.message;}finally{if(run?.status==='active')$('attack').disabled=false;}};
$('claim').onclick=async()=>{try{const d=await api("claim",{runId:run.id});$('combatLog').textContent=`Claimed ${d.materials?.length||0} material stacks and ${d.essence?.length||0} essence stacks.`;$('claim').hidden=true;$('attack').disabled=true;}catch(e){$('combatLog').textContent=e.message;}};
$('roomSearch').addEventListener('input',renderRoomList);loadIndex().catch(e=>$('status').textContent=e.message);
