import { mountShell } from "../../src/ui/shell.js";
import { deepSeaRequest } from "../../src/backend/cloudDeepSea.js";
import { invokeFunction } from "../../src/backend/invoke.js";
import { getSettings, updateSettings } from "../../src/ui/settings.js";
mountShell({page:"limited-events",base:"../../"});
const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let snapshot,timer;
const milestones=[[5,"The Reef Calls"],[10,"Beneath the Waves"],[15,"Into the Deep"],[20,"The Abyss Opens"],[25,"The Ocean Floor"],[30,"The Depths Are Satisfied"]];
function duration(ms){if(ms<=0)return"00d 00h 00m 00s";const s=Math.floor(ms/1000);return`${String(Math.floor(s/86400)).padStart(2,"0")}d ${String(Math.floor(s/3600)%24).padStart(2,"0")}h ${String(Math.floor(s/60)%60).padStart(2,"0")}m ${String(s%60).padStart(2,"0")}s`;}
function notice(text,bad=false){$("notice").textContent=text;$("notice").className=`notice show${bad?" bad":""}`;clearTimeout(notice.t);notice.t=setTimeout(()=>$("notice").className="notice",3500);}
function phaseClock(){clearInterval(timer);const loaded=Date.now(),server=Date.parse(snapshot.serverNow),run=snapshot.run;const tick=()=>{const now=server+Date.now()-loaded,target=snapshot.phase==="teaser"?Date.parse(run.starts_at):snapshot.phase==="active"?Date.parse(run.ends_at):Date.parse(run.redemption_ends_at);$("countdown").textContent=snapshot.phase==="archived"?"ARCHIVED":duration(target-now);};tick();timer=setInterval(tick,1000);}
function render(){const s=snapshot.state,phase=snapshot.phase,settings=getSettings();$("phase").textContent=phase.toUpperCase();$("teaser").classList.toggle("hidden",phase!=="teaser");$("event").classList.toggle("hidden",phase==="teaser");$("clockLabel").textContent=phase==="teaser"?"THE DESCENT BEGINS IN":phase==="active"?"THE TIDE RECEDES IN":phase==="redemption"?"REDEMPTION CLOSES IN":"THE SEA REMEMBERS";phaseClock();if(phase==="teaser")return;$("tokens").textContent=Number(s.tide_tokens).toLocaleString()+" TT";$("depth").textContent=`${s.depth_step} / 30`;$("neptuneState").textContent=s.neptune_owned?"FORGED":"LOCKED";$("poolState").textContent=(settings.rollPool||"normal").replace("deep_sea","DEEP SEA").toUpperCase();$("neptuneFeed").checked=s.neptune_auto_feed;$("depthFeed").checked=s.depths_auto_feed;const progress=new Map((snapshot.progress||[]).map(p=>[`${p.target}:${p.gem_name}`,Number(p.quantity)]));const recipe={Clay:500,"Salt Crystal":250,Seaweed:100,"Sand Rock":50,"Sea Salt Rock":25,"Prismarine Fragment":10,"Ancient Coin":5,Pearl:5,"Pearl of the Sea":1};$("recipe").innerHTML=Object.entries(recipe).map(([g,q])=>`<article><strong>${esc(g)}</strong><span>${progress.get("neptune:"+g)||0} / ${q}</span></article>`).join("");const step=Math.min(30,Number(s.depth_step)+1),req=(snapshot.requirements||[]).filter(r=>Number(r.step)===step);$("requirements").innerHTML=req.map(r=>`<article><strong>${esc(r.gem_name)}</strong><span>${progress.get("depths:"+r.gem_name)||0} / ${r.quantity}</span></article>`).join("")||"<p>The Depths are satisfied.</p>";$("milestone").textContent=milestones.find(([n])=>step<=n)?.[1]||milestones.at(-1)[1];$("catalogue").innerHTML=(snapshot.gems||[]).map(g=>`<article><span>1 in ${Number(g.rarity).toLocaleString()}</span><h3>${esc(g.name)}</h3><p>${esc(g.description)}</p></article>`).join("");const bought=new Set((snapshot.purchases||[]).map(p=>p.item_id));$("shop").innerHTML=(snapshot.shop||[]).map(i=>`<article><strong>${esc(i.item_id.replaceAll("-"," "))}</strong><span>${Number(i.price).toLocaleString()} TT</span><button data-buy="${esc(i.item_id)}" ${i.item_type==="cosmetic"&&bought.has(i.item_id)?"disabled":""}>${bought.has(i.item_id)&&i.item_type==="cosmetic"?"Owned":"Buy"}</button></article>`).join("");$("legacyGem").innerHTML=(snapshot.gems||[]).map(g=>`<option>${esc(g.name)}</option>`).join("");$("claimLegacy").disabled=phase!=="redemption"||Boolean(s.legacy_gem_name);$("craftNeptune").disabled=s.neptune_owned||phase==="archived";}
async function load(){try{snapshot=await deepSeaRequest();render();}catch(e){notice(e.message,true);}}
async function act(action,payload={}){try{const data=await deepSeaRequest(action,payload);snapshot=data.snapshot||data;render();notice("Deep Sea records updated.");}catch(e){notice(e.message,true);}}
document.addEventListener("click",e=>{const tab=e.target.closest("[data-tab]");if(tab){document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===tab));document.querySelectorAll("[data-panel]").forEach(x=>x.classList.toggle("hidden",x.dataset.panel!==tab.dataset.tab));return;}const buy=e.target.closest("[data-buy]");if(buy)act("buy",{itemId:buy.dataset.buy});});
async function setPool(pool){if(getSettings().autoRoll){notice("Stop Auto Roll before changing pools.",true);return;}await updateSettings({rollPool:pool});render();window.dispatchEvent(new CustomEvent("gem:roll-pool-changed",{detail:{pool}}));}
$("normalPool").onclick=()=>setPool("normal");$("deepSeaPool").onclick=()=>setPool("deep_sea");$("neptuneFeed").onchange=e=>act("setFeed",{target:"neptune",enabled:e.target.checked});$("depthFeed").onchange=e=>act("setFeed",{target:"depths",enabled:e.target.checked});$("craftNeptune").onclick=()=>act("craftNeptune");$("claimLegacy").onclick=()=>act("claimLegacy",{gemName:$("legacyGem").value});load();

const supplyNames={diver:"Diver",'tidal-rush':"Tidal Rush",pressure:"Pressure",'treasure-tonic':"Treasure Tonic",offering:"Offering to Neptune",'supply-crate':"Supply Crate",'abyssal-potion':"Abyssal Potion"};
function renderSupplies(){if(!snapshot||!$("supplies"))return;$("supplies").innerHTML=Object.entries(supplyNames).map(([id,name])=>`<article><strong>${name}</strong><span>Owned · ${Number(snapshot.consumables?.[id]||0).toLocaleString()}</span><button data-use="${id}" ${Number(snapshot.consumables?.[id]||0)<1?"disabled":""}>${id==='supply-crate'?'Open':id==='abyssal-potion'?'Drink & roll':'Use'}</button></article>`).join("");}
setInterval(renderSupplies,500);
document.addEventListener("click",async e=>{const button=e.target.closest("[data-use]");if(!button)return;const id=button.dataset.use;if(getSettings().autoRoll){notice("Stop Auto Roll before using Deep Sea supplies.",true);return;}if(id==='supply-crate')return act("openCrate");if(id==='abyssal-potion'){const {data,error}=await invokeFunction("roll",{batchSize:1,pool:"normal",abyssalPotion:true});if(error){notice(error.message||error.code,true);return;}window.dispatchEvent(new CustomEvent("gem:roll-complete",{detail:data}));notice(`${data.gem?.name||'A specimen'} emerged from the Abyssal Potion.`);return load();}return act("use",{itemId:id});});
