import{ensurePlayerAuth}from"../src/backend/auth.js";import{loadMiningCacheState,purchaseMiningCache,claimMiningCache}from"../src/backend/cloudLootboxes.js";import{mountShell}from"../src/ui/shell.js";import{notify}from"../src/ui/toast.js";import{formatMoney,formatCount,escapeHtml}from"../src/ui/format.js";
const shell=mountShell({page:"boosts",base:"../"}),moneyEl=document.getElementById("cacheMoney"),creditsEl=document.getElementById("cacheCredits"),useCreditsEl=document.getElementById("useCredits"),listEl=document.getElementById("cacheList"),pendingSection=document.getElementById("pendingSection"),pendingChoices=document.getElementById("pendingChoices"),historyEl=document.getElementById("cacheHistory");let state=null,busy=false;
const nextPrice=d=>d.prices?.[Number(state.counts?.[d.id]??0)]??null;const creditsFor=p=>Math.min(Number(state.wallet.credits??0),Math.floor(Number(p)/200000));
function rewardDetail(c){const r=c.reward??{};return Array.isArray(r.items)?r.items.map(i=>`${formatCount(i.quantity)}× ${i.id.replaceAll("-"," ")}`).join(" · "):c.description??"Account-bound reward";}
function render(){if(!state)return;const money=Number(state.wallet?.money??0);moneyEl.textContent=formatMoney(money);creditsEl.textContent=formatCount(state.wallet?.credits??0);shell.setWallet(money);listEl.innerHTML=(state.definitions??[]).map(d=>{const count=Number(state.counts?.[d.id]??0),price=nextPrice(d),limit=d.prices.length,credits=price?creditsFor(price):0,cash=price?Number(price)-credits*100000:0,pity=Number(state.pity?.[d.id]??0),meter=d.id==="prospector"?5:d.id==="deep"?8:6;return`<article class="cache-card cache-card--${escapeHtml(d.id)}"><div class="cache-card__head"><div><p class="cache-eyebrow">${count}/${limit} today</p><h3>${escapeHtml(d.name)}</h3></div><span class="cache-card__price">${price==null?"Daily limit reached":formatMoney(price)}</span></div><p>${escapeHtml(d.description)}</p><div class="cache-meter"><span>High guarantee</span><strong>${Math.min(pity,meter)}/${meter}</strong><i style="--progress:${Math.min(100,pity/meter*100)}%"></i></div>${price==null?`<button class="btn" disabled>Available tomorrow</button>`:`<p class="cache-card__discount">With credits: ${credits?`${credits} credit${credits===1?"":"s"} + ${formatMoney(cash)}`:"cash only"}</p><button class="btn btn--primary" data-buy="${escapeHtml(d.id)}" ${state.pending||busy||money<(useCreditsEl.checked?cash:price)?"disabled":""}>Reveal three rewards</button>`}</article>`}).join("");listEl.querySelectorAll("[data-buy]").forEach(b=>b.addEventListener("click",()=>buy(b.dataset.buy)));
pendingSection.hidden=!state.pending;pendingChoices.innerHTML=state.pending?(state.pending.choices??[]).map((c,i)=>`<button class="cache-choice" data-claim="${i}" ${busy?"disabled":""}><span class="cache-choice__quality">${["Supply","Rare","Premium","Perfect"][Number(c.quality)||0]}</span><strong>${escapeHtml(c.label)}</strong><small>${escapeHtml(rewardDetail(c))}</small><b>Choose this reward</b></button>`).join(""):"";pendingChoices.querySelectorAll("[data-claim]").forEach(b=>b.addEventListener("click",()=>claim(Number(b.dataset.claim))));const h=state.history??[];historyEl.innerHTML=h.length?h.map(e=>`<div class="cache-history__row"><span>${escapeHtml(e.selected_reward?.label??"Reward")}</span><small>${escapeHtml(e.cache_id)} · ${new Date(e.claimed_at).toLocaleString()}</small><strong>${formatMoney(e.cash_paid)}${Number(e.credits_used)>0?` + ${e.credits_used} credit${Number(e.credits_used)===1?"":"s"}`:""}</strong></div>`).join(""):`<p class="muted">No cache history yet.</p>`;}
async function buy(id){if(busy)return;busy=true;render();const{data,error}=await purchaseMiningCache(id,useCreditsEl.checked);busy=false;if(error){notify.error("Could not open cache",error.message);render();return}state=data;render();pendingSection.scrollIntoView({behavior:"smooth",block:"center"});notify.success("Cache revealed","Choose one of the three rewards.");}
async function claim(i){if(busy||!state.pending)return;busy=true;render();const label=state.pending.choices[i]?.label,{data,error}=await claimMiningCache(state.pending.id,i);busy=false;if(error){notify.error("Could not claim reward",error.message);render();return}state=data;render();notify.success("Reward claimed",label??"Added to your account.");}
useCreditsEl.addEventListener("change",render);async function start(){const auth=await ensurePlayerAuth();if(!auth)return;const{data,error}=await loadMiningCacheState();if(error){listEl.innerHTML=`<div class="empty"><p class="empty__title">Mining Caches unavailable</p><p>${escapeHtml(error.message)}</p></div>`;return}state=data;render()}start();
