create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id) on delete restrict,
  target_player_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);

alter table public.admin_audit_log enable row level security;

-- No browser policies are created. The table is accessed only by the
-- server-side admin Edge Function through its service-role client.
revoke all on public.admin_audit_log from anon, authenticated;
