import { ensurePlayerAuth } from "../src/backend/auth.js";
import { loadMuseum, placeMuseumExhibit, removeMuseumExhibit, expandMuseum, registerMuseumSpecimen } from "../src/backend/cloudMuseum.js";

const $=(id)=>document.getElementById(id); let state=null;
const money=(v)=>`$${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const count=(v)=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
const esc=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const capacityCosts={5:2000000,6:5000000,7:10000000,8:20000000,9:40000000,10:75000000};
function effectiveRarity(g){return Math.max(1,Number(g.effective_rarity||Number(g.rarity||1)*Math.max(1,Number(g.mutation_chance_multiplier||1))))}function estimate(g){const r=Math.max(1,Number(g.rarity||1)),e=effectiveRarity(g),ratio=Math.max(1,Number(g.final_weight||1)/Math.max(Number(g.base_weight||1),.000001)),m=(g.mutation_ids||[]).length;return 20*Math.log10(r)+Math.min(180,15*Math.log10(e))+Math.min(75,25*Math.log2(ratio))+[0,15,35,60,90][Math.min(4,m)]+(g.serial_number===1?100:g.serial_number<=10?60:g.serial_number<=50?35:g.serial_number<=100?20:g.serial_number<=500?10:0)}
function status(text,error=false){$("museumStatus").textContent=text;$("museumStatus").classList.toggle("error",error)}
function progress(def,specimens){const req=def.requirements||{},list=specimens||[];if(req.type==="count")return Math.min(list.length,req.count);if(req.type==="unique_gems")return Math.min(new Set(list.map(x=>x.gem_name)).size,req.count);if(req.type==="unique_mutations")return Math.min(new Set(list.flatMap(x=>x.mutation_ids||[])).size,req.count);if(req.type==="serial_count")return Math.min(list.filter(x=>x.serial_number!=null).length,req.count);if(req.type==="min_rarity")return Math.min(list.filter(x=>Number(x.rarity)>=Number(req.min)).length,req.count);return 0}
function render(){const p=state.profile;$("prestige").textContent=count(p.prestige);$("museumTier").textContent=p.tier;$("collectionCount").textContent=p.collections_completed;
 const occupied=new Map(state.exhibits.map(x=>[Number(x.slot),x]));$("museumSlots").innerHTML=Array.from({length:p.capacity},(_,i)=>{const slot=i+1,e=occupied.get(slot);return e?`<article class="museum-slot"><div><span class="museum-slot__number">Exhibit ${slot}</span><h3>${esc(e.snapshot.gem_name)}</h3><p>1 in ${count(e.snapshot.effective_rarity||e.snapshot.rarity)}</p><p>${(e.snapshot.mutation_ids||[]).length} mutations · ${count(e.snapshot.final_weight)}g</p></div><div><p class="museum-slot__score">${count(e.prestige)} Prestige</p><button class="btn" data-remove="${slot}">Remove</button></div></article>`:`<article class="museum-slot museum-slot--empty"><div><strong>Exhibit ${slot}</strong><p>Select a specimen below to place it here.</p></div></article>`}).join("");
 const next=p.capacity+1,cost=capacityCosts[next];$("expandButton").disabled=p.capacity>=10;$("expandButton").textContent=p.capacity>=10?"Museum fully expanded":`Unlock slot ${next} · ${money(cost)}`;renderSpecimens();renderCollections();}
function renderSpecimens(){const q=$("museumSearch").value.trim().toLowerCase(),sort=$("museumSort").value;let gems=state.inventory.filter(g=>!g.museum_locked&&String(g.gem_name).toLowerCase().includes(q));gems.sort((a,b)=>sort==="newest"?String(b.created_at).localeCompare(String(a.created_at)):sort==="rarity"?effectiveRarity(b)-effectiveRarity(a):estimate(b)-estimate(a));const empty=Array.from({length:state.profile.capacity},(_,i)=>i+1).filter(n=>!state.exhibits.some(e=>Number(e.slot)===n));$("specimenList").innerHTML=gems.length?gems.map(g=>`<article class="specimen"><div><h3>${esc(g.gem_name)} ${g.serial_number?`<small>#${count(g.serial_number)}</small>`:""}</h3><p>1 in ${count(effectiveRarity(g))} · ${count(g.final_weight)}g · ≈ ${count(estimate(g))} Prestige</p></div><div class="specimen__actions">${empty.length?`<select class="select" data-slot-for="${g.id}">${empty.map(s=>`<option value="${s}">Exhibit ${s}</option>`).join("")}</select><button class="btn btn--primary" data-place="${g.id}">Display</button>`:""}<button class="btn" data-register="${g.id}" ${g.locked?"disabled title=\"Unlock this gem first\"":""}>Register forever</button></div></article>`).join(""):`<p class="empty-message">No available specimens match this search.</p>`}
function renderCollections(){const exhibit=state.exhibits.map(e=>e.snapshot),registered=state.registrations.map(r=>r.specimen_snapshot),done=new Set(state.completedCollections.map(c=>c.collection_id));$("collectionList").innerHTML=state.collections.map(d=>{const list=d.kind==="showcase"?exhibit:registered,n=progress(d,list),target=Number(d.requirements.count||1),complete=d.kind==="permanent"?done.has(d.id):n>=target;return `<article class="collection ${complete?"completed":""}"><div class="collection__top"><div><span class="collection__kind">${esc(d.kind)}</span><h3>${esc(d.name)}</h3></div><strong>${complete?"Complete":`${n}/${target}`}</strong></div><p>${esc(d.description)}</p><p>+${count(d.prestige_reward)} Prestige${d.cosmetic_reward?` · ${esc(d.cosmetic_reward)}`:""}</p></article>`}).join("")}
async function refresh(){status("Opening the hall…");const {data,error}=await loadMuseum();if(error){status(error.message,true);return}state=data;render();status("")}
async function act(fn){status("Updating your museum…");const {error}=await fn();if(error){status(error.message,true);return}await refresh()}
$("museumSlots").addEventListener("click",e=>{const b=e.target.closest("[data-remove]");if(b&&confirm("Remove this specimen from its exhibit? It will remain locked in your inventory."))act(()=>removeMuseumExhibit(Number(b.dataset.remove)))});
$("specimenList").addEventListener("click",e=>{const place=e.target.closest("[data-place]"),reg=e.target.closest("[data-register]");if(place){const id=Number(place.dataset.place),slot=Number(document.querySelector(`[data-slot-for="${id}"]`).value);act(()=>placeMuseumExhibit(id,slot))}if(reg&&confirm("Permanent registration consumes this specimen forever. It may advance every matching permanent collection. Continue?"))act(()=>registerMuseumSpecimen(Number(reg.dataset.register)))});
$("expandButton").addEventListener("click",()=>{const next=state.profile.capacity+1;if(confirm(`Spend ${money(capacityCosts[next])} to permanently unlock exhibit slot ${next}?`))act(expandMuseum)});$("museumSearch").addEventListener("input",renderSpecimens);$("museumSort").addEventListener("change",renderSpecimens);
await ensurePlayerAuth();await refresh();
