import { progressMeter, stat, findSection, volcanicFinds, completionSummary, showExpeditionComplete } from "../src/ui/expeditionConsole.js";
import{mountShell}from"../src/ui/shell.js";import{loadVolcanicDashboard,startVolcanicDepths,fundVolcanicDepth,buyVolcanicMonitoring,buyVolcanicCooling,useVolcanicLift,sampleVolcanicMagma,continueVolcanicOverdepth,extractVolcanicDepths,settleVolcanicDepths}from"../src/backend/cloudExpeditions.js";import{formatMoney,escapeHtml}from"../src/ui/format.js";import{confirmDialog}from"../src/ui/dialog.js";mountShell({page:"expeditions",base:"../"});
const $=id=>document.getElementById(id),money=n=>formatMoney(Number(n||0));let data,busy=false;const btn=(label,action,secondary=false)=>`<button type="button" class="btn ${secondary?"":"btn--primary"}" data-action="${action}" ${busy?"disabled":""}>${label}</button>`;const state=r=>r.overdepth?"eruption":(["stable","heating","unstable","critical","eruption"].includes(r.activity_state)?r.activity_state:"unknown");const label=s=>({stable:"🟢 Stable",heating:"🟡 Heating",unstable:"🟠 Unstable",critical:"🔴 Critical",eruption:"🌋 Active Eruption",unknown:"❔ Unknown threshold"}[s]);
function controls(r){if(r.status==="active")return`<p>Make genuine gem rolls to advance expedition progress.</p>`;if(r.status==="awaiting_funding"){const d=r.depth+1,c=data.funding[d-1];return`<div class="action-grid">${btn(`Fund D${d} · ${money(c)}`,`fund:${d}`)}${r.depth>0?btn("Extract safely","extract",true):""}</div>`}if(r.status==="eruption_choice")return`<p class="warning"><strong>ERUPTION:</strong> 80% of unsecured cargo was destroyed.</p><div class="action-grid">${btn("Extract","extract",true)}${btn("Enter mandatory OD1","overdepth")}</div>`;if(r.status==="forced_extraction")return`<div class="action-grid">${btn("Complete forced extraction","extract")}</div>`;if(r.status==="ready_to_extract")return`<div class="action-grid">${btn("Extract safely","extract",true)}${btn(`Descend to OD${r.overdepth+1} · Free`,"overdepth")}</div>`;if(r.status==="extracted")return btn("Settle expedition","settle");return""}
function equipment(r){
 if(r.overdepth||!["awaiting_funding","ready_to_extract"].includes(r.status))return"";
 const at=[3,6,9].includes(r.depth),monitor=[400000,1250000,2000000],cool=[500000,1500000,4000000],tier=r.depth>=9?3:r.depth>=6?2:r.depth>=3?1:0,s=state(r);
 const options=(tier>r.monitoring_tier?btn(`Buy Monitoring ${tier} · ${money(monitor[tier-1])}`,`monitor:${tier}`,true):"")+
 (tier&&!r.suppression_used?btn(`Buy Cooling ${tier} · ${money(cool[tier-1])}`,`cool:${tier}`,true):"")+
 (at&&!(r.lift_used_depths||[]).includes(r.depth)?btn("Use free Evacuation Lift","lift",true):"")+
 (["unstable","critical"].includes(s)&&r.sampled_depth!==r.depth?btn(`Collect ${s} magma sample`,"sample"):"");
 return options?`<section class="volcanic-equipment"><h3>Expedition equipment</h3><div class="action-grid">${options}</div></section>`:"";
}
function activityMonitor(r){
 const s=state(r),activity=Math.max(0,Number(r.activity||0)),known=r.forecast_low!=null&&r.forecast_high!=null;
 const scale=Math.max(200,Math.ceil(Math.max(activity,Number(r.forecast_high||0))/50)*50);
 const low=Math.max(0,Number(r.forecast_low||0)),high=Math.max(low,Number(r.forecast_high||0));
 const descriptions={stable:"Activity is restrained. Every cleared depth adds heat.",heating:"The volcano is heating. Review your next descent.",unstable:"Eruption is approaching. Cargo and sampling carry growing risk.",critical:"Critical conditions. Prepare for an eruption.",eruption:"Active eruption. Every Overdepth stage risks your unsecured cargo.",unknown:"The eruption threshold is hidden."};
 return `<section class="volcanic-monitor volcanic-monitor--${s}" aria-label="Volcanic Activity"><div class="volcanic-monitor__head"><div><p class="exp-eyebrow">Eruption monitor</p><h3>${label(s)}</h3></div><div class="volcanic-activity"><strong>${activity}</strong><span>Activity</span></div></div><p>${descriptions[s]}</p>
 <div class="volcanic-activity-track" role="meter" aria-label="Activity, not percentage to eruption" aria-valuemin="0" aria-valuemax="${scale}" aria-valuenow="${activity}" aria-valuetext="${activity} Activity; ${known?`forecast ${low} to ${high}`:"eruption forecast unknown"}"><i style="width:${activity/scale*100}%"></i>${known?`<span class="volcanic-forecast-band" style="left:${low/scale*100}%;width:${(high-low)/scale*100}%"></span>`:""}</div><div class="volcanic-scale"><span>0 Activity</span><span>${scale} · display scale, not eruption point</span></div>
 <div class="volcanic-forecast"><div><span>Eruption forecast</span><strong>${known?`${low}–${high} Activity`:"Unknown"}</strong></div><small>${known?`Monitoring ${r.monitoring_tier} · striped band marks the forecast range`:"Monitoring reveals a range—not the true eruption point."}</small></div>${r.eruption_suppressed?'<p class="volcanic-suppressed">Cooling succeeded · Eruption temporarily suppressed</p>':""}</section>`;
}
function render(){
 const r=data.run;$("status").innerHTML=`<strong>Wallet ${money(data.money)}</strong><span>The true Eruption Point remains hidden.</span>`;
 if(!r)$("console").innerHTML=`<div class="volcanic-empty"><p class="exp-eyebrow">Volcanic Depths / Normal</p><h2>Plan your descent</h2><p>Fund ten depths, monitor Activity and decide when to bring your haul home.</p>${btn("Begin Volcanic Depths","start")}</div>`;
 else{
  const finds=volcanicFinds(r),events=[...(r.event_log||[])].filter(x=>!["artifact","cargo"].includes(x.kind)).reverse().slice(0,10);
  const cooling=r.cooling_tier?`Tier ${r.cooling_tier} · ${[0,20,30,40][r.cooling_tier]}%`:r.suppression_used?"Used":"None";
  $("console").innerHTML=`<section class="volcanic-overview"><div><p class="exp-eyebrow">Volcanic Depths / Normal</p><h2>${r.overdepth?`Overdepth ${r.overdepth}`:`Depth ${r.depth}`}</h2></div>${progressMeter(r.progress,r.target)}</section>
  ${activityMonitor(r)}<section class="volcanic-orders"><h3>Next move</h3>${controls(r)}</section>
  <div class="exp-stats volcanic-secondary">${stat("Danger",`${r.danger}%`,"Incident chance","risk")}${stat("Cooling",cooling,r.cooling_tier?"Automatic suppression chance":"One successful suppression per run")}${stat("Emergency Shelter",r.shelter_used?"Destroyed":"Intact","Absorbs the first OD Critical")}</div>
  ${equipment(r)}<div class="exp-stats volcanic-cargo">${stat("Secured cargo",money(r.secured_cargo),"Protected for extraction","safe")}${stat("Unsecured cargo",money(r.unsecured_cargo),"Includes duplicate artifact value","risk")}</div>
  <div class="volcanic-find-grid">${findSection("Normal Cargo Finds",finds.cargo,"No recorded cargo finds yet.","Original depth finds. Older runs may have totals only; no missing values are guessed.")}${findSection("Artifact Finds",finds.artifacts,"No artifacts discovered this run.","New Museum discoveries are protected. Duplicate value is unsecured until extraction.")}</div>
  <details class="volcanic-log"><summary>Recent Expedition Log <span>Incidents &amp; equipment</span></summary><ol>${events.map(x=>`<li>${escapeHtml(x.message)}</li>`).join("")||"<li>No incidents or equipment events yet.</li>"}</ol></details>`;
 }
 $("artifacts").innerHTML=(data.artifacts||[]).map(a=>`<div class="artifact-row ${a.registered?"is-owned":""}"><strong>${a.registered?"✓ ":""}${escapeHtml(a.name)}</strong><small>${escapeHtml(a.passive_name)}: ${escapeHtml(a.passive_description)} · Duplicate ${money(a.duplicate_value)}</small></div>`).join("");
}
async function confirmSpend(title,cost){return await confirmDialog({title,body:`<p>Cost: <strong>${money(cost)}</strong></p><p>Balance after: ${money(data.money-cost)}</p>`,confirmLabel:`Spend ${money(cost)}`,defaultAction:"cancel",preventEnter:true})==="confirm"}async function act(a){const r=data.run;if(a==="start")return startVolcanicDepths();if(a.startsWith("fund:")){const d=+a.split(":")[1],c=data.funding[d-1];return await confirmSpend(`Fund D${d}?`,c)?fundVolcanicDepth(r.id,d):null}if(a.startsWith("monitor:")){const t=+a.split(":")[1],c=[400000,1250000,2000000][t-1];return await confirmSpend("Buy Monitoring?",c)?buyVolcanicMonitoring(r.id,t):null}if(a.startsWith("cool:")){const t=+a.split(":")[1],c=[500000,1500000,4000000][t-1];return await confirmSpend("Buy Cooling Charge?",c)?buyVolcanicCooling(r.id,t):null}if(a==="lift")return useVolcanicLift(r.id);if(a==="sample"){const c=state(r)==="critical"?3000000:1500000;return await confirmSpend("Collect magma sample?",c)?sampleVolcanicMagma(r.id):null}if(a==="overdepth")return continueVolcanicOverdepth(r.id);if(a==="extract")return extractVolcanicDepths(r.id);if(a==="settle")return settleVolcanicDepths(r.id)}async function refresh(){const x=await loadVolcanicDashboard();if(x.error){$("status").textContent=x.error.message;return}data=x.data;render()}document.addEventListener("click",async e=>{const a=e.target.closest("[data-action]")?.dataset.action;if(!a||busy)return;busy=true;render();try{const before=data.run,x=await act(a);if(x?.error)alert(x.error.message);else showExpeditionComplete(completionSummary("Volcanic Depths",x,before))}finally{busy=false;await refresh()}});refresh();

startExpeditionRefresh(refresh,()=>busy);
import { startExpeditionRefresh } from "../src/ui/expeditionRefresh.js";
