-- Column definitions read from the live backend on 2026-09-08; no player data.
create role anon;
create role authenticated;
create role service_role;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');
create table public.best_roll_history (
id bigint not null generated by default as identity,
player_id uuid not null,
username text,
gem_name text not null,
rarity numeric not null,
final_weight numeric not null default 0,
value numeric not null default 0,
mutation_id text,
mutation_ids text[] not null default '{}'::text[],
mutation_multiplier numeric not null default 1,
roll_number bigint,
created_at timestamp with time zone not null default now(),
raw_luck numeric not null default 1,
base_luck numeric not null default 1,
effective_rarity numeric not null default 1
);
create table public.game_bundles (
id text not null,
name text not null,
icon text not null,
sort_order integer not null,
requires_first_six boolean not null default false
);
create table public.inventory_gems (
id bigint not null generated by default as identity,
player_id uuid not null,
gem_name text not null,
rarity integer not null,
base_weight double precision not null,
value_per_gram double precision not null,
rolled_weight_multiplier double precision not null,
rolled_weight double precision not null,
final_weight double precision not null,
value double precision not null,
locked boolean not null default false,
created_at timestamp with time zone not null default now(),
roll_number bigint,
luck_at_roll numeric,
mutation_id text,
mutation_multiplier numeric not null default 1,
mutation_ids text[] not null default '{}'::text[],
mutation_multipliers jsonb not null default '{}'::jsonb,
mutation_chance_multiplier numeric not null default 1,
serial_number bigint,
museum_locked boolean not null default false,
source_event_occurrence_id uuid,
source_event_key text,
event_properties jsonb not null default '{}'::jsonb,
value_multiplier_at_roll numeric not null default 1
);
create table public.museum_collection_completions (
player_id uuid not null,
collection_id text not null,
completed_at timestamp with time zone not null default now()
);
create table public.museum_collection_definitions (
id text not null,
name text not null,
description text not null,
kind text not null,
prestige_reward integer not null,
requirements jsonb not null,
cosmetic_reward text,
sort_order integer not null default 0,
enabled boolean not null default true
);
create table public.museum_exhibits (
player_id uuid not null,
slot integer not null,
specimen_id bigint not null,
prestige numeric not null default 0,
snapshot jsonb not null default '{}'::jsonb,
added_at timestamp with time zone not null default now()
);
create table public.player_achievement_cosmetics (
player_id uuid not null,
cosmetic_id text not null,
cosmetic_type text not null,
earned_at timestamp with time zone not null default now()
);
create table public.player_achievement_milestones (
player_id uuid not null,
ap integer not null,
claimed_at timestamp with time zone not null default now()
);
create table public.player_bundle_completions (
player_id uuid not null,
bundle_id text not null,
completed_at timestamp with time zone not null default now()
);
create table public.player_bundle_special_submissions (
player_id uuid not null,
requirement_id text not null,
specimen_snapshot jsonb not null,
submitted_at timestamp with time zone not null default now()
);
create table public.player_gem_mutation_combinations (
id bigint not null generated by default as identity,
player_id uuid not null,
gem_name text not null,
combination_key text not null,
mutation_ids text[] not null default '{}'::text[],
mutation_multipliers jsonb not null default '{}'::jsonb,
total_found bigint not null default 0,
highest_value numeric not null default 0,
first_discovered_at timestamp with time zone not null default now(),
last_discovered_at timestamp with time zone not null default now()
);
create table public.player_research_purchases (
player_id uuid not null,
node_id text not null,
purchased_at timestamp with time zone not null default now()
);
create table public.player_season_cosmetics (
player_id uuid not null,
cosmetic_id text not null,
cosmetic_type text not null,
season_id uuid,
earned_at timestamp with time zone not null default now()
);
create table public.player_titles (
player_id uuid not null,
title text not null,
color text not null default '#ffd166'::text,
updated_at timestamp with time zone not null default now()
);
create table public.players (
id uuid not null,
created_at timestamp with time zone not null default now(),
last_seen timestamp with time zone not null default now(),
next_roll_at timestamp with time zone,
inventory_capacity integer not null default 15,
money double precision not null default 0,
crafting_migrated boolean not null default false,
total_rolls bigint not null default 0,
rarest_gem_name text,
rarest_gem_rarity integer,
stats_migrated boolean not null default false,
legacy_save_migrated boolean not null default false,
username text,
lifetime_earnings numeric not null default 0,
coins bigint not null default 0,
mutation_luck double precision not null default 1,
gems_found_score numeric not null default 0,
showcase jsonb not null default '[]'::jsonb,
leaderboard_hidden boolean not null default false,
current_island_id uuid,
max_equipment_tier integer not null default 0,
pickaxe_tier integer not null default 0,
bag_tier integer not null default 0,
display_title text not null default ''::text,
display_title_color text not null default '#ffd166'::text,
legacy_cache_credits bigint not null default 0,
lifetime_money_burned double precision not null default 0,
rarity_resonance integer not null default 0,
gravitational_surge_progress integer not null default 0,
gravitational_surge_ready boolean not null default false,
bag_compression_progress integer not null default 0,
best_rare_natural_weight_100k double precision not null default 0,
best_rare_natural_weight_1m double precision not null default 0,
roll_lease_id uuid,
roll_lease_expires_at timestamp with time zone,
equipment_genuine_rolls bigint not null default 0,
equipment_state jsonb not null default '{}'::jsonb,
equipment_state_roll bigint not null default 0,
misty_mutation_boost_rolls integer not null default 0,
misty_mutation_boost_stacks integer not null default 0,
ancient_relic_boost_rolls integer not null default 0,
enchanted_relic_boost_rolls integer not null default 0
);
create table public.private_feature_definitions (
id uuid not null default gen_random_uuid(),
feature_kind text not null,
quest_type text,
name text not null,
description text not null default ''::text,
icon text not null default '◆'::text,
sort_order integer not null default 0,
enabled boolean not null default true,
starts_at timestamp with time zone,
ends_at timestamp with time zone,
prerequisites uuid[] not null default '{}'::uuid[],
requirements jsonb not null default '{"all": []}'::jsonb,
rewards jsonb not null default '[]'::jsonb,
unlocks jsonb not null default '[]'::jsonb,
metadata jsonb not null default '{}'::jsonb,
created_at timestamp with time zone not null default now(),
updated_at timestamp with time zone not null default now(),
admin_only boolean not null default false
);
create table public.private_feature_gems (
id uuid not null default gen_random_uuid(),
name text not null,
rarity double precision not null,
base_weight numeric not null,
value_per_gram numeric not null,
sort_order integer not null default 0,
enabled boolean not null default true,
starts_at timestamp with time zone,
ends_at timestamp with time zone,
metadata jsonb not null default '{}'::jsonb,
created_at timestamp with time zone not null default now(),
updated_at timestamp with time zone not null default now(),
description text not null default ''::text,
hide_rarity_until_discovered boolean not null default false,
title text not null default ''::text,
availability_mode text not null default 'always'::text,
daily_start_time time without time zone,
daily_end_time time without time zone,
availability_timezone text not null default 'Asia/Singapore'::text,
affected_by_luck boolean not null default true,
required_event_key text,
special_gem boolean not null default false
);
create table public.private_feature_progress (
id bigint not null generated by default as identity,
player_id uuid not null,
feature_id uuid not null,
current_value numeric not null default 0,
completed boolean not null default false,
reward_granted boolean not null default false,
completed_at timestamp with time zone,
reward_granted_at timestamp with time zone,
metadata jsonb not null default '{}'::jsonb,
updated_at timestamp with time zone not null default now(),
achievement_points_awarded integer not null default 0
);
create table public.research_nodes (
id text not null,
branch text not null,
stage smallint not null,
name text not null,
description text not null,
cost integer not null,
required_ap integer not null default 0,
prerequisites text[] not null default '{}'::text[],
effects jsonb not null default '{}'::jsonb,
sort_order integer not null,
enabled boolean not null default true
);
create table public.season_definitions (
id uuid not null default gen_random_uuid(),
name text not null,
description text not null default ''::text,
enabled boolean not null default false,
starts_at timestamp with time zone,
ends_at timestamp with time zone,
xp_per_roll numeric not null default 1,
tier_xp numeric not null default 1000,
tiers jsonb not null default '[]'::jsonb,
challenges jsonb not null default '[]'::jsonb,
modifiers jsonb not null default '{}'::jsonb,
metadata jsonb not null default '{}'::jsonb,
created_at timestamp with time zone not null default now(),
updated_at timestamp with time zone not null default now()
);
alter table public.players add primary key(id);


alter table public.player_achievement_cosmetics add primary key(player_id,cosmetic_id);
alter table public.player_season_cosmetics add primary key(player_id,cosmetic_id);
alter table public.player_achievement_milestones add primary key(player_id,ap);
alter table public.player_research_purchases add primary key(player_id,node_id);
alter table public.museum_collection_completions add primary key(player_id,collection_id);
alter table public.museum_exhibits add primary key(player_id,slot),add unique(specimen_id);
alter table public.player_bundle_completions add primary key(player_id,bundle_id);
grant usage on schema auth to anon,authenticated;
