import{ensurePlayerAuth}from"../src/backend/auth.js";
import{loadCloudPlayerState}from"../src/backend/cloudInventory.js";
import{loadExpeditionDashboard,fundMineDepth,chooseMineRoute,chooseSupplyCampService,continueMineOverdepth,extractMine,settleMine}from"../src/backend/cloudExpeditions.js";
import{mountShell}from"../src/ui/shell.js";import{formatMoney,escapeHtml}from"../src/ui/format.js";import{notify}from"../src/ui/toast.js";import{confirmDialog}from"../src/ui/dialog.js";
const shell=mountShell({page:"expeditions",base:"../"}),consoleNode=document.getElementById("mineConsole"),artifactList=document.getElementById("artifactList"),historyList=document.getElementById("historyList"),lootDialog=document.getElementById("lootTableDialog"),lootContent=document.getElementById("lootTableContent");
let dashboard=null,money=0,busy=false;
const statusLabel={awaiting_funding:"Awaiting funding",active:"Crew advancing",checkpoint_decision:"Supply Camp decision",awaiting_route:"Route decision",ready_to_extract:"D10 cleared",extracted:"Awaiting settlement",forced_extraction:"Forced extraction · settle cargo"};
const cargoValue=items=>(items||[]).reduce((sum,item)=>sum+Number(item.value||0),0),pct=run=>Math.min(100,run.target?run.progress/run.target*100:0);
function actionButton(label,action,kind="primary",disabled=false){return `<button class="btn btn--${kind}" data-mine-action="${action}" ${disabled?"disabled":""}>${escapeHtml(label)}</button>`;}
function routeChoices(run){if(run.depth===4)return `<div class="route-grid"><article><h3>Reinforced Tunnel</h3><p>Reduce Danger by 10 before D5.</p>${actionButton("Take reinforced tunnel","route:reinforced_tunnel")}</article><article><h3>Rich Vein</h3><p>25% stronger cargo, but +12 Danger.</p>${actionButton("Follow the rich vein","route:rich_vein","danger")}</article></div>`;return `<div class="route-grid"><article><h3>Supply Line</h3><p>Reduce Danger by 12 before D8.</p>${actionButton("Establish supply line","route:supply_line")}</article><article><h3>Unstable Descent</h3><p>40% stronger cargo, but +16 Danger.</p>${actionButton("Risk the descent","route:unstable_descent","danger")}</article></div>`;}
function fundingAction(run){const depth=run.depth+1,cost=dashboard.fundingCosts[depth-1];return actionButton(`Fund D${depth} · ${formatMoney(cost)}`,`fund:${depth}`,"primary",money<cost);}
function checkpointActions(run){const camp=dashboard.checkpointServices?.[String(run.depth)];if(!camp)return "";return actionButton(`Secure Current Cargo · ${formatMoney(camp.secureCost)}`,"camp:secure","default",money<camp.secureCost)+actionButton(`Full Resupply · ${formatMoney(camp.resupplyCost)}`,"camp:resupply","default",money<camp.resupplyCost)+fundingAction(run);}
function runActions(run){if(run.status==="checkpoint_decision")return checkpointActions(run)+actionButton("Extract voluntarily","extract","default");if(run.status==="awaiting_funding")return fundingAction(run)+actionButton("Extract voluntarily","extract","default");if(run.status==="awaiting_route")return routeChoices(run)+actionButton("Extract voluntarily","extract","default");if(run.status==="ready_to_extract")return actionButton(`Enter Overdepth ${dashboard.nextOverdepth} · ${formatMoney(dashboard.nextOverdepthCost,{compact:true})}`,"overdepth","primary",money<dashboard.nextOverdepthCost)+actionButton("Extract safely","extract","default");if(["extracted","forced_extraction"].includes(run.status))return actionButton("Settle recovered cargo","settle");return actionButton("Extract voluntarily","extract","default");}
const lootHeadings={economic:"Economic discoveries",normal:"Normal Museum artifacts",lost_workings:"Lost Workings / route-exclusive artifacts",d10:"D10 artifacts",overdepth:"Overdepth artifacts"};
function renderLootTable(){const opportunity=dashboard.artifactOpportunity;lootContent.innerHTML=`<div class="loot-summary"><strong>${escapeHtml(opportunity.description)}</strong><p>${(opportunity.baseChance*100).toFixed(1)}% base + ${(opportunity.depthIncrement*100).toFixed(1)}% per depth + ${(opportunity.overdepthIncrement*100).toFixed(1)}% per Overdepth, capped at ${(opportunity.maximumChance*100).toFixed(0)}%. A successful opportunity selects one eligible artifact by the conditional weights below; these are not extra drop chances.</p><p>Economic cargo: ${(dashboard.economicOpportunity.chance*100).toFixed(0)}% per completed depth.</p></div>`+Object.entries(lootHeadings).map(([category,heading])=>`<section class="loot-section"><h3>${heading}</h3><div class="loot-grid">${dashboard.lootCatalog.filter(item=>item.category===category).map(item=>`<article class="loot-entry"><div><strong>${escapeHtml(item.name)}</strong><br><small>${escapeHtml(item.eligibility_condition)}</small></div><div><small>Earliest</small><br>D${item.earliest_depth}${item.earliest_overdepth?` · OD${item.earliest_overdepth}+`:""}</div><div><small>Required route</small><br>${escapeHtml(item.required_route||"None")}</div><div><small>${item.kind==="artifact"?"Conditional weight":"Eligible chance"}</small><br>${item.kind==="artifact"?`${Number(item.weight)} weight`:"100%"}</div><div><small>Handling</small><br>${item.protected?"Protected":"Unsecured"}</div><div><small>Duplicate / status</small><br>${item.duplicate_value==null?"—":formatMoney(item.duplicate_value)} · ${item.kind==="economic"?"Not registered":item.registered?"Registered":"Undiscovered"}<br><small>${item.collection==="overdepth"?"Overdepth":"Normal Mine"}</small></div></article>`).join("")}</div></section>`).join("");}
function renderRun(run){if(!run){consoleNode.innerHTML=`<section class="card empty-mine"><p class="expedition-eyebrow">Abandoned Mine</p><h2>No active descent</h2><p>Fund D1 to dispatch a crew. Funding is permanent, but you may extract voluntarily after any roll.</p>${actionButton(`Fund D1 · ${formatMoney(dashboard.fundingCosts[0])}`,"fund:1","primary",money<dashboard.fundingCosts[0])}</section>`;return;}const secured=run.secured_cargo||[],unsecured=run.unsecured_cargo||[],discoveries=run.protected_discoveries||[],last=(run.incident_log||[]).at(-1);consoleNode.innerHTML=`<section class="card mine-run"><div class="mine-run__head"><div><span class="badge badge--accent">${escapeHtml(statusLabel[run.status]||run.status)}</span><h2>D${run.depth}${run.overdepth?` · Overdepth +${run.overdepth}`:""}</h2><p>${run.progress.toLocaleString()} / ${run.target.toLocaleString()} genuine rolls</p></div><div class="danger-meter"><span>Danger</span><strong>${run.danger}%</strong></div></div><div class="progress"><span style="width:${pct(run)}%"></span></div><div class="cargo-grid"><div><span>Secured cargo</span><strong>${formatMoney(cargoValue(secured))}</strong><small>${secured.length} finds survive forced extraction</small></div><div><span>Unsecured cargo</span><strong>${formatMoney(cargoValue(unsecured))}</strong><small>${unsecured.length} finds remain at risk</small></div><div><span>Protected discoveries</span><strong>${discoveries.length}</strong><small>Artifacts always return to the Museum</small></div></div>${last?`<p class="incident incident--${escapeHtml(last.severity)}"><strong>${escapeHtml(last.severity)} incident:</strong> ${Number(last.lost||0)} unsecured finds lost.</p>`:""}<div class="mine-actions">${runActions(run)}</div></section>`;}
function render(){shell.setWallet(money);renderRun(dashboard.run);renderLootTable();artifactList.innerHTML=dashboard.artifacts.length?dashboard.artifacts.map(a=>`<div class="history-row"><div><strong>${escapeHtml(a.artifact_name)}</strong><small> · found at D${a.depth_found}</small></div><span class="badge">Registered</span></div>`).join(""):"<p>No expedition artifacts registered yet.</p>";historyList.innerHTML=dashboard.history.length?dashboard.history.map(run=>`<div class="history-row"><div><strong>D${run.depth}${run.overdepth?` +${run.overdepth}`:""}</strong><small> · ${escapeHtml(run.extraction_reason||"extracted")} · ${new Date(run.settled_at).toLocaleString()}</small></div><span>${formatMoney(run.settlement?.cargoValue||0)}</span></div>`).join(""):"<p>No settled descents yet. Legacy expedition records remain preserved in storage.</p>";}
async function refresh(){const[player,result]=await Promise.all([loadCloudPlayerState(),loadExpeditionDashboard()]);if(result.error){notify.error("Expeditions unavailable",result.error.message);return;}money=Number(player?.money||0);dashboard=result.data;render();}
async function perform(action){const run=dashboard.run;let result;if(action.startsWith("fund:")){const depth=Number(action.split(":")[1]),cost=dashboard.fundingCosts[depth-1],choice=await confirmDialog({title:`Fund D${depth}?`,body:`<p>This commits ${formatMoney(cost)} to the descent.</p>`,confirmLabel:"Fund depth"});if(choice!=="confirm")return;result=await fundMineDepth(depth);}else if(action.startsWith("route:"))result=await chooseMineRoute(run.id,action.split(":")[1]);else if(action.startsWith("camp:"))result=await chooseSupplyCampService(run.id,action.split(":")[1]);else if(action==="overdepth"){const cost=dashboard.nextOverdepthCost,choice=await confirmDialog({title:`Enter Overdepth ${dashboard.nextOverdepth}?`,body:`<p><strong>${formatMoney(cost)}</strong> will be permanently spent.</p><p>Danger: <strong>${run.danger}% → ${dashboard.projectedDanger}%</strong></p><p>An incident can occur during entry. ${run.unsecured_cargo.length} unsecured cargo find${run.unsecured_cargo.length===1?" is":"s are"} currently at risk.</p>`,confirmLabel:`Spend ${formatMoney(cost)} and enter`});if(choice!=="confirm")return;result=await continueMineOverdepth(run.id);}else if(action==="extract"){const choice=await confirmDialog({title:"Extract now?",body:"<p>Voluntary extraction secures all current cargo and ends this descent.</p>",confirmLabel:"Extract"});if(choice!=="confirm")return;result=await extractMine(run.id,false);if(!result.error)result=await settleMine(run.id);}else if(action==="settle")result=await settleMine(run.id);if(result?.error)notify.error("Expedition action failed",result.error.message);else notify.success("Mine updated",action==="settle"||action==="extract"?"Cargo has been settled.":"The crew's orders were accepted.");await refresh();}
document.addEventListener("click",async event=>{const button=event.target.closest("[data-mine-action]");if(!button||busy)return;busy=true;button.disabled=true;try{await perform(button.dataset.mineAction);}finally{busy=false;}});
document.getElementById("viewLootTable").addEventListener("click",()=>lootDialog.showModal());lootDialog.addEventListener("click",event=>{if(event.target.closest("[data-close-loot]"))lootDialog.close();});
if(await ensurePlayerAuth()){await refresh();setInterval(()=>dashboard?.run&&refresh(),30000);}
