import { progressMeter, stat, findSection, mineFinds, rewardText, completionSummary, showExpeditionComplete } from "../src/ui/expeditionConsole.js";
import { loadHellArtifactFinds } from "../src/backend/cloudExpeditions.js";
import{ensurePlayerAuth}from"../src/backend/auth.js";
import{loadCloudPlayerState}from"../src/backend/cloudInventory.js";
import{loadExpeditionDashboard,loadHellDashboard,fundMineDepth,chooseMineRoute,chooseSupplyCampService,continueMineOverdepth,extractMine,settleMine,startHellMine,fundHellDepth,chooseHellEvent,revealHellCard,selectHellCard,continueHellOverdepth,extractHellMine,settleHellMine}from"../src/backend/cloudExpeditions.js";
import{mountShell}from"../src/ui/shell.js";import{formatMoney,escapeHtml}from"../src/ui/format.js";import{notify}from"../src/ui/toast.js";import{confirmDialog}from"../src/ui/dialog.js";
const shell=mountShell({page:"expeditions",base:"../"}),consoleNode=document.getElementById("mineConsole"),artifactList=document.getElementById("artifactList"),lootDialog=document.getElementById("lootTableDialog"),lootContent=document.getElementById("lootTableContent");
let dashboard=null,hellDashboard=null,money=0,busy=false,hellFinds=[],hellFindsAvailable=true;
const statusLabel={awaiting_funding:"Awaiting funding",active:"Crew advancing",checkpoint_decision:"Supply Camp decision",awaiting_route:"Route decision",ready_to_extract:"D10 cleared",extracted:"Awaiting settlement",forced_extraction:"Forced extraction · settle cargo"};
const artifactPassives={"miners-lamp":"+2% additive Roll Speed","surveyors-compass":"+3% Weight Luck","silver-pick":"+5% Weight Multiplier","foreman-seal":"+3% normal gem sale value","canary-charm":"10% relative reduction to Critical incident chance","vein-prism":"+5% additive Luck","descent-chain":"5% relative reduction to Danger gained from descending","deepcore-map":"+5% relative Expedition artifact chance","clockwork-drill":"+5% additive Roll Speed","royal-claim":"5% relative reduction to player-market transaction fees","black-geode":"×1.05 mutation chance","bedrock-crown":"×1.05 final gem value"};
const cargoValue=items=>(items||[]).reduce((sum,item)=>sum+Number(item.value||0),0),pct=run=>Math.min(100,run.target?run.progress/run.target*100:0);
function actionButton(label,action,kind="primary",disabled=false){return `<button class="btn btn--${kind}" data-mine-action="${action}" ${disabled||busy?"disabled":""}>${escapeHtml(label)}</button>`;}
const titleCase=value=>String(value||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
function objectiveText(objective){if(!objective)return "Preparing objective…";const target=Number(objective.target||0).toLocaleString(),fallback=objective.fallback?` or ${Number(objective.fallback).toLocaleString()} rolls`:"";const descriptions={roll_count:`Make ${target} rolls`,rarity_hunt:`Roll rarity 1/${target} or rarer`,weight_hunt:`Roll at least ${target}× displayed weight`,mutation_hunt:`Roll ${target} mutated gems`,value_generated:`Generate ${formatMoney(objective.target)} displayed value`,total_weight:`Accumulate ${target}g displayed weight`,rare_or_grind:`Roll rarity 1/${target} or rarer${fallback}`,weight_or_grind:`Roll at least ${target}× weight${fallback}`,combined:`On one gem, hit 1/${target} rarity and ${objective.weightTarget}× weight${fallback}`};return descriptions[objective.family]||titleCase(objective.family);}
function hellCardEffect(card,run){const tier=Number(card.tier||0),danger=tier?`+${tier*2} Danger`:"Raises Danger",doom=run.overdepth&&tier?` · +${[0,2,5,10][tier]} Doom`:"";if(card.kind==="lesser")return{minor_danger:"Adds 2–5 Danger.",next_incident:"Adds 5 percentage points to the next incident check.",next_reveal_tax:"Raises the next card reveal price by 15%.",recovery_wear:"Reduces emergency unsecured-cargo recovery by 3 percentage points.",lost_opportunity:"Adds 2–5 Danger.",mercy:"Reduces Doom by 1–5 unless Hope Extinguished is active."}[card.key]||"A short-lived consequence.";if(!tier)return{danger_surge:"Raises Danger; its tier is hidden by Torn Records.",incident_pressure:"Raises Danger and the next incident chance; its tier is hidden.",reveal_tax:"Raises Danger and future reveal prices; its tier is hidden.",recovery_damage:"Raises Danger and weakens emergency recovery; its tier is hidden.",danger_floor:"Raises Danger and the expedition's minimum Danger; its tier is hidden.",conditional_risk:"Raises Danger; its tier is hidden."}[card.key]||"Curse strength hidden by Torn Records.";const effects={danger_surge:`Adds ${5+tier*5} Danger.`,incident_pressure:`${danger} and +${tier*5} percentage points to the next incident check.`,reveal_tax:`${danger} and raises future card reveal prices by ${tier*25}%.`,recovery_damage:`${danger} and reduces emergency recovery by ${tier*3} percentage points.`,danger_floor:`${danger} and raises minimum Danger by ${3+tier*2}.`,conditional_risk:`${danger}.`};return`${effects[card.key]||danger}${doom}`;}
function hellCard(card,state,run){const faceUp=card.revealed||state.selectedCard?.slot===card.slot;if(!faceUp)return `<article class="hell-card hell-card--hidden"><strong>Face-down card</strong><p>No free information.</p><div>${actionButton("Reveal",`hell-reveal:${card.slot}`,"default")}${actionButton("Choose",`hell-card:${card.slot}`,"danger")}</div></article>`;const tier=card.kind==="curse"?card.tier?` · Tier ${card.tier}`:" · Tier hidden":"";return `<article class="hell-card hell-card--${escapeHtml(card.kind)}"><strong>${escapeHtml(card.name)}${tier}</strong><p class="hell-card__type">${card.kind==="curse"?"Curse":"Lesser consequence"}</p><p class="hell-card__effect">${escapeHtml(hellCardEffect(card,run))}</p><div>${state.phase==="cards"?actionButton("Choose this card",`hell-card:${card.slot}`,card.kind==="curse"?"danger":"primary"):""}</div></article>`;}
function selectedHellCardResult(run,state){const card=state.selectedCard;if(!card||state.phase==="cards")return"";const tier=card.kind==="curse"?` · Tier ${Number(card.tier||1)}`:"";const severity=state.lastIncident?.severity;const incident=severity?`${titleCase(severity)} incident occurred.`:"No incident occurred.";return`<section class="hell-resolution" aria-live="polite"><p class="expedition-eyebrow">Chosen card revealed</p><h3>${escapeHtml(card.name)}${tier}</h3><p><strong>${card.kind==="curse"?"Curse":"Lesser consequence"}:</strong> ${escapeHtml(hellCardEffect(card,run))}</p><p class="hell-resolution__incident hell-resolution__incident--${escapeHtml(severity||"none")}">${escapeHtml(incident)}</p></section>`;}
function hellEventEffect(option){const effects=[`${option.dangerDelta>0?"+":""}${Number(option.dangerDelta||0)} Danger`];if(option.secureCargo)effects.push("secure all current cargo");if(option.cargoValue)effects.push(`add ${formatMoney(option.cargoValue)} unsecured cargo`);if(option.incidentDelta)effects.push(`${option.incidentDelta>0?"+":""}${option.incidentDelta}pp next incident chance`);if(option.revealTaxDelta)effects.push(`${Math.round(option.revealTaxDelta*100)}% future reveal prices`);if(option.recoveryPenaltyDelta)effects.push(`${Math.round(option.recoveryPenaltyDelta*100)}pp emergency recovery penalty`);return effects.join(" · ");}
function hellActions(run,state){if(run.depth===0)return actionButton(`Fund D1 · ${formatMoney(hellDashboard.config.depthCosts[0])}`,"hell-fund:1","primary",money<Number(hellDashboard.config.depthCosts[0]));if(run.status==="forced_extraction")return actionButton("Recover what remains","hell-extract","danger");if(run.status==="extracted")return actionButton("Settle recovered cargo","hell-settle");if(state.phase==="event")return (state.event?.options||[]).map(option=>`<article><h3>${escapeHtml(option.label)}</h3><p>${escapeHtml(option.info)} information</p><p class="hell-event__effect">${escapeHtml(hellEventEffect(option))}</p>${actionButton(option.cost?`${formatMoney(option.cost)} · Choose`:"Choose free option",`hell-event:${option.id}`,option.dangerDelta>0?"danger":"primary",money<Number(option.cost||0))}</article>`).join("");if(state.phase==="cards")return (state.cards||[]).map(card=>hellCard(card,state,run)).join("");if(run.status==="ready_to_extract"){const descend=run.depth<10?actionButton(`Fund D${run.depth+1} · ${formatMoney(hellDashboard.config.depthCosts[run.depth])}`,`hell-fund:${run.depth+1}`,"primary",money<Number(hellDashboard.config.depthCosts[run.depth])):actionButton(run.overdepth?`Descend to OD${run.overdepth+1} · Free`:"Enter Overdepth · Free","hell-overdepth","danger");return descend+actionButton("Extract safely","hell-extract","default");}return "";}
function renderHellRun(run){
 const state=run.hell_state||{},objective=state.objective||{},danger=run.danger==null?run.dangerBand:`${run.danger}%`;
 const finds=mineFinds(run,hellDashboard?.hellArtifacts||[],hellFinds);
 const threshold=Number(hellDashboard.config.doomThreshold||90),doom=Number(state.doom||0);
 const phase=run.status==="ready_to_extract"?"Stage cleared · extraction available":run.status==="active"?({cards:"Choose a card",event:"Encounter decision",objective:"Crew advancing"}[state.phase]||titleCase(state.phase)):statusLabel[run.status]||titleCase(state.phase);
 consoleNode.innerHTML=`<section class="card mine-run mine-run--hell">
 <div class="mine-run__head"><div><p class="exp-eyebrow">Abandoned Mine / Hell</p><h2>${run.overdepth?`Overdepth ${run.overdepth}`:`Depth ${run.depth||1}`}</h2><span class="mine-phase">${escapeHtml(phase)}</span></div><div class="mine-danger"><span>Danger</span><strong>${escapeHtml(danger)}</strong><small>Incident risk</small></div></div>
 <div class="mine-objective"><p>${escapeHtml(objectiveText(objective))}</p>${progressMeter(objective.progress,objective.target,"Objective Progress")}<small>${Number(objective.rolls||0).toLocaleString()} genuine rolls this stage</small></div>
 <section class="mine-doom"><div><strong>Doom</strong><span>${doom} / ${threshold}</span></div>${progressMeter(doom,threshold,"Doom toward next Break")}<p class="exp-note">${run.overdepth?"Doom rises with descent and card consequences.":"Doom is introduced in Overdepth."} ${(state.doomBreaks||[]).length} Doom Breaks endured.</p></section>
 <section class="mine-decision"><div class="exp-panel__head"><h3>${state.phase==="cards"?"Choose your consequence":state.phase==="event"?"Crew encounter":"Crew orders"}</h3></div>${run.status==="active"&&state.phase==="objective"?'<p class="exp-note">Make genuine gem rolls to complete the objective and reveal the next decision.</p>':""}<div class="mine-actions hell-actions">${hellActions(run,state)}</div></section>
 ${selectedHellCardResult(run,state)}
 ${state.lastDoomBreak?`<p class="incident incident--critical"><strong>Last Doom Break:</strong> ${escapeHtml(titleCase(state.lastDoomBreak))}</p>`:""}
 <div class="exp-stats mine-cargo-status">${stat("Secured cargo",formatMoney(cargoValue(run.secured_cargo)),"Always recovered","safe")}${stat("Unsecured cargo",formatMoney(cargoValue(run.unsecured_cargo)),"Emergency recovery may lose cargo","risk")}${stat("Artifacts at risk",(run.unsecured_cargo||[]).filter(x=>x.kind==="artifact").length,"Critical extraction will lose them")}</div>
 <div class="mine-find-grid">${findSection("Normal Cargo Finds",finds.cargo,"No ordinary cargo held.","Current cargo values, after losses.")}${findSection("Artifact Finds",finds.artifacts,"No artifact finds yet.",hellFindsAvailable?"New discoveries need extraction; duplicate rewards are awarded immediately.":"Full duplicate history needs the expedition metadata migration. Current held artifacts are shown.")}</div>
 ${state.hellCache?`<details class="mine-reward"><summary>Hell Cache awarded${state.weeklyMythicAwarded?" · Weekly Mythic Potion awarded":""}</summary><ul>${[state.hellCache.highEnd,...(state.hellCache.minor||[])].map(x=>`<li>${escapeHtml(rewardText(x))}</li>`).join("")}</ul></details>`:""}</section>`;
}
function routeChoices(run){if(run.depth===4)return `<div class="route-grid"><article><h3>Reinforced Tunnel</h3><p>Reduce Danger by 10 before D5.</p>${actionButton("Take reinforced tunnel","route:reinforced_tunnel")}</article><article><h3>Rich Vein</h3><p>25% stronger cargo, but +12 Danger.</p>${actionButton("Follow the rich vein","route:rich_vein","danger")}</article></div>`;return `<div class="route-grid"><article><h3>Supply Line</h3><p>Reduce Danger by 12 before D8.</p>${actionButton("Establish supply line","route:supply_line")}</article><article><h3>Unstable Descent</h3><p>40% stronger cargo, but +16 Danger.</p>${actionButton("Risk the descent","route:unstable_descent","danger")}</article></div>`;}
function fundingAction(run){const depth=run.depth+1,cost=dashboard.fundingCosts[depth-1];return actionButton(`Fund D${depth} · ${formatMoney(cost)}`,`fund:${depth}`,"primary",money<cost);}
function checkpointActions(run){const camp=dashboard.checkpointServices?.[String(run.depth)];if(!camp)return "";return actionButton(`Secure Current Cargo · ${formatMoney(camp.secureCost)}`,"camp:secure","default",money<camp.secureCost)+actionButton(`Full Resupply · ${formatMoney(camp.resupplyCost)}`,"camp:resupply","default",money<camp.resupplyCost)+fundingAction(run);}
function runActions(run){if(run.status==="checkpoint_decision")return checkpointActions(run)+actionButton("Extract voluntarily","extract","default");if(run.status==="awaiting_funding")return fundingAction(run)+actionButton("Extract voluntarily","extract","default");if(run.status==="awaiting_route")return routeChoices(run)+actionButton("Extract voluntarily","extract","default");if(run.status==="ready_to_extract")return actionButton(`Descend to OD${dashboard.nextOverdepth} · Free`,"overdepth","primary")+actionButton("Extract safely","extract","default");if(["extracted","forced_extraction"].includes(run.status))return actionButton("Settle recovered cargo","settle");return actionButton("Extract voluntarily","extract","default");}
const lootHeadings={economic:"Economic discoveries",normal:"Normal Museum artifacts",lost_workings:"Lost Workings / route-exclusive artifacts",d10:"D10 artifacts",overdepth:"Overdepth artifacts"};
function renderLootTable(){const opportunities=dashboard.artifactOpportunities||[];lootContent.innerHTML=`<div class="loot-summary"><strong>Independent artifact opportunities</strong>${opportunities.map(o=>`<p><strong>${escapeHtml(o.name)}:</strong> ${escapeHtml(o.description)}${o.curve?` Curve: ${o.curve.map((chance,i)=>`D${i+1} ${(chance*100).toFixed(0)}%`).join(" · ")}`:""}</p>`).join("")}<p>Each successful opportunity selects one eligible artifact from its named pool by the weights below. Duplicates remain possible; undiscovered artifacts are never guaranteed. Economic cargo is awarded on every completed depth.</p></div>`+Object.entries(lootHeadings).map(([category,heading])=>`<section class="loot-section"><h3>${heading}</h3><div class="loot-grid">${dashboard.lootCatalog.filter(item=>item.category===category).map(item=>`<article class="loot-entry"><div><strong>${escapeHtml(item.name)}</strong><br><small>${escapeHtml(item.eligibility_condition)}</small></div><div><small>Opportunity / pool</small><br>${escapeHtml(item.opportunity.replaceAll("_"," "))}</div><div><small>Earliest</small><br>D${item.earliest_depth}${item.earliest_overdepth?` · OD${item.earliest_overdepth}+`:""}</div><div><small>Pool weight</small><br>${Number(item.weight)}</div><div><small>Handling</small><br>${item.protected?"Protected":"Unsecured"}</div><div><small>Duplicate / status</small><br>${item.duplicate_value==null?"—":formatMoney(item.duplicate_value)} · ${item.kind==="economic"?"Not registered":item.registered?"Registered":"Undiscovered"}<br><small>${item.collection==="overdepth"?"Overdepth":"Normal Mine"}</small></div></article>`).join("")}</div></section>`).join("");}
function renderHellLootTable(){const artifacts=[{name:"Charred Miner's Tag",od:1,odds:"1/8 · 12.5%",duplicate:"Curse Fragment ×1"},{name:"Melted Chain Link",od:3,odds:"1/12 · 8.33%",duplicate:"Curse Fragment ×2"},{name:"Crimson Geode",od:6,odds:"1/16 · 6.25%",duplicate:"Legendary Potion ×1"},{name:"Extinguished Hell-Lantern",od:10,odds:"1/20 · 5%",duplicate:"Curse Fragment ×5"},{name:"Doomstone",od:15,odds:"1/16 · 6.25%",duplicate:"Legendary Potion ×2"},{name:"Eye of the Bottomless Mine",od:20,odds:"1/10 · 10%",duplicate:"Mythic Potion ×1"}];const highEnd=["Legendary Potion ×2 — 30%","Legendary Potion ×3 — 22%","Mythic Potion ×1 — 20%","Ancient Relic ×2 — 12%","Legendary Potion ×5 — 8%","Mythic Potion ×2 — 4%","Hell premium reward — 2.5%","Hell cosmetic — 1%","Jackpot — 0.5%"];lootContent.innerHTML=`<div class="loot-summary loot-summary--hell"><strong>Abandoned Mine: Hell</strong><p>Clearing D10 awards one Hell Cache. Up to five successful clears per UTC week also award a guaranteed Mythic Potion.</p><p>Every cleared Overdepth performs one independent check for every artifact currently eligible.</p><p><strong>Warning:</strong> newly discovered artifacts remain unsecured. Voluntary extraction registers them; Critical extraction loses them.</p></div><section class="loot-section"><h3>Hell Overdepth artifacts</h3><div class="loot-grid">${artifacts.map(item=>`<article class="loot-entry"><div><strong>${escapeHtml(item.name)}</strong><br><small>Abandoned Mine: Hell collection</small></div><div><small>Eligible</small><br>OD${item.od}+</div><div><small>Chance per clear</small><br>${item.odds}</div><div><small>First discovery</small><br>Unsecured Museum artifact</div><div><small>Registered duplicate</small><br>${escapeHtml(item.duplicate)}</div></article>`).join("")}</div></section><section class="loot-section"><h3>Hell Cache · one high-end roll</h3><div class="hell-loot-list">${highEnd.map(item=>`<p>${escapeHtml(item)}</p>`).join("")}</div></section><section class="loot-section"><h3>Hell Cache · three minor rolls</h3><div class="hell-loot-list"><p>Curse Fragment ×1 — 45%</p><p>Curse Fragment ×2 — 25%</p><p>Curse Fragment ×3 — 10%</p><p>Random Tier III Potion ×1 — 15%</p><p>Random Tier III Potion ×2 — 5%</p></div></section>`;}
function renderRun(run){
 if(run?.mode==="hell"){renderHellRun(run);return;}
 if(!run){const normalCost=Number(dashboard?.fundingCosts?.[0]||100000),hellCost=Number(hellDashboard?.config?.depthCosts?.[0]||100000);consoleNode.innerHTML=`<section class="card empty-mine"><p class="exp-eyebrow">Abandoned Mine</p><h2>Choose a descent</h2><p>Ten depths. Two very different ways down.</p><div class="mode-grid"><article><h3>Normal</h3><p>Route forks, Supply Camps and protected Museum discoveries. Choose when to secure your haul.</p>${actionButton(`Fund D1 · ${formatMoney(normalCost)}`,"fund:1","primary",money<normalCost)}</article><article class="mode-card--hell"><h3>Hell Mode</h3><p>Hidden cards, curses and Doom. No Supply Camps—money buys information, never certainty.</p>${actionButton(`Enter Hell · D1 ${formatMoney(hellCost)}`,"hell-start","danger",money<hellCost)}</article></div></section>`;return;}
 const secured=run.secured_cargo||[],unsecured=run.unsecured_cargo||[],discoveries=run.protected_discoveries||[],last=(run.incident_log||[]).at(-1),finds=mineFinds(run,dashboard?.artifacts||[]);
 const phase=run.status==="ready_to_extract"?(run.overdepth?"Overdepth cleared":"D10 cleared"):statusLabel[run.status]||run.status;
 const context=run.status==="checkpoint_decision"?"Supply Camp · Secure your haul or keep descending":run.status==="awaiting_route"?"Route fork · Choose the crew’s path":run.status==="active"?"Crew advancing · Make genuine gem rolls":"Crew orders";
 consoleNode.innerHTML=`<section class="card mine-run"><div class="mine-run__head"><div><p class="exp-eyebrow">Abandoned Mine / Normal</p><h2>${run.overdepth?`Overdepth ${run.overdepth}`:`Depth ${run.depth}`}</h2><span class="mine-phase">${escapeHtml(phase)}</span></div><div class="mine-danger"><span>Danger</span><strong>${run.danger}%</strong><small>Checked on descent</small></div></div>
 <div class="mine-objective">${progressMeter(run.progress,run.target,"Depth Progress")}</div>
 <div class="mine-route-strip"><span>D1–D10</span><span>Camp D3 / D6 / D9</span><span>${run.route_d4?escapeHtml(titleCase(run.route_d4)):"Route fork D4"}</span><span>${run.route_d7?escapeHtml(titleCase(run.route_d7)):"Route fork D7"}</span></div>
 <section class="mine-decision"><h3>${escapeHtml(context)}</h3><div class="mine-actions">${runActions(run)}</div></section>
 ${last?`<p class="incident incident--${escapeHtml(last.severity)}"><strong>${escapeHtml(titleCase(last.severity))} incident:</strong> ${formatMoney(Number(last.valueLost||0))} value lost.</p>`:""}
 <div class="exp-stats mine-cargo-status">${stat("Secured cargo",formatMoney(cargoValue(secured)),"Survives forced extraction","safe")}${stat("Unsecured cargo",formatMoney(cargoValue(unsecured)),"At risk on descent","risk")}${stat("Protected artifacts",discoveries.length,"Always return for settlement")}</div>
 <div class="mine-find-grid">${findSection("Normal Cargo Finds",finds.cargo,"Clear a depth to recover cargo.","Current held cargo, after any incident losses.")}${findSection("Artifact Finds",finds.artifacts,"No artifacts discovered this run.","Museum discoveries and duplicate rewards remain separate from ordinary cargo.")}</div></section>`;
}
function artifactHistoryRow(artifact){const passive=artifactPassives[artifact.artifact_key];return `<div class="history-row artifact-history-row"><div><strong>${escapeHtml(artifact.artifact_name)}</strong><small> · found at D${artifact.depth_found}</small>${passive?`<small class="artifact-passive"><span>Passive</span>${escapeHtml(passive)}</small>`:""}</div><span class="badge">Registered</span></div>`;}
function render(){shell.setWallet(money);const run=hellDashboard?.run?.mode==="hell"?hellDashboard.run:dashboard?.run;renderRun(run);if(run?.mode==="hell")renderHellLootTable();else if(dashboard?.lootCatalog)renderLootTable();const normalArtifactKeys=new Set((dashboard?.lootCatalog||[]).filter(item=>item.kind==="artifact").map(item=>item.key)),normalArtifacts=(dashboard?.artifacts||[]).filter(artifact=>normalArtifactKeys.has(artifact.artifact_key)),hellArtifacts=hellDashboard?.hellArtifacts||[];const progress=(dashboard?.artifactCollections||[]).map(c=>`<div class="history-row"><strong>${c.collection==="overdepth"?"Overdepth collection":"Normal Mine collection"}</strong><span>${c.registered} / ${c.total}</span></div>`).join("");artifactList.innerHTML=`<div class="history-row"><strong>Abandoned Mine: Hell</strong><span>${hellArtifacts.length} / 6 · ${Number(hellDashboard?.curseFragments||0)} Curse Fragments</span></div>`+progress+([...normalArtifacts,...hellArtifacts].length?[...normalArtifacts,...hellArtifacts].map(artifactHistoryRow).join(""):"<p>No expedition artifacts registered yet.</p>");}
async function refresh(){const[player,result,hell]=await Promise.all([loadCloudPlayerState(),loadExpeditionDashboard(),loadHellDashboard()]);if(result.error||hell.error){notify.error("Expeditions unavailable",result.error?.message||hell.error?.message);return;}money=Number(player?.money||0);dashboard=result.data;hellDashboard=hell.data;
 if(hellDashboard?.run?.mode==="hell"){const finds=await loadHellArtifactFinds(hellDashboard.run.id);hellFindsAvailable=!finds.error;hellFinds=finds.data||[];}else hellFinds=[];
 render();}
async function perform(action){const run=hellDashboard?.run?.mode==="hell"?hellDashboard.run:dashboard?.run;let result;
if(action==="hell-start"||action.startsWith("hell-fund:")){const depth=action==="hell-start"?1:Number(action.split(":")[1]),cost=Number(hellDashboard.config.depthCosts[depth-1]),choice=await confirmDialog({title:`Fund Hell D${depth}?`,body:`<p>This commits ${formatMoney(cost)}. Hell has no Supply Camps.</p>`,confirmLabel:"Enter Hell"});if(choice!=="confirm")return;result=await fundHellDepth(depth);
}else if(action.startsWith("hell-event:")){const option=action.split(":")[1];result=await chooseHellEvent(run.id,option);
}else if(action.startsWith("hell-reveal:")){const slot=Number(action.split(":")[1]),cost=Number(hellDashboard.config.revealCosts[run.depth-1]),choice=await confirmDialog({title:"Reveal this card?",body:`<p>The server will reveal this card for ${formatMoney(cost)}. You may still choose another.</p>`,confirmLabel:"Pay and reveal"});if(choice!=="confirm")return;result=await revealHellCard(run.id,slot);
}else if(action.startsWith("hell-card:")){const slot=Number(action.split(":")[1]),choice=await confirmDialog({title:"Choose this Hell card?",body:"<p>The consequence and incident check resolve immediately.</p>",confirmLabel:"Choose card"});if(choice!=="confirm")return;result=await selectHellCard(run.id,slot);
}else if(action==="hell-overdepth"){const choice=await confirmDialog({title:run.overdepth?`Descend to OD${run.overdepth+1}?`:"Enter Overdepth?",body:`<p>The descent is free, but you’re risking your <strong>ENTIRE unsecured cargo</strong>. Overdepth also introduces Doom. Doom rises as you descend, and reaching its limit triggers a Doom Break.</p><p>You’re committing to the next OD stage. Voluntary extraction is available again after clearing it. Continue?</p><p>Doom: ${Number(run.hell_state?.doom||0)} / ${Number(hellDashboard.config.doomThreshold||90)}. ${run.unsecured_cargo?.filter(item=>item.kind==="artifact").length||0} new artifacts are unsecured.</p>`,confirmLabel:"Descend",cancelLabel:"Cancel",defaultAction:"cancel",preventEnter:true});if(choice!=="confirm")return;result=await continueHellOverdepth(run.id);
}else if(action==="hell-extract"){const forced=run.status==="forced_extraction",choice=await confirmDialog({title:forced?"Begin emergency recovery?":"Extract safely?",body:forced?"<p>All secured cargo returns. Only a random share of eligible unsecured cargo can be recovered; new artifacts are lost.</p>":"<p>All secured and unsecured cargo returns, and new artifacts are registered.</p>",confirmLabel:forced?"Recover cargo":"Extract safely"});if(choice!=="confirm")return;result=await extractHellMine(run.id);if(!result.error)result=await settleHellMine(run.id);
}else if(action==="hell-settle")result=await settleHellMine(run.id);
else if(action.startsWith("fund:")){const depth=Number(action.split(":")[1]),cost=dashboard.fundingCosts[depth-1],choice=await confirmDialog({title:`Fund D${depth}?`,body:`<p>This commits ${formatMoney(cost)} to the descent.</p>`,confirmLabel:"Fund depth"});if(choice!=="confirm")return;result=await fundMineDepth(depth);
}else if(action.startsWith("route:"))result=await chooseMineRoute(run.id,action.split(":")[1]);else if(action.startsWith("camp:"))result=await chooseSupplyCampService(run.id,action.split(":")[1]);else if(action==="overdepth"){const choice=await confirmDialog({title:`Descend to OD${dashboard.nextOverdepth}?`,body:`<p>The descent is free, but you leave this safe extraction point.</p><p>Danger: <strong>${run.danger}% → ${dashboard.projectedDanger}%</strong></p><p>An incident can occur during entry. ${run.unsecured_cargo.length} unsecured cargo find${run.unsecured_cargo.length===1?" is":"s are"} currently at risk.</p>`,confirmLabel:"Descend free",defaultAction:"cancel"});if(choice!=="confirm")return;result=await continueMineOverdepth(run.id);}else if(action==="extract"){const choice=await confirmDialog({title:"Extract now?",body:"<p>Voluntary extraction secures all current cargo and ends this descent.</p>",confirmLabel:"Extract"});if(choice!=="confirm")return;result=await extractMine(run.id,false);if(!result.error)result=await settleMine(run.id);}else if(action==="settle")result=await settleMine(run.id);
const receipt=completionSummary("Abandoned Mine",result,run,hellFindsAvailable?hellFinds:null);
if(result?.error)notify.error("Expedition action failed",result.error.message);else notify.success("Mine updated",action.includes("settle")||action.includes("extract")?"Cargo has been settled.":"The crew's orders were accepted.");await refresh();if(receipt)showExpeditionComplete(receipt);}
document.addEventListener("click",async event=>{const button=event.target.closest("[data-mine-action]");if(!button||busy)return;busy=true;button.disabled=true;try{await perform(button.dataset.mineAction);}finally{busy=false;if(dashboard)render();}});
document.getElementById("viewLootTable").addEventListener("click",()=>lootDialog.showModal());lootDialog.addEventListener("click",event=>{if(event.target.closest("[data-close-loot]"))lootDialog.close();});
if(await ensurePlayerAuth()){await refresh();setInterval(()=>!busy&&(dashboard?.run||hellDashboard?.run)&&refresh(),30000);}
