import { ensurePlayerAuth } from "../src/backend/auth.js";
import { loadCloudPlayerState } from "../src/backend/cloudInventory.js";
import { loadExpeditionDashboard,enterExpedition,abandonExpedition,rerollExpeditionQuest } from "../src/backend/cloudExpeditions.js";
import { mountShell } from "../src/ui/shell.js";
import { formatMoney,escapeHtml } from "../src/ui/format.js";
import { notify } from "../src/ui/toast.js";
import { confirmDialog } from "../src/ui/dialog.js";

const shell=mountShell({page:"expeditions",base:"../"});
const dailyCards=document.getElementById("dailyCards"),weeklyCards=document.getElementById("weeklyCards"),activeArea=document.getElementById("activeArea"),historyList=document.getElementById("historyList");
let dashboard=null,money=0;
const DETAILS={daily:{standard:{quests:2,bonus:"65% Tier II pair · 25% Tier III · 8% Enchant Relic · 2% Legendary"},deep:{quests:3,bonus:"45% Tier III pair · 25% Legendary · 20% Enchant · 8% two Enchant · 2% Ancient"},void:{quests:4,bonus:"35% Legendary · 25% two Enchant · 20% Tier III set · 15% Ancient · 5% Mythic"}},weekly:{standard:{quests:4,bonus:"60% Enchant Relic · 30% Legendary · 10% Ancient"},deep:{quests:5,bonus:"45% two Enchant · 30% Legendary · 20% Ancient · 5% Mythic"},void:{quests:6,bonus:"35% three Enchant · 30% Ancient · 20% two Ancient · 10% Mythic · 5% Mythic + Ancient"}}};
const REWARD_CHOICES={daily:{standard:[["mixed","Mixed: 2 different Tier II + 1 Tier III"],["lucky","3 Lucky Potions II"],["speed","3 Speed Potions II"],["fortune","3 Fortune Potions II"],["mass","3 Mass Potions II"]],deep:[["balanced","Balanced: one of every Tier II"],["forge","1 Enchant Relic + 1 random Tier III"],["lucky","2 Lucky Potions III"],["speed","2 Speed Potions III"],["fortune","2 Fortune Potions III"],["mass","2 Mass Potions III"]],void:[["power","1 Legendary + 2 different Tier III"],["forge","2 Enchant Relics + 2 different Tier III"],["ancient","1 Ancient Relic"]]},weekly:{standard:[["legendary","1 Legendary Potion"],["enchant","2 Enchant Relics"],["lucky","6 Lucky Potions III"],["speed","6 Speed Potions III"],["fortune","6 Fortune Potions III"],["mass","6 Mass Potions III"]],deep:[["ancient_forge","1 Ancient + 2 Enchant Relics"],["legendary_forge","2 Legendary Potions + 2 Enchant Relics"],["mythic","1 Mythic Potion"]],void:[["mythic_ancient","1 Mythic Potion + 1 Ancient Relic"],["ancient_cache","3 Ancient Relics"],["legendary_forge","2 Legendary Potions + 5 Enchant Relics"]]}};

function countdown(value){const ms=Math.max(0,new Date(value).getTime()-Date.now()),d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000);return `${d?`${d}d `:""}${h}h ${m}m`;}
function questProgress(q){const p=q.progress||{},t=q.target||{};switch(q.template){case"excavation_quota":case"rapid_extraction":case"rarity_quota":case"heavy_haul":case"mutation_quota":case"potion_assisted":case"high_grade_mining":return [p.count||0,t.count||1];case"rarity_score":case"weight_score":case"mutation_score":return[p.score||0,t.score||1];case"rarity_breakthrough":case"exceptional_specimen":case"mutation_breakthrough":return[p.score||0,t.fallback||1];case"mineral_diversity":return[(p.names||[]).length,t.names];case"tier_survey":return[(p.tiers||[]).length,t.tiers];case"sample_collection":return[Object.values(p.counts||{}).filter(v=>v>=t.copies).length,t.names];case"alchemical_variety":return[Object.values(p.families||{}).filter(v=>v>=t.per_family).length,t.families];case"relic_offering":return[p.points||0,t.points];case"relic_discovery":case"ancient_breakthrough":return[p.points||0,t.points];case"sustained_operation":return[Object.values(p.days||{}).filter(v=>v>=t.daily).length,t.days];default:return[0,1];}}
function targetText(q){const t=q.target||{};if(q.template==="rapid_extraction")return `${t.count.toLocaleString()} rolls in ${Math.round(t.seconds/60)} minutes`;if(q.template==="sustained_operation")return `${t.daily.toLocaleString()} rolls on ${t.days} UTC days`;if(t.multiplier)return `${t.multiplier}× multiplier${t.fallback?` or ${t.fallback} score`:""}`;if(t.rarity)return `Base rarity 1/${Number(t.rarity).toLocaleString()}${t.count?` · ${t.count} finds`:t.fallback?` or ${t.fallback} score`:""}`;if(t.copies)return `${t.copies} copies each of ${t.names} gems`;if(t.per_family)return `${t.per_family} rolls in ${t.families} families`;if(t.points)return `${t.points} points${t.rolls?` or ${Number(t.rolls).toLocaleString()} rolls`:""}`;const entry=Object.entries(t)[0];return entry?`${Number(entry[1]).toLocaleString()} ${entry[0]}`:"Personal target";}
function renderQuest(q,e){const [now,target]=questProgress(q),pct=q.completed_at?100:Math.min(100,now/target*100),rerollCost=e.entry_fee*(e.cadence==="daily"?.2:.15),hasAlternative=!(q.category==="rolling"&&e.difficulty==="standard");return `<article class="quest ${q.completed_at?"quest--complete":""}"><div class="quest__head"><div><span class="badge">${escapeHtml(q.category)}</span><h3>${escapeHtml(q.title)}</h3></div><strong>${q.completed_at?"Complete":`${Number(now).toLocaleString()} / ${Number(target).toLocaleString()}`}</strong></div><p>${escapeHtml(q.description)}</p><div class="quest__bar"><span style="width:${pct}%"></span></div><div class="quest__foot"><small>${q.completed_at?"Objective secured":escapeHtml(targetText(q))}</small>${!q.completed_at&&hasAlternative&&e.rerolls_used<e.rerolls_max?`<button class="btn btn--sm" data-reroll="${q.id}">Reroll · ${formatMoney(rerollCost)}</button>`:""}</div></article>`;}
function renderActive(){const active=[dashboard.daily.active,dashboard.weekly.active].filter(Boolean);activeArea.innerHTML=active.map(e=>`<section class="card active-expedition"><div class="active-expedition__head"><div><span class="badge badge--accent">${e.cadence}</span><h2>${e.difficulty} Expedition</h2><p>Ends in ${countdown(e.period_end)} · Rerolls ${e.rerolls_used}/${e.rerolls_max}</p></div><button class="btn btn--danger" data-abandon="${e.id}">Abandon</button></div><div class="quest-list">${e.quests.map(q=>renderQuest(q,e)).join("")}</div></section>`).join("");}
function renderCards(cadence,node){const state=dashboard[cadence];node.innerHTML=["standard","deep","void"].map(d=>{const fee=dashboard.fees[cadence][d],info=DETAILS[cadence][d],disabled=Boolean(state.active)||(cadence==="daily"?(state.entriesUsed>=2||(d==="void"&&state.voidUsed)):state.entriesUsed>=1)||money<fee,options=REWARD_CHOICES[cadence][d].map(([value,label])=>`<option value="${value}">${escapeHtml(label)}</option>`).join("");return `<article class="card expedition-card expedition-card--${d}"><div class="expedition-card__head"><h3>${d}</h3><span class="badge">${info.quests} quests</span></div><div class="expedition-card__price">${formatMoney(fee)}</div><label class="expedition-reward"><span>Choose guaranteed reward</span><select data-reward-choice="${cadence}:${d}" ${disabled?"disabled":""}>${options}</select></label><ul><li>Personal randomized objectives</li><li>One additional random bonus reward</li><li>No cash reward</li></ul><details><summary>Bonus chances</summary><p>${escapeHtml(info.bonus)}</p></details><button class="btn btn--primary" data-enter="${cadence}:${d}" ${disabled?"disabled":""}>${money<fee?"Not enough money":state.active?"Expedition active":"Enter expedition"}</button></article>`}).join("");}
function render(){shell.setWallet(money);document.getElementById("dailyReset").textContent=countdown(dashboard.daily.periodEnd);document.getElementById("weeklyReset").textContent=countdown(dashboard.weekly.periodEnd);document.getElementById("dailyUses").textContent=`${dashboard.daily.entriesUsed} / 2 entries used`;document.getElementById("weeklyUses").textContent=`${dashboard.weekly.entriesUsed} / 1 selection used`;renderActive();renderCards("daily",dailyCards);renderCards("weekly",weeklyCards);historyList.innerHTML=dashboard.history.length?dashboard.history.map(e=>`<div class="history-row"><div><strong>${escapeHtml(e.difficulty)} ${escapeHtml(e.cadence)}</strong><small> · ${new Date(e.entered_at).toLocaleString()}</small></div><span class="badge">${escapeHtml(e.status)}</span></div>`).join(""):"<p>No previous operations.</p>";}
async function refresh(){const [player,result]=await Promise.all([loadCloudPlayerState(),loadExpeditionDashboard()]);if(result.error){notify.error("Expeditions unavailable",result.error.message);return;}money=Number(player?.money||0);dashboard=result.data;render();}
document.addEventListener("click",async event=>{const enter=event.target.closest("[data-enter]");if(enter){const[cadence,difficulty]=enter.dataset.enter.split(":"),rewardSelect=document.querySelector(`[data-reward-choice="${cadence}:${difficulty}"]`),rewardChoice=rewardSelect.value,rewardLabel=rewardSelect.selectedOptions[0].textContent;const fee=dashboard.fees[cadence][difficulty],choice=await confirmDialog({title:`Enter ${difficulty} expedition?`,body:`<p>This costs ${formatMoney(fee)}.</p><p><strong>Guaranteed reward:</strong> ${escapeHtml(rewardLabel)}</p><p>Generated quests are revealed after payment. Abandoning does not restore the entry.</p>`,confirmLabel:"Enter expedition"});if(choice!=="confirm")return;const result=await enterExpedition(cadence,difficulty,rewardChoice);if(result.error)notify.error("Entry failed",result.error.message);else{money=Number(result.data.money);notify.success("Expedition started","Your objectives have been revealed.");}await refresh();return;}const abandon=event.target.closest("[data-abandon]");if(abandon){const choice=await confirmDialog({title:"Abandon expedition?",body:"<p>Your fee, progress, and entry allowance will be permanently forfeited.</p>",confirmLabel:"Abandon"});if(choice!=="confirm")return;const result=await abandonExpedition(Number(abandon.dataset.abandon));if(result.error)notify.error("Could not abandon",result.error.message);await refresh();return;}const reroll=event.target.closest("[data-reroll]");if(reroll){const choice=await confirmDialog({title:"Reroll this quest?",body:"<p>All progress will be lost. The replacement starts at zero.</p>",confirmLabel:"Reroll quest"});if(choice!=="confirm")return;const result=await rerollExpeditionQuest(Number(reroll.dataset.reroll));if(result.error)notify.error("Reroll failed",result.error.message);else money=Number(result.data.money);await refresh();}});
setInterval(()=>dashboard&&render(),60000);
if(await ensurePlayerAuth())await refresh();
