-- =========================================================
-- Final Workbench + admin observability runtime repair
-- =========================================================

-- Keep the historical forge_* tables for data compatibility, but make
-- Workbench itself the only public feature identity.
alter table if exists public.forge_config
  add column if not exists display_name text not null default 'Workbench [BETA]',
  add column if not exists icon text not null default '⚒';

update public.forge_config
set enabled = true,
    display_name = coalesce(nullif(display_name, ''), nullif(beta_label, ''), 'Workbench [BETA]'),
    icon = coalesce(nullif(icon, ''), '⚒')
where id = true;

grant select, insert, update, delete on table public.forge_config to service_role;
grant select, insert, update, delete on table public.forge_sessions to service_role;
grant select, insert, update, delete on table public.forge_items to service_role;

insert into public.game_section_settings
  (id, label, short_label, icon, description, enabled, sort_order, admin_only)
values
  ('workbench', 'Workbench [BETA]', 'Workbench', '⚒',
   'Three-stage precision forging for weapons and armor.', true, 120, true)
on conflict (id) do update
set label = 'Workbench [BETA]',
    short_label = 'Workbench',
    icon = '⚒',
    enabled = true,
    admin_only = true,
    updated_at = now();

delete from public.game_section_settings where id = 'forge';

-- Audit storage must always be writable by the service-role admin function.
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id) on delete restrict,
  target_player_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log(created_at desc);

alter table public.admin_audit_log enable row level security;
revoke all on public.admin_audit_log from anon, authenticated;
grant select, insert on public.admin_audit_log to service_role;
grant usage, select on sequence public.admin_audit_log_id_seq to service_role;

-- Ensure the configured owner is recognized consistently by RPC analytics,
-- Edge Functions, and the Admin UI.
insert into public.admins(user_id, note)
select '38d5e8ce-18af-46d3-aa9e-6e601e75dd78', 'configured owner'
where exists (select 1 from auth.users where id = '38d5e8ce-18af-46d3-aa9e-6e601e75dd78')
on conflict (user_id) do nothing;

-- Analytics RPC: owner/admin access + defensive optional-table reads.
create or replace function public.get_admin_analytics()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_is_admin boolean := false;
  v_players bigint := 0;
  v_rolls numeric := 0;
  v_inventory bigint := 0;
  v_mutated bigint := 0;
  v_money numeric := 0;
  v_inventory_value numeric := 0;
  v_announcements bigint := 0;
  v_announcements_mutated bigint := 0;
  v_pending_boosts bigint := 0;
begin
  select exists (
    select 1 from public.admins where user_id = auth.uid()
  ) or auth.uid() = '38d5e8ce-18af-46d3-aa9e-6e601e75dd78'::uuid
  into v_is_admin;

  if not v_is_admin then
    begin
      select exists (
        select 1 from public.code_improvement where user_id = auth.uid()
      ) into v_is_admin;
    exception when undefined_table then
      v_is_admin := false;
    end;
  end if;

  if not v_is_admin then
    raise exception 'not_authorized';
  end if;

  select count(*), coalesce(sum(total_rolls),0), coalesce(sum(money),0)
    into v_players, v_rolls, v_money
  from public.players;

  select count(*),
         coalesce(sum(value),0),
         count(*) filter (where coalesce(cardinality(mutation_ids),0) > 0)
    into v_inventory, v_inventory_value, v_mutated
  from public.inventory_gems;

  begin
    select count(*),
           count(*) filter (where coalesce(cardinality(mutation_ids),0) > 0)
      into v_announcements, v_announcements_mutated
    from public.global_chat_announcements;
  exception when undefined_table then
    v_announcements := 0;
    v_announcements_mutated := 0;
  end;

  begin
    select count(*) into v_pending_boosts
    from public.player_one_roll_boosts;
  exception when undefined_table then
    v_pending_boosts := 0;
  end;

  return jsonb_build_object(
    'players', v_players,
    'totalRolls', v_rolls,
    'totalInventoryGems', v_inventory,
    'mutatedGems', v_mutated,
    'mutationRate', case when v_inventory > 0 then v_mutated::numeric / v_inventory else 0 end,
    'totalMoney', v_money,
    'totalInventoryValue', v_inventory_value,
    'rareAnnouncements', v_announcements,
    'announcementsWithMutations', v_announcements_mutated,
    'emptyAnnouncementMutations', greatest(0, v_announcements-v_announcements_mutated),
    'announcementMutationCoverage', case when v_announcements > 0 then v_announcements_mutated::numeric/v_announcements else 1 end,
    'pendingOneRollBoosts', v_pending_boosts,
    'generatedAt', now()
  );
end;
$$;

revoke all on function public.get_admin_analytics() from public;
grant execute on function public.get_admin_analytics() to authenticated;
