-- =========================================================
-- Analytics presence + dynamic mutations + guild reliability
-- =========================================================

create table if not exists public.player_presence (
  player_id uuid primary key references public.players(id) on delete cascade,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  total_sessions bigint not null default 0
);

create table if not exists public.player_presence_events (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  seen_at timestamptz not null default now()
);

create index if not exists player_presence_last_seen_idx
  on public.player_presence(last_seen_at desc);
create index if not exists player_presence_events_seen_at_idx
  on public.player_presence_events(seen_at desc);
create index if not exists player_presence_events_player_seen_idx
  on public.player_presence_events(player_id, seen_at desc);

alter table public.player_presence enable row level security;
alter table public.player_presence_events enable row level security;
revoke all on public.player_presence, public.player_presence_events from anon, authenticated;
grant select, insert, update on public.player_presence, public.player_presence_events to service_role;
grant usage, select on sequence public.player_presence_events_id_seq to service_role;

create or replace function public.record_player_presence()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_now timestamptz := now();
  v_first timestamptz;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  insert into public.player_presence(player_id, first_seen_at, last_seen_at, total_sessions)
  values(v_uid, v_now, v_now, 1)
  on conflict(player_id) do update
    set last_seen_at = excluded.last_seen_at;

  select first_seen_at into v_first
  from public.player_presence
  where player_id = v_uid;

  insert into public.player_presence_events(player_id, seen_at)
  values(v_uid, v_now);

  -- Keep the heartbeat table bounded without running a large delete on every
  -- one-minute heartbeat. The modulo check simply spreads cleanup across
  -- ordinary player traffic.
  if mod(extract(epoch from v_now)::bigint, 97) = 0 then
    delete from public.player_presence_events
    where seen_at < v_now - interval '45 days';
  end if;

  return jsonb_build_object(
    'ok', true,
    'firstSeenAt', v_first,
    'lastSeenAt', v_now
  );
end;
$$;

revoke all on function public.record_player_presence() from public;
grant execute on function public.record_player_presence() to authenticated;

create table if not exists public.game_mutations (
  id text primary key,
  name text not null,
  chance numeric not null check (chance > 0),
  multiplier numeric not null check (multiplier > 0),
  description text not null default '',
  icon text not null default '✦',
  color text not null default '#9fdcff',
  enabled boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.game_mutations enable row level security;
revoke all on public.game_mutations from anon, authenticated;
grant select on public.game_mutations to anon, authenticated;
grant all on public.game_mutations to service_role;

insert into public.game_mutations(id,name,chance,multiplier,description,icon,color,sort_order)
values
 ('polished','Polished',100,1.5,'A clean reflective finish.','✦','#b8d7ff',10),
 ('gilded','Gilded',500,2.5,'Fine golden veins run across the specimen.','◆','#ffd66b',20),
 ('prismatic','Prismatic',2500,5,'The surface shifts through a spectrum of colour.','✧','#d9a7ff',30),
 ('celestial','Celestial',10000,12,'A cold light seems to come from beyond the sky.','☼','#9ee8ff',40),
 ('corrupted','Corrupted',50000,30,'Unstable energy twists the specimen.','☠','#ff718f',50)
on conflict(id) do nothing;

-- The owner can use the existing admins table without requiring a redeploy.
insert into public.admins(user_id, note)
select '38d5e8ce-18af-46d3-aa9e-6e601e75dd78', 'configured owner'
where exists (select 1 from auth.users where id = '38d5e8ce-18af-46d3-aa9e-6e601e75dd78')
on conflict (user_id) do nothing;

-- Make the previously shipped Roll-page utilities available again.
insert into public.game_section_settings(id,label,short_label,icon,description,enabled,sort_order)
values
 ('session-insights','Session Insights','Sessions','▤','Detailed statistics and highlights for the current browser session.',true,91),
 ('auto-keep','Auto Keep','Auto Keep','◆','Protects exceptional rolls before Auto Sell.',true,92)
on conflict(id) do update
set enabled = true, updated_at = now();

-- Defensive guild creation RPC. The Edge Function also has a fallback for
-- deployments that have not yet applied the earlier guild migration.
create or replace function public.create_guild_for_player(p_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_name text := btrim(left(coalesce(p_name,''),50));
  v_guild public.guilds%rowtype;
begin
  if v_uid is null then raise exception 'not_authenticated'; end if;
  if length(v_name) < 2 then raise exception 'invalid_name'; end if;
  if exists(select 1 from public.guild_members where player_id=v_uid) then raise exception 'already_in_guild'; end if;

  insert into public.guilds(name,owner_id)
  values(v_name,v_uid)
  returning * into v_guild;

  insert into public.guild_members(guild_id,player_id,role)
  values(v_guild.id,v_uid,'owner');

  return jsonb_build_object('guild',to_jsonb(v_guild));
exception
  when unique_violation then raise exception 'guild_name_taken';
end;
$$;

revoke all on function public.create_guild_for_player(text) from public;
grant execute on function public.create_guild_for_player(text) to authenticated;

-- Extended analytics. It deliberately uses a short presence window so the
-- current-online number does not stay inflated by abandoned browser tabs.
create or replace function public.get_admin_analytics()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_is_admin boolean := false;
  v_players bigint := 0;
  v_rolls numeric := 0;
  v_inventory bigint := 0;
  v_mutated bigint := 0;
  v_money numeric := 0;
  v_inventory_value numeric := 0;
  v_online bigint := 0;
  v_daily bigint := 0;
  v_weekly bigint := 0;
  v_retained_1d numeric := 0;
  v_retained_7d numeric := 0;
  v_announcements bigint := 0;
  v_announcements_mutated bigint := 0;
  v_pending_boosts bigint := 0;
  v_hourly jsonb := '[]'::jsonb;
begin
  select exists(select 1 from public.admins where user_id=v_uid)
      or v_uid='38d5e8ce-18af-46d3-aa9e-6e601e75dd78'::uuid
    into v_is_admin;
  if not v_is_admin then raise exception 'not_authorized'; end if;

  select count(*), coalesce(sum(total_rolls),0), coalesce(sum(money),0)
    into v_players,v_rolls,v_money from public.players;

  select count(*),coalesce(sum(value),0),
         count(*) filter(where coalesce(cardinality(mutation_ids),0)>0)
    into v_inventory,v_inventory_value,v_mutated from public.inventory_gems;

  select count(*) into v_online
    from public.player_presence
    where last_seen_at >= now()-interval '90 seconds';

  select count(distinct player_id) into v_daily
    from public.player_presence_events
    where seen_at >= now()-interval '24 hours';

  select count(distinct player_id) into v_weekly
    from public.player_presence_events
    where seen_at >= now()-interval '7 days';

  -- D1/D7 retention: among players old enough to be eligible, count those
  -- who were seen again during the corresponding retention window.
  select case when count(*)=0 then 0 else 100.0 * count(*) filter(where exists(
      select 1 from public.player_presence_events e
      where e.player_id=p.player_id
        and e.seen_at between p.first_seen_at + interval '1 day'
                           and p.first_seen_at + interval '2 days'
    ))::numeric / count(*) end
    into v_retained_1d
  from public.player_presence p
  where p.first_seen_at <= now()-interval '2 days';

  select case when count(*)=0 then 0 else 100.0 * count(*) filter(where exists(
      select 1 from public.player_presence_events e
      where e.player_id=p.player_id
        and e.seen_at between p.first_seen_at + interval '7 days'
                           and p.first_seen_at + interval '8 days'
    ))::numeric / count(*) end
    into v_retained_7d
  from public.player_presence p
  where p.first_seen_at <= now()-interval '8 days';

  begin
    select count(*),count(*) filter(where coalesce(cardinality(mutation_ids),0)>0)
      into v_announcements,v_announcements_mutated
    from public.global_chat_announcements;
  exception when undefined_table then null; end;

  begin
    select count(*) into v_pending_boosts from public.player_one_roll_boosts;
  exception when undefined_table then null; end;

  select coalesce(jsonb_agg(jsonb_build_object('hour',bucket,'users',users) order by bucket),'[]'::jsonb)
    into v_hourly
  from (
    select date_trunc('hour', now()-((g.i)::text||' hours')::interval) as bucket,
           count(distinct e.player_id) as users
    from generate_series(0,23) g(i)
    left join public.player_presence_events e
      on e.seen_at >= date_trunc('hour',now()-((g.i)::text||' hours')::interval)
     and e.seen_at <  date_trunc('hour',now()-((g.i-1)::text||' hours')::interval)
    group by bucket
  ) h;

  return jsonb_build_object(
    'players',v_players,'totalRolls',v_rolls,'totalInventoryGems',v_inventory,
    'mutatedGems',v_mutated,'mutationRate',case when v_inventory>0 then v_mutated::numeric/v_inventory else 0 end,
    'totalMoney',v_money,'totalInventoryValue',v_inventory_value,
    'currentOnline',v_online,'dailyOnline',v_daily,'weeklyOnline',v_weekly,
    'retention1d',v_retained_1d,'retention7d',v_retained_7d,
    'hourlyOnline',v_hourly,'rareAnnouncements',v_announcements,
    'announcementsWithMutations',v_announcements_mutated,
    'emptyAnnouncementMutations',greatest(0,v_announcements-v_announcements_mutated),
    'announcementMutationCoverage',case when v_announcements>0 then v_announcements_mutated::numeric/v_announcements else 1 end,
    'pendingOneRollBoosts',v_pending_boosts,'generatedAt',now()
  );
end;
$$;

revoke all on function public.get_admin_analytics() from public;
grant execute on function public.get_admin_analytics() to authenticated;

-- Rare-roll chat messages also preserve the exact effective luck multiplier.
alter table if exists public.global_chat_announcements
  add column if not exists luck_at_roll numeric;

create or replace function public.attach_roll_announcement_mutations(
  p_player_id uuid,
  p_gem_name text,
  p_gem_rarity numeric,
  p_mutation_ids text[] default '{}',
  p_luck_at_roll numeric default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  select a.id into v_id
  from public.global_chat_announcements a
  where a.player_id = p_player_id
    and a.gem_name = p_gem_name
    and a.rarity = p_gem_rarity
    and coalesce(cardinality(a.mutation_ids),0)=0
  order by a.created_at desc,a.id desc
  limit 1
  for update;

  if v_id is null then return null; end if;

  update public.global_chat_announcements
  set mutation_ids = coalesce(p_mutation_ids,'{}'::text[]),
      luck_at_roll = coalesce(p_luck_at_roll, luck_at_roll)
  where id=v_id;

  return v_id;
end;
$$;

revoke all on function public.attach_roll_announcement_mutations(uuid,text,numeric,text[],numeric) from public;
grant execute on function public.attach_roll_announcement_mutations(uuid,text,numeric,text[],numeric) to service_role;

-- Live admin-created gems must be readable by the Gem Index once enabled.
-- Disabled/temporary definitions remain hidden by the policy.
create table if not exists public.private_feature_gems (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  rarity numeric not null default 1,
  base_weight numeric not null default 1,
  value_per_gram numeric not null default 0,
  description text not null default '',
  hide_rarity_until_discovered boolean not null default false,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.private_feature_gems enable row level security;
drop policy if exists private_feature_gems_enabled_catalog_read on public.private_feature_gems;
create policy private_feature_gems_enabled_catalog_read
  on public.private_feature_gems
  for select to anon, authenticated
  using (
    enabled = true
    and (starts_at is null or starts_at <= now())
    and (ends_at is null or ends_at > now())
  );
grant select on public.private_feature_gems to anon, authenticated;
grant all on public.private_feature_gems to service_role;
