-- Crystal Caverns V1: a server-authoritative expedition destination.

create table public.crystal_cavern_runs(
  id bigint generated always as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  status text not null default 'awaiting_funding',depth integer not null default 0,overdepth integer not null default 0,
  progress integer not null default 0,target integer not null default 0,danger integer not null default 0,
  instability integer not null default 0,total_funding numeric not null default 0,
  secured_cargo jsonb not null default '[]',unsecured_cargo jsonb not null default '[]',
  secured_artifacts jsonb not null default '[]',unsecured_artifacts jsonb not null default '[]',
  pending jsonb,incident_log jsonb not null default '[]',extraction_reason text,settlement jsonb,
  started_at timestamptz not null default now(),updated_at timestamptz not null default now(),settled_at timestamptz,
  constraint crystal_status check(status in('awaiting_funding','active','decision','ready_to_extract','forced_extraction','extracted','settled')),
  constraint crystal_depth check(depth between 0 and 10),constraint crystal_instability check(instability>=0)
);
create unique index crystal_one_open_run on public.crystal_cavern_runs(player_id) where status<>'settled';
alter table public.crystal_cavern_runs enable row level security;
revoke all on public.crystal_cavern_runs from public,anon,authenticated;grant all on public.crystal_cavern_runs to service_role;

create table public.crystal_cavern_artifacts(
  key text primary key,name text not null,collection text not null,min_depth integer not null default 1,min_overdepth integer not null default 0,
  min_instability integer not null default 0,pool text not null,weight numeric not null default 1,duplicate_value numeric not null,
  passive_name text not null,passive_description text not null,sort_order integer not null unique
);
insert into public.crystal_cavern_artifacts values
('crystal-splinter','Crystal Splinter','normal',1,0,0,'general',10,125000,'Crystal Luck','+0.02× additive Luck',10),
('calcified-geode','Calcified Geode','normal',2,0,0,'general',9,175000,'Dense Formation','+2% Weight Luck',20),
('quartz-cluster','Quartz Cluster','normal',3,0,0,'general',8,250000,'Crystal Precision','+2% Weight Multiplier',30),
('broken-survey-lens','Broken Survey Lens','normal',5,0,0,'general',7,400000,'Survey Analysis','+2% relative Expedition artifact discovery',40),
('crystallized-lantern','Crystallized Lantern','normal',6,0,0,'general',6,600000,'Crystal Illumination','+2% normal gem sale value',50),
('ancient-crystal-chisel','Ancient Crystal Chisel','normal',8,0,0,'general',5,850000,'Fine Extraction','+3% Weight Multiplier',60),
('prismatic-shard','Prismatic Shard','normal',1,0,15,'formation',8,750000,'Prismatic Fortune','×1.02 Mutation Chance',70),
('fractured-prism','Fractured Prism','normal',1,0,30,'formation',7,1100000,'Fractured Luck','+0.03× additive Luck',80),
('resonance-core','Resonance Core','normal',1,0,45,'formation',6,1500000,'Resonance','+3% Expedition bonus-progress sources',90),
('unstable-crystal-heart','Unstable Crystal Heart','normal',1,0,60,'formation',5,2000000,'Unstable Fortune','+3% final gem value',100),
('perfect-crystal-sphere','Perfect Crystal Sphere','normal',10,0,0,'d10-sphere',1,1500000,'Perfect Form','+3% Weight Luck',110),
('heart-of-the-cavern','Heart of the Cavern','normal',10,0,0,'d10-heart',1,3000000,'Crystal Heart','×1.02 Mutation Chance',120),
('frozen-light-fragment','Frozen Light Fragment','overdepth',10,1,0,'od',10,2000000,'Frozen Light','+3% normal gem sale value',200),
('prismatic-fossil','Prismatic Fossil','overdepth',10,2,0,'od',9,3000000,'Ancient Refraction','+3% relative Expedition artifact discovery',210),
('resonant-geode','Resonant Geode','overdepth',10,4,0,'od',8,4500000,'Deep Resonance','+4% Expedition bonus-progress sources',220),
('fractured-core','Fractured Core','overdepth',10,6,0,'od',7,7000000,'Core Compression','×1.03 Mutation Chance',230),
('impossible-crystal','Impossible Crystal','overdepth',10,3,100,'od',6,10000000,'Impossible Geometry','+4% final Weight Multiplier',240),
('shattered-heart','Shattered Heart','overdepth',10,8,150,'od',6,15000000,'Critical Mass','Gems rolled at 2.00× weight or higher gain +5% final value',250);
alter table public.crystal_cavern_artifacts enable row level security;
create policy crystal_artifacts_read on public.crystal_cavern_artifacts for select to authenticated using(true);

create or replace function public.crystal_funding(p_depth integer,p_od integer default 0) returns numeric language plpgsql immutable set search_path='' as $$
declare n numeric;lvl integer;begin
 if p_od=0 then if p_depth not between 1 and 10 then raise exception 'invalid_crystal_depth';end if;return(array[200000,300000,450000,650000,900000,1300000,2000000,3000000,4500000,7000000]::numeric[])[p_depth];end if;
 if p_od<=10 then return(array[12000000,18000000,26000000,38000000,54000000,76000000,108000000,152000000,214000000,300000000]::numeric[])[p_od];end if;
 n:=300000000;for lvl in 11..p_od loop n:=floor((n*1.4+500000)/1000000)*1000000;end loop;return n;end $$;
create or replace function public.crystal_base_danger(p_depth integer,p_od integer default 0) returns integer language sql immutable set search_path='' as $$
 select case when p_od=0 then(array[0,3,7,12,18,26,35,45,57,70]::integer[])[p_depth]
 when p_od<=9 then(array[75,79,83,87,90,93,95,96,97]::integer[])[p_od] else 98 end $$;
create or replace function public.crystal_artifact_multiplier(p_i integer) returns numeric language sql immutable set search_path='' as $$select 3-2*exp(-greatest(0,p_i)::numeric/125)$$;
create or replace function public.crystal_artifact_chance(p_base numeric,p_i integer) returns numeric language sql immutable set search_path='' as $$select least(1,p_base*public.crystal_artifact_multiplier(p_i))$$;
create or replace function public.crystal_severity(p_i integer,p_roll numeric default random()) returns text language plpgsql volatile set search_path='' as $$
declare mi numeric:=.65*exp(-power(greatest(0,p_i)::numeric/145,1.406));cr numeric:=.08+.92*(1-exp(-power(greatest(0,p_i)::numeric/320,1.767)));begin
 return case when p_roll<mi then 'minor' when p_roll<1-cr then 'major' else 'critical' end;end $$;
create or replace function public.crystal_od_cargo_range(p_od integer) returns numeric[] language plpgsql immutable set search_path='' as $$
declare lo numeric;hi numeric;lvl integer;begin if p_od<=10 then lo:=(array[5000000,7000000,10000000,14000000,19000000,26000000,35000000,47000000,63000000,84000000]::numeric[])[p_od];hi:=(array[7000000,10000000,14000000,19000000,26000000,35000000,47000000,63000000,84000000,112000000]::numeric[])[p_od];else lo:=84000000;hi:=112000000;for lvl in 11..p_od loop lo:=round(lo*1.33);hi:=round(hi*1.33);end loop;end if;return array[lo,hi];end $$;
create or replace function public.crystal_cargo(p_depth integer,p_od integer default 0) returns jsonb language plpgsql volatile set search_path='' as $$
declare lo numeric;hi numeric;b numeric[];begin if p_od>0 then b:=public.crystal_od_cargo_range(p_od);lo:=b[1];hi:=b[2];else lo:=(array[30000,50000,75000,125000,175000,300000,500000,800000,1100000,2500000]::numeric[])[p_depth];hi:=(array[60000,90000,125000,200000,300000,500000,800000,1200000,1700000,3500000]::numeric[])[p_depth];end if;return jsonb_build_object('kind','cargo','name','Crystal cargo','value',round(lo+random()*(hi-lo)),'depth',p_depth,'overdepth',p_od);end $$;

create or replace function public.crystal_player_effects(p_uid uuid) returns jsonb language sql stable security definer set search_path='' as $$
with owned as(select artifact_key k from public.museum_artifact_registrations where player_id=p_uid)
select jsonb_build_object('luckBonus',(case when exists(select 1 from owned where k='crystal-splinter')then .02 else 0 end)+(case when exists(select 1 from owned where k='fractured-prism')then .03 else 0 end),
'weightLuckMultiplier',(case when exists(select 1 from owned where k='calcified-geode')then 1.02 else 1 end)*(case when exists(select 1 from owned where k='perfect-crystal-sphere')then 1.03 else 1 end),
'weightMultiplierMultiplier',(case when exists(select 1 from owned where k='quartz-cluster')then 1.02 else 1 end)*(case when exists(select 1 from owned where k='ancient-crystal-chisel')then 1.03 else 1 end)*(case when exists(select 1 from owned where k='impossible-crystal')then 1.04 else 1 end),
'artifactChanceMultiplier',(case when exists(select 1 from owned where k='broken-survey-lens')then 1.02 else 1 end)*(case when exists(select 1 from owned where k='prismatic-fossil')then 1.03 else 1 end),
'gemValueMultiplier',(case when exists(select 1 from owned where k='crystallized-lantern')then 1.02 else 1 end)*(case when exists(select 1 from owned where k='unstable-crystal-heart')then 1.03 else 1 end)*(case when exists(select 1 from owned where k='frozen-light-fragment')then 1.03 else 1 end),
'mutationChanceMultiplier',(case when exists(select 1 from owned where k='prismatic-shard')then 1.02 else 1 end)*(case when exists(select 1 from owned where k='heart-of-the-cavern')then 1.02 else 1 end)*(case when exists(select 1 from owned where k='fractured-core')then 1.03 else 1 end),
'bonusProgressMultiplier',(case when exists(select 1 from owned where k='resonance-core')then 1.03 else 1 end)*(case when exists(select 1 from owned where k='resonant-geode')then 1.04 else 1 end),
'heavyGemValueMultiplier',case when exists(select 1 from owned where k='shattered-heart')then 1.05 else 1 end)$$;
revoke all on function public.crystal_player_effects(uuid) from public,anon,authenticated;grant execute on function public.crystal_player_effects(uuid) to service_role;

create or replace function public.crystal_roll_artifact(p_run public.crystal_cavern_runs,p_pool text,p_quality boolean default false) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare a public.crystal_cavern_artifacts;begin select * into a from public.crystal_cavern_artifacts where pool=p_pool and p_run.depth>=min_depth and p_run.overdepth>=min_overdepth and p_run.instability>=min_instability order by -ln(greatest(random(),.000000001))/(weight*case when p_quality then greatest(1,sort_order/50.0)else 1 end)limit 1;if not found then return null;end if;return jsonb_build_object('kind','artifact','key',a.key,'name',a.name,'duplicateValue',a.duplicate_value,'depth',p_run.depth,'overdepth',p_run.overdepth,'instability',p_run.instability);end $$;
create or replace function public.crystal_add_opportunities(p_run public.crystal_cavern_runs,p_pool text,p_count integer,p_base numeric,p_quality boolean default false) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare out jsonb:=p_run.unsecured_artifacts;a jsonb;i integer;bonus numeric:=coalesce((public.crystal_player_effects(p_run.player_id)->>'artifactChanceMultiplier')::numeric,1);begin for i in 1..p_count loop if random()<least(1,public.crystal_artifact_chance(p_base,p_run.instability)*bonus)then a:=public.crystal_roll_artifact(p_run,p_pool,p_quality);if a is not null then out:=out||jsonb_build_array(a);end if;end if;end loop;return out;end $$;

create or replace function public.start_crystal_caverns() returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.crystal_cavern_runs;begin if auth.uid()is null then raise exception'not_authenticated';end if;if exists(select 1 from public.crystal_cavern_runs where player_id=auth.uid()and status<>'settled')then raise exception'crystal_run_already_open';end if;insert into public.crystal_cavern_runs(player_id)values(auth.uid())returning*into r;return to_jsonb(r);end $$;
create or replace function public.fund_crystal_depth(p_run_id bigint,p_depth integer) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.crystal_cavern_runs;c numeric;m numeric;begin select*into r from public.crystal_cavern_runs where id=p_run_id and player_id=auth.uid()for update;if not found or r.overdepth<>0 or r.status<>'awaiting_funding'or p_depth<>r.depth+1 then raise exception'crystal_depth_unavailable';end if;c:=public.crystal_funding(p_depth);update public.players p set money=p.money-c where id=r.player_id and p.money>=c returning p.money into m;if not found then raise exception'insufficient_funds';end if;update public.crystal_cavern_runs set depth=p_depth,progress=0,target=100+p_depth*50,danger=public.crystal_base_danger(p_depth),status='active',total_funding=total_funding+c,updated_at=now()where id=r.id returning*into r;return jsonb_build_object('run',to_jsonb(r),'money',m,'cost',c);end $$;

create or replace function public.crystal_apply_incident(p_run public.crystal_cavern_runs)returns public.crystal_cavern_runs language plpgsql volatile security definer set search_path='' as $$
declare sev text;loss numeric;kept jsonb;begin if random()>=p_run.danger/100.0 then return p_run;end if;sev:=public.crystal_severity(p_run.instability);loss:=case sev when'minor'then .05+random()*.05 when'major'then .15+random()*.10 else .30+random()*.15 end;select coalesce(jsonb_agg(jsonb_set(value,'{value}',to_jsonb(round(coalesce((value->>'value')::numeric,0)*(1-loss))))),'[]')into kept from jsonb_array_elements(p_run.unsecured_cargo)value;p_run.unsecured_cargo:=kept;p_run.incident_log:=p_run.incident_log||jsonb_build_array(jsonb_build_object('severity',sev,'lossFraction',loss,'instability',p_run.instability,'at',now()));if sev='major'then p_run.instability:=p_run.instability+3;elsif sev='critical'then p_run.status:='forced_extraction';p_run.extraction_reason:='critical_incident';p_run.unsecured_artifacts:='[]';end if;return p_run;end $$;

create or replace function public.record_crystal_cavern_roll(p_player_id uuid,p_payload jsonb)returns void language plpgsql security definer set search_path='' as $$
declare r public.crystal_cavern_runs;inc integer:=1;bonus integer:=0;newp integer;base numeric;auto_i integer;pending jsonb:=null;begin select*into r from public.crystal_cavern_runs where player_id=p_player_id and status='active'for update;if not found then return;end if;if coalesce((p_payload->>'rarity')::numeric,0)>=1000 then bonus:=bonus+3;end if;if jsonb_array_length(coalesce(p_payload->'mutationIds','[]'))>0 then bonus:=bonus+3;end if;if coalesce((p_payload->>'weightMultiplier')::numeric,0)>=2 then bonus:=bonus+3;end if;inc:=inc+floor(bonus*coalesce((public.crystal_player_effects(p_player_id)->>'bonusProgressMultiplier')::numeric,1)+random())::integer;newp:=least(r.target,r.progress+inc);if r.progress<r.target and newp>=r.target then
 r:=public.crystal_apply_incident(r);
 if r.status<>'forced_extraction'then r.unsecured_cargo:=r.unsecured_cargo||jsonb_build_array(public.crystal_cargo(r.depth,r.overdepth));if r.overdepth>0 then auto_i:=case when r.overdepth<=3 then 8 when r.overdepth<=6 then 10 else 12 end;r.instability:=r.instability+auto_i;base:=least(.40,.20+(r.overdepth-1)*.03);r.unsecured_artifacts:=public.crystal_add_opportunities(r,'od',1,base,false);if random()<.35 then pending:=jsonb_build_object('type','od_formation');else r.status:='ready_to_extract';end if;else base:=case when r.depth<=3 then .15 when r.depth<=6 then .20 when r.depth<=9 then .25 else .40 end;r.unsecured_artifacts:=public.crystal_add_opportunities(r,'general',1,base,false);if r.depth=10 then if random()<public.crystal_artifact_chance(.20,r.instability)then r.unsecured_artifacts:=r.unsecured_artifacts||jsonb_build_array(public.crystal_roll_artifact(r,'d10-sphere'));end if;if random()<public.crystal_artifact_chance(1.0/9,r.instability)then r.unsecured_artifacts:=r.unsecured_artifacts||jsonb_build_array(public.crystal_roll_artifact(r,'d10-heart'));end if;pending:=jsonb_build_object('type','d10_choice');elsif r.depth in(4,7,9)then pending:=jsonb_build_object('type','formation','depth',r.depth);elsif r.depth in(3,6)then pending:=jsonb_build_object('type','outpost','depth',r.depth);elsif r.depth in(2,5,8)and random()<.5 then pending:=jsonb_build_object('type','minor_event','event',(array['pocket','resonance','deposit'])[1+floor(random()*3)::integer]);else r.status:='awaiting_funding';end if;end if;if pending is not null then r.status:='decision';r.pending:=pending;end if;end if;
 end if;update public.crystal_cavern_runs set progress=newp,status=r.status,instability=r.instability,unsecured_cargo=r.unsecured_cargo,unsecured_artifacts=r.unsecured_artifacts,pending=r.pending,incident_log=r.incident_log,extraction_reason=r.extraction_reason,updated_at=now()where id=r.id;end $$;

create or replace function public.resolve_crystal_decision(p_run_id bigint,p_choice text)returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.crystal_cavern_runs;t text;e text;c numeric:=0;di integer:=0;count_ integer:=0;quality boolean:=false;pool text:='formation';m numeric:=null;nextp jsonb:=null;begin select*into r from public.crystal_cavern_runs where id=p_run_id and player_id=auth.uid()for update;if not found or r.status<>'decision'then raise exception'crystal_decision_unavailable';end if;t:=r.pending->>'type';
 if t='minor_event'then e:=r.pending->>'event';if p_choice='leave'then null;elsif e='pocket'and p_choice='excavate'then di:=5;count_:=1;pool:='general';elsif e='resonance'and p_choice='trigger'then di:=8;count_:=1;quality:=true;elsif e='deposit'and p_choice='break'then di:=3;r.unsecured_cargo:=r.unsecured_cargo||jsonb_build_array(public.crystal_cargo(r.depth,0));else raise exception'invalid_crystal_choice';end if;r.status:='awaiting_funding';
 elsif t in('formation','od_formation')then if p_choice='leave'then null;elsif t='od_formation'and p_choice='careful'then c:=public.crystal_funding(10,r.overdepth)*.20;di:=8;count_:=2;quality:=true;pool:='od';elsif t='od_formation'and p_choice='shatter'then di:=25;count_:=4;pool:='od';elsif t='formation'and p_choice='careful'then c:=case r.depth when 4 then 750000 when 7 then 2000000 else 4500000 end;di:=case r.depth when 4 then 4 when 7 then 6 else 8 end;count_:=case when r.depth=9 then 2 else 1 end;quality:=true;elsif t='formation'and p_choice='shatter'then di:=case r.depth when 4 then 12 when 7 then 18 else 25 end;count_:=case r.depth when 4 then 2 when 7 then 3 else 4 end;else raise exception'invalid_crystal_choice';end if;if t='od_formation'then r.status:='ready_to_extract';elsif r.depth=9 then nextp:=jsonb_build_object('type','outpost','depth',9);r.status:='decision';else r.status:='awaiting_funding';end if;
 elsif t='outpost'then if p_choice not in('secure','reinforce')then raise exception'invalid_crystal_choice';end if;c:=case r.depth when 3 then case p_choice when'secure'then 250000 else 500000 end when 6 then case p_choice when'secure'then 1000000 else 1750000 end else case p_choice when'secure'then 3500000 else 5500000 end end;if p_choice='reinforce'then r.danger:=greatest(0,r.danger-15);end if;r.secured_cargo:=r.secured_cargo||r.unsecured_cargo;r.unsecured_cargo:='[]';r.secured_artifacts:=r.secured_artifacts||r.unsecured_artifacts;r.unsecured_artifacts:='[]';r.status:='awaiting_funding';
 elsif t='d10_choice'then if p_choice='extract'then r.status:='ready_to_extract';elsif p_choice='fracture'then r.instability:=r.instability+30;r.status:='ready_to_extract';nextp:=jsonb_build_object('fractured',true);else raise exception'invalid_crystal_choice';end if;else raise exception'invalid_crystal_choice';end if;
 if c>0 then update public.players p set money=p.money-c where id=r.player_id and p.money>=c returning p.money into m;if not found then raise exception'insufficient_funds';end if;r.total_funding:=r.total_funding+c;end if;r.instability:=r.instability+di;if count_>0 then r.unsecured_artifacts:=public.crystal_add_opportunities(r,pool,count_,case when r.overdepth>0 then least(.40,.20+(r.overdepth-1)*.03)else case when r.depth<=6 then .20 else .25 end end,quality);end if;r.pending:=nextp;update public.crystal_cavern_runs set(status,instability,danger,secured_cargo,unsecured_cargo,secured_artifacts,unsecured_artifacts,pending,total_funding,updated_at)=(r.status,r.instability,r.danger,r.secured_cargo,r.unsecured_cargo,r.secured_artifacts,r.unsecured_artifacts,r.pending,r.total_funding,now())where id=r.id returning*into r;return jsonb_build_object('run',to_jsonb(r),'money',m,'cost',c);end $$;

create or replace function public.continue_crystal_overdepth(p_run_id bigint)returns jsonb language plpgsql security definer set search_path='' as $$declare r public.crystal_cavern_runs;n integer;c numeric;m numeric;begin select*into r from public.crystal_cavern_runs where id=p_run_id and player_id=auth.uid()for update;if not found or r.status<>'ready_to_extract'or r.depth<>10 or not(coalesce((r.pending->>'fractured')::boolean,false)or r.overdepth>0)then raise exception'crystal_overdepth_unavailable';end if;n:=r.overdepth+1;c:=public.crystal_funding(10,n);update public.players p set money=p.money-c where id=r.player_id and p.money>=c returning p.money into m;if not found then raise exception'insufficient_funds';end if;update public.crystal_cavern_runs set overdepth=n,progress=0,target=600+n*50,danger=public.crystal_base_danger(10,n),status='active',pending=null,total_funding=total_funding+c,updated_at=now()where id=r.id returning*into r;return jsonb_build_object('run',to_jsonb(r),'money',m,'cost',c);end $$;
create or replace function public.extract_crystal_caverns(p_run_id bigint)returns jsonb language plpgsql security definer set search_path='' as $$declare r public.crystal_cavern_runs;begin select*into r from public.crystal_cavern_runs where id=p_run_id and player_id=auth.uid()for update;if not found or r.status not in('ready_to_extract','forced_extraction')then raise exception'crystal_extraction_unavailable';end if;r.secured_cargo:=r.secured_cargo||r.unsecured_cargo;if r.status='forced_extraction'then r.unsecured_artifacts:='[]';else r.secured_artifacts:=r.secured_artifacts||r.unsecured_artifacts;end if;update public.crystal_cavern_runs set status='extracted',secured_cargo=r.secured_cargo,unsecured_cargo='[]',secured_artifacts=r.secured_artifacts,unsecured_artifacts='[]',extraction_reason=coalesce(extraction_reason,case when r.status='forced_extraction'then'critical_incident'else'voluntary'end),updated_at=now()where id=r.id returning*into r;return to_jsonb(r);end $$;
create or replace function public.settle_crystal_caverns(p_run_id bigint)returns jsonb language plpgsql security definer set search_path='' as $$declare r public.crystal_cavern_runs;x jsonb;cargo numeric:=0;dupes numeric:=0;registered jsonb:='[]';m numeric;begin select*into r from public.crystal_cavern_runs where id=p_run_id and player_id=auth.uid()for update;if not found or r.status<>'extracted'then raise exception'crystal_not_extracted';end if;for x in select value from jsonb_array_elements(r.secured_cargo)loop cargo:=cargo+coalesce((x->>'value')::numeric,0);end loop;for x in select value from jsonb_array_elements(r.secured_artifacts)loop insert into public.museum_artifact_registrations(player_id,artifact_key,artifact_name,depth_found,discovery_snapshot)values(r.player_id,x->>'key',x->>'name',r.depth,x)on conflict(player_id,artifact_key)do nothing;if found then registered:=registered||jsonb_build_array(x);else dupes:=dupes+coalesce((x->>'duplicateValue')::numeric,0);end if;end loop;update public.players p set money=p.money+cargo+dupes,lifetime_earnings=p.lifetime_earnings+cargo+dupes where id=r.player_id returning p.money into m;update public.crystal_cavern_runs set status='settled',settled_at=now(),settlement=jsonb_build_object('cargoValue',cargo,'duplicateValue',dupes,'registeredArtifacts',registered,'money',m),updated_at=now()where id=r.id returning*into r;return jsonb_build_object('run',to_jsonb(r),'money',m,'settlement',r.settlement);end $$;
create or replace function public.get_crystal_caverns_dashboard()returns jsonb language plpgsql security definer set search_path='' as $$declare r jsonb;a jsonb;m numeric;begin if auth.uid()is null then raise exception'not_authenticated';end if;select to_jsonb(x)into r from public.crystal_cavern_runs x where player_id=auth.uid()and status<>'settled'order by id desc limit 1;select p.money into m from public.players p where id=auth.uid();select coalesce(jsonb_agg(to_jsonb(x)order by x.sort_order),'[]')into a from(select c.*,exists(select 1 from public.museum_artifact_registrations z where z.player_id=auth.uid()and z.artifact_key=c.key)registered from public.crystal_cavern_artifacts c)x;return jsonb_build_object('destination',jsonb_build_object('id','crystal-caverns','name','Crystal Caverns','identity','How much will you disturb?'),'run',r,'money',m,'artifacts',a,'funding',to_jsonb(array[200000,300000,450000,650000,900000,1300000,2000000,3000000,4500000,7000000]),'danger',to_jsonb(array[0,3,7,12,18,26,35,45,57,70]));end $$;

-- Route committed rolls to the active destination without trusting the client.
create or replace function public.record_abandoned_mine_roll(p_player_id uuid,p_payload jsonb)returns void language plpgsql security definer set search_path='' as $$begin if exists(select 1 from public.crystal_cavern_runs where player_id=p_player_id and status='active')then perform public.record_crystal_cavern_roll(p_player_id,p_payload);elsif exists(select 1 from public.abandoned_mine_runs where player_id=p_player_id and mode='hell'and status<>'settled')then perform public.record_abandoned_mine_hell_roll(p_player_id,p_payload);else perform public.record_normal_abandoned_mine_roll(p_player_id,p_payload);end if;end $$;

revoke all on function public.start_crystal_caverns(),public.fund_crystal_depth(bigint,integer),public.resolve_crystal_decision(bigint,text),public.continue_crystal_overdepth(bigint),public.extract_crystal_caverns(bigint),public.settle_crystal_caverns(bigint),public.get_crystal_caverns_dashboard() from public,anon;
grant execute on function public.start_crystal_caverns(),public.fund_crystal_depth(bigint,integer),public.resolve_crystal_decision(bigint,text),public.continue_crystal_overdepth(bigint),public.extract_crystal_caverns(bigint),public.settle_crystal_caverns(bigint),public.get_crystal_caverns_dashboard() to authenticated;
revoke all on function public.record_crystal_cavern_roll(uuid,jsonb)from public,anon,authenticated;grant execute on function public.record_crystal_cavern_roll(uuid,jsonb)to service_role;
