-- Complete v0.13.0 Beta catalog: 138 visible + 18 hidden achievements.
create or replace function public.seed_achievement_series_v013(p_category text,p_names text[],p_aps integer[],p_hidden boolean default false)returns void language plpgsql security definer set search_path='' as $$declare i integer;n text;fid uuid;begin if cardinality(p_names)<>cardinality(p_aps)then raise exception 'achievement_series_mismatch:%',p_category;end if;for i in 1..cardinality(p_names)loop n:=p_names[i];fid:=md5('v013:'||p_category||':'||i)::uuid;insert into public.private_feature_definitions(id,feature_kind,name,description,icon,sort_order,enabled,requirements,rewards,metadata)values(fid,'achievement',n,'Complete this '||p_category||' milestone through genuine server-authoritative gameplay.','◆',(array_position(array['rolling','discovery','mutations','wealth','equipment','museum','social','special','hidden'],p_category)*1000)+i,true,case when p_category='rolling'then jsonb_build_object('type','rolls','amount',(array[1,100,500,1000,5000,10000,25000,50000,100000,250000,1000000])[i])else jsonb_build_object('type','single','match',jsonb_build_object('eventType','achievement:'||p_category||':'||i))end,'[]',jsonb_build_object('category',p_category,'ap',p_aps[i],'target',case when p_category='rolling'then(array[1,100,500,1000,5000,10000,25000,50000,100000,250000,1000000])[i]else 1 end,'hidden',p_hidden,'catalogVersion','v0.13.0-beta'))on conflict(id)do update set name=excluded.name,description=excluded.description,sort_order=excluded.sort_order,enabled=true,requirements=excluded.requirements,metadata=excluded.metadata,updated_at=now();end loop;end$$;
-- Preserve prototype progress while removing prototypes from the live catalog.
update public.private_feature_definitions set enabled=false,metadata=metadata||'{"legacyCatalog":true}'::jsonb,updated_at=now()where feature_kind='achievement'and coalesce(metadata->>'catalogVersion','')<>'v0.13.0-beta';
select public.seed_achievement_series_v013('rolling',string_to_array('First Spark|Getting Started|Finding Rhythm|Into the Mines|Seasoned Miner|Relentless|Deep Routine|Veteran Roller|Century Fortune|Endless Descent|Millionth Spark','|'),array[5,10,15,20,30,40,60,80,120,175,300]);
select public.seed_achievement_series_v013('discovery',string_to_array('A Legendary Find|Mythic Discovery|Exotic Discovery|Exalted Discovery|Cosmic Discovery|Transcendent Discovery|One in a Billion|Effective 100K|Effective Million|Effective Ten Million|Effective Hundred Million|Effective Billion|Effective Trillion|Index Apprentice|Index Explorer|Index Scholar|Index Expert|The Complete Index','|'),array[10,20,35,60,100,160,250,15,30,50,80,125,200,10,20,40,75,150]);
select public.seed_achievement_series_v013('mutations',string_to_array('First Mutation|Mutation Collector|Mutation Researcher|Mutation Hoarder|Mutation Archive|Double Mutation|Triple Mutation|Quadruple Mutation|The Mutated|Mutation Odds 1K|Mutation Odds 100K|Mutation Odds 10M|Mutation Odds 1B|Mutation Odds 1T|Five Mutation Types|Ten Mutation Types|Mutation Mastery','|'),array[10,15,25,45,75,20,45,90,175,15,35,75,140,225,20,50,125]);
select public.seed_achievement_series_v013('wealth',string_to_array('First Hundred Thousand|First Million|Ten Million Earned|Fifty Million Earned|Hundred Million Earned|Gem Magnate|Billionaire|Valuable Specimen|Premium Specimen|Million-Dollar Gem|Priceless|First Major Purchase|Committed Customer|Serious Patron|Patron|Golden Vault','|'),array[10,20,40,65,90,150,225,10,25,60,140,15,35,70,140,250]);
select public.seed_achievement_series_v013('equipment',string_to_array('First Equipment|Tier V Pickaxe|Tier X Pickaxe|Master Miner|Tier V Boots|Tier X Boots|Tier V Bag|Tier VIII Bag|Capable Loadout|Advanced Loadout|Fully Equipped|First Masterwork|Masterwork III|Masterwork V|Masterwork Artisan|First Enchantment|Ancient Enchantment|Enchant Collector|Arcane Mastery','|'),array[10,15,35,100,15,75,15,75,25,55,150,15,35,70,150,10,40,60,125]);
select public.seed_achievement_series_v013('museum',string_to_array('Opening Exhibit|Four Displays|Expanded Gallery|Grand Hall|Registered Specimen|Ten Registered|Fifty Registered|Museum Curator|Museum Archivist|First Collection|Four Collections|Master Curator|Prestige 250|Prestige 400|World-Class Curator|Museum Prestige 500|Museum Prestige 3500|Museum Prestige 12000|Prestige Gallery|Living Museum','|'),array[10,20,35,100,10,25,55,100,175,20,60,150,20,50,125,15,40,80,140,250]);
select public.seed_achievement_series_v013('social',string_to_array('Guild Member|Guild Founder|Guild Contributor|Guild Regular|Guild Stalwart|Competition Contributor|Guild Podium|Guild Champion|Three-Time Champion|First Market Trade|Market Regular|Market Veteran|Market Expert|Trusted Trader','|'),array[10,20,15,35,80,30,75,150,250,10,25,60,125,75]);
select public.seed_achievement_series_v013('special',string_to_array('First Expedition|Expedition Regular|Expedition Veteran|Depth Explorer|Voidwalker|Expedition Master|First Cache|Cache Collector|Guaranteed Reward|Cache Connoisseur|First Season Mission|Season Tier 10|Season Tier 25|Season Tier 50|Season Veteran|Right Time Right Gem|Early Serial|Single-Digit Serial|Original|Twenty-Five Achievements|Fifty Achievements|One Hundred Achievements|Gem Incremental','|'),array[10,30,75,40,75,150,10,30,40,100,10,25,50,125,75,20,30,100,250,40,75,150,300]);
select public.seed_achievement_series_v013('hidden',string_to_array('Déjà Vu|Perfect Copy|Against All Odds|Pure Fortune|Mutation Overflow|Heavyweight Champion|Pocket Mineral|Wrong Side Jackpot|Perfect Timing|Museum Piece|Difficult Choice|Two Birds|Milestone Cascade|From Nothing|Full Circle|Chosen One|Exactly as Planned|Secret Within Secret','|'),array[10,35,60,100,175,40,25,100,75,125,50,50,75,75,40,100,30,250],true);
do $$declare vc integer;hc integer;va integer;ta integer;begin select count(*)filter(where not coalesce((metadata->>'hidden')::boolean,false)),count(*)filter(where coalesce((metadata->>'hidden')::boolean,false)),sum((metadata->>'ap')::integer)filter(where not coalesce((metadata->>'hidden')::boolean,false)),sum((metadata->>'ap')::integer)into vc,hc,va,ta from public.private_feature_definitions where feature_kind='achievement'and metadata->>'catalogVersion'='v0.13.0-beta';if vc<>138 or hc<>18 or va<>10145 or ta<>11565 then raise exception 'achievement_catalog_validation_failed visible=% hidden=% visible_ap=% total_ap=%',vc,hc,va,ta;end if;end$$;
revoke all on function public.seed_achievement_series_v013(text,text[],integer[],boolean)from public,anon,authenticated;grant execute on function public.seed_achievement_series_v013(text,text[],integer[],boolean)to service_role;
