-- =========================================================
-- Daily Spin + PvP + Workbench customization + custom gem rarities
-- All new gameplay sections are disabled by default.
-- =========================================================

-- Shared section metadata now supports a custom symbol/short label.
alter table public.game_section_settings
  add column if not exists icon text not null default '◆',
  add column if not exists short_label text;

update public.game_section_settings
set short_label = coalesce(short_label, label)
where short_label is null;

-- Keep the previous Forge feature, but rename its default presentation to
-- Workbench. Existing custom labels are preserved.
update public.game_section_settings
set label = 'Workbench [BETA]',
    short_label = 'Workbench',
    icon = '⚒'
where id = 'forge'
  and label = 'The Forge [BETA]';

-- =========================================================
-- Daily Spin
-- =========================================================
create table if not exists public.daily_spin_config (
  id boolean primary key default true,
  enabled boolean not null default false,
  title text not null default 'Daily Spin',
  subtitle text not null default 'One free spin every day.',
  icon text not null default '◉',
  rewards jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.daily_spin_config(id, enabled, title, subtitle, icon, rewards)
values (
  true, false, 'Daily Spin', 'One free spin every day.', '◉',
  '[
    {"id":"coins-25","label":"25 Coins","chance":45,"reward":{"type":"coins","amount":25}},
    {"id":"money-5k","label":"$5,000","chance":30,"reward":{"type":"money","amount":5000}},
    {"id":"lucky-potion","label":"Lucky Potion ×1","chance":15,"reward":{"type":"potion","consumableId":"lucky-potion-1","amount":1}},
    {"id":"legendary-potion","label":"Legendary Potion ×1","chance":7,"reward":{"type":"potion","consumableId":"legendary-potion","amount":1}},
    {"id":"mythic-potion","label":"Mythic Potion ×1","chance":3,"reward":{"type":"potion","consumableId":"mythic-potion","amount":1}}
  ]'::jsonb
)
on conflict(id) do nothing;

create table if not exists public.daily_spin_claims (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  claim_date date not null,
  reward jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(player_id, claim_date)
);

alter table public.daily_spin_config enable row level security;
alter table public.daily_spin_claims enable row level security;
revoke all on public.daily_spin_config, public.daily_spin_claims from anon, authenticated;
grant select on public.daily_spin_config to service_role;
grant all on public.daily_spin_config, public.daily_spin_claims to service_role;

create index if not exists daily_spin_claims_player_idx
  on public.daily_spin_claims(player_id, claim_date desc);

create or replace function public.claim_daily_spin()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_cfg public.daily_spin_config%rowtype;
  v_item jsonb;
  v_reward jsonb;
  v_total numeric := 0;
  v_roll numeric;
  v_cursor numeric := 0;
  v_date date := current_date;
  v_money numeric;
  v_coins numeric;
  v_qty integer;
  v_reward_type text;
  v_consumable text;
  v_gem_name text;
  v_gem jsonb;
begin
  if v_uid is null then raise exception 'not_authenticated'; end if;

  select * into v_cfg from public.daily_spin_config where id = true for update;
  if not found or not v_cfg.enabled then raise exception 'feature_disabled'; end if;

  if exists (
    select 1 from public.daily_spin_claims
    where player_id = v_uid and claim_date = v_date
  ) then
    raise exception 'already_claimed';
  end if;

  if jsonb_typeof(v_cfg.rewards) <> 'array' or jsonb_array_length(v_cfg.rewards) = 0 then
    raise exception 'no_rewards_configured';
  end if;

  select coalesce(sum(greatest(0, coalesce((x->>'chance')::numeric,0))),0)
    into v_total
  from jsonb_array_elements(v_cfg.rewards) x;

  if v_total <= 0 then raise exception 'invalid_rewards'; end if;

  v_roll := random() * v_total;

  for v_item in select value from jsonb_array_elements(v_cfg.rewards)
  loop
    v_cursor := v_cursor + greatest(0, coalesce((v_item->>'chance')::numeric,0));
    if v_roll <= v_cursor then
      v_reward := coalesce(v_item->'reward', '{}'::jsonb) || jsonb_build_object(
        'id', coalesce(v_item->>'id',''),
        'label', coalesce(v_item->>'label','Reward')
      );
      exit;
    end if;
  end loop;

  if v_reward is null then
    v_reward := coalesce(v_cfg.rewards->-1->'reward','{}'::jsonb);
  end if;

  v_reward_type := v_reward->>'type';

  if v_reward_type = 'money' then
    v_money := greatest(0, coalesce((v_reward->>'amount')::numeric,0));
    update public.players
      set money = greatest(0, coalesce(money,0) + v_money),
          lifetime_earnings = greatest(0, coalesce(lifetime_earnings,0) + v_money)
      where id = v_uid;
  elsif v_reward_type = 'coins' then
    v_coins := greatest(0, coalesce((v_reward->>'amount')::numeric,0));
    update public.players
      set coins = greatest(0, coalesce(coins,0) + v_coins)
      where id = v_uid;
  elsif v_reward_type = 'potion' then
    v_consumable := v_reward->>'consumableId';
    v_qty := greatest(1, coalesce((v_reward->>'amount')::integer,1));
    if not exists(select 1 from public.game_consumables where id=v_consumable) then
      raise exception 'invalid_consumable';
    end if;
    insert into public.player_consumables(player_id,consumable_id,quantity,updated_at)
    values(v_uid,v_consumable,v_qty,now())
    on conflict(player_id,consumable_id) do update
      set quantity = public.player_consumables.quantity + excluded.quantity,
          updated_at = now();
  elsif v_reward_type = 'capacity' then
    update public.players
      set inventory_capacity = greatest(0, coalesce(inventory_capacity,0) + greatest(0,coalesce((v_reward->>'amount')::integer,0)))
      where id=v_uid;
  elsif v_reward_type = 'boost' then
    if (v_reward->>'family') not in ('luck','rollSpeed','weightLuck','weightMultiplier') then
      raise exception 'invalid_boost_family';
    end if;
    insert into public.player_boosts(player_id,family,tier,effect_value,expires_at,updated_at)
    values(
      v_uid,
      v_reward->>'family',
      3,
      greatest(0.0001,coalesce((v_reward->>'effectValue')::numeric,0)),
      now()+make_interval(secs=>greatest(1,coalesce((v_reward->>'seconds')::integer,300))),
      now()
    )
    on conflict(player_id,family) do update
      set tier=excluded.tier,effect_value=excluded.effect_value,expires_at=excluded.expires_at,updated_at=now();
  elsif v_reward_type = 'gem' then
    v_gem_name := v_reward->>'gemName';
    select to_jsonb(g) into v_gem
    from public.private_feature_gems g
    where g.name=v_gem_name and g.enabled=true
    order by g.rarity asc
    limit 1;
    if v_gem is null then raise exception 'invalid_gem_reward'; end if;
    insert into public.inventory_gems(
      player_id,gem_name,rarity,base_weight,value_per_gram,
      rolled_weight_multiplier,rolled_weight,final_weight,
      mutation_id,mutation_multiplier,mutation_ids,mutation_multipliers,
      value,locked,roll_number,luck_at_roll
    )
    values(
      v_uid,v_gem->>'name',(v_gem->>'rarity')::numeric,(v_gem->>'base_weight')::numeric,(v_gem->>'value_per_gram')::numeric,
      1,(v_gem->>'base_weight')::numeric,(v_gem->>'base_weight')::numeric,
      null,1,'{}'::text[],'{}'::jsonb,
      (v_gem->>'base_weight')::numeric*(v_gem->>'value_per_gram')::numeric,
      false,(select coalesce(total_rolls,0) from public.players where id=v_uid),1
    );
  end if;

  insert into public.daily_spin_claims(player_id,claim_date,reward)
  values(v_uid,v_date,v_reward);

  return jsonb_build_object('success',true,'claimDate',v_date,'reward',v_reward);
exception
  when unique_violation then
    raise exception 'already_claimed';
end;
$$;

grant execute on function public.claim_daily_spin() to authenticated;

-- =========================================================
-- PvP
-- =========================================================
create table if not exists public.pvp_weapon_definitions (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text not null default '',
  enabled boolean not null default true,
  rarity text not null default 'Common',
  base_damage numeric not null default 10,
  attacks jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pvp_matches (
  id uuid primary key default gen_random_uuid(),
  challenger_id uuid not null references public.players(id) on delete cascade,
  opponent_id uuid not null references public.players(id) on delete cascade,
  challenger_weapon_id uuid references public.pvp_weapon_definitions(id),
  opponent_weapon_id uuid references public.pvp_weapon_definitions(id),
  challenger_hp numeric not null default 100,
  opponent_hp numeric not null default 100,
  turn_player_id uuid not null references public.players(id) on delete cascade,
  status text not null default 'active' check(status in ('active','won','lost','draw','abandoned')),
  battle_log jsonb not null default '[]'::jsonb,
  winner_id uuid references public.players(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.pvp_weapon_definitions enable row level security;
alter table public.pvp_matches enable row level security;
revoke all on public.pvp_weapon_definitions, public.pvp_matches from anon, authenticated;
grant select on public.pvp_weapon_definitions to service_role;
grant all on public.pvp_weapon_definitions, public.pvp_matches to service_role;

create index if not exists pvp_matches_players_idx
  on public.pvp_matches(challenger_id,opponent_id,status);

insert into public.pvp_weapon_definitions(
  name,description,rarity,base_damage,attacks,sort_order
)
values(
  'Starter Blade',
  'A balanced PvP weapon with three distinct attacks.',
  'Common',
  10,
  '[
    {"id":"slash","name":"Slash","damageMultiplier":1.0,"cooldown":0.5,"description":"Fast balanced strike."},
    {"id":"heavy","name":"Heavy Cleave","damageMultiplier":1.7,"cooldown":2.0,"description":"Slower, harder hit."},
    {"id":"lunge","name":"Lunge","damageMultiplier":1.25,"cooldown":1.2,"description":"A precise forward attack."}
  ]'::jsonb,
  10
)
on conflict(name) do nothing;

insert into public.game_section_settings(id,label,short_label,icon,description,enabled,sort_order)
values
 ('daily-spin','Daily Spin','Spin','◉','One free daily prize spin.',false,70),
 ('pvp','PvP','PvP','⚔','Player-versus-player combat.',false,80)
on conflict(id) do nothing;

-- Seed custom rarity tiers for the upcoming-feature builder.
create table if not exists public.gem_rarity_definitions (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  min_rarity numeric not null default 1,
  max_rarity numeric,
  color text not null default '#9aa4b2',
  icon text not null default '◆',
  sort_order integer not null default 0,
  enabled boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.gem_rarity_definitions enable row level security;
revoke all on public.gem_rarity_definitions from anon, authenticated;
grant select on public.gem_rarity_definitions to anon, authenticated;
grant all on public.gem_rarity_definitions to service_role;

insert into public.gem_rarity_definitions(name,min_rarity,max_rarity,color,icon,sort_order)
values
 ('Common',1,9,'#94a3b8','◆',10),
 ('Uncommon',10,99,'#22c55e','◇',20),
 ('Rare',100,999,'#38bdf8','✦',30),
 ('Epic',1000,9999,'#a855f7','✧',40),
 ('Legendary',10000,999999,'#f59e0b','★',50),
 ('Mythic',1000000,null,'#ef4444','✹',60)
on conflict(name) do nothing;

create index if not exists gem_rarity_definitions_sort_idx
  on public.gem_rarity_definitions(enabled,sort_order,min_rarity);

-- Workbench configuration can now carry its public symbol/name independently.
alter table public.forge_config
  add column if not exists display_name text not null default 'Workbench [BETA]',
  add column if not exists icon text not null default '⚒';

update public.forge_config
set display_name='Workbench [BETA]', icon='⚒'
where id=true and (display_name is null or display_name='The Forge [BETA]');

-- Give the old Forge section a default Workbench identity if it has not
-- already been customized.
update public.game_section_settings
set label=coalesce(nullif(label,'The Forge [BETA]'),'Workbench [BETA]'),
    short_label=coalesce(nullif(short_label,'The Forge [BETA]'),'Workbench'),
    icon=coalesce(nullif(icon,'◆'),'⚒')
where id='forge';
