-- Gem Museum v0.12.0 Beta
-- Server-authoritative exhibits, permanent registrations and prestige.

alter table public.inventory_gems
  add column if not exists museum_locked boolean not null default false;

create table if not exists public.museum_profiles (
  player_id uuid primary key references public.players(id) on delete cascade,
  museum_name text not null default 'My Gem Museum',
  capacity integer not null default 4 check (capacity between 4 and 10),
  prestige numeric not null default 0,
  tier integer not null default 1,
  collections_completed integer not null default 0,
  highest_exhibit_score numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.museum_exhibits (
  player_id uuid not null references public.players(id) on delete cascade,
  slot integer not null check (slot between 1 and 10),
  specimen_id bigint not null unique references public.inventory_gems(id) on delete restrict,
  prestige numeric not null default 0,
  snapshot jsonb not null default '{}'::jsonb,
  added_at timestamptz not null default now(),
  primary key (player_id, slot)
);

create table if not exists public.museum_registrations (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  original_specimen_id bigint not null,
  specimen_snapshot jsonb not null,
  registered_at timestamptz not null default now(),
  unique (player_id, original_specimen_id)
);

create table if not exists public.museum_collection_definitions (
  id text primary key,
  name text not null,
  description text not null,
  kind text not null check (kind in ('permanent', 'showcase')),
  prestige_reward integer not null check (prestige_reward >= 0),
  requirements jsonb not null,
  cosmetic_reward text,
  sort_order integer not null default 0,
  enabled boolean not null default true
);

create table if not exists public.museum_collection_completions (
  player_id uuid not null references public.players(id) on delete cascade,
  collection_id text not null references public.museum_collection_definitions(id) on delete cascade,
  completed_at timestamptz not null default now(),
  primary key (player_id, collection_id)
);

create table if not exists public.museum_purchases (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  purchase_kind text not null,
  money_removed numeric not null check (money_removed >= 0),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.museum_collection_definitions
  (id, name, description, kind, prestige_reward, requirements, cosmetic_reward, sort_order)
values
  ('first-exhibit', 'First Exhibit', 'Place any specimen in your museum.', 'showcase', 100, '{"type":"count","count":1}', 'Founding Curator plaque', 10),
  ('curator-selection', 'Curator Selection', 'Display four different base gems at once.', 'showcase', 300, '{"type":"unique_gems","count":4}', null, 20),
  ('mutation-symphony', 'Mutation Symphony', 'Display specimens containing four different mutation types.', 'showcase', 600, '{"type":"unique_mutations","count":4}', 'Mutation gallery trim', 30),
  ('million-to-one', 'Million-to-One Hall', 'Display four gems with base rarity of 1 in 1,000,000 or rarer.', 'showcase', 1000, '{"type":"min_rarity","count":4,"min":1000000}', null, 40),
  ('polished-foundations', 'Polished Foundations', 'Permanently register ten different base gems.', 'permanent', 250, '{"type":"unique_gems","count":10}', 'Stone curator title', 110),
  ('mutation-sampler', 'Mutation Sampler', 'Permanently register five different mutation types.', 'permanent', 500, '{"type":"unique_mutations","count":5}', null, 120),
  ('serial-archive', 'Serial Archive', 'Permanently register ten serialized specimens.', 'permanent', 500, '{"type":"serial_count","count":10}', 'Archive display case', 130),
  ('million-archive', 'Million-to-One Archive', 'Permanently register four gems with base rarity of 1 in 1,000,000 or rarer.', 'permanent', 1000, '{"type":"min_rarity","count":4,"min":1000000}', null, 140)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  kind = excluded.kind,
  prestige_reward = excluded.prestige_reward,
  requirements = excluded.requirements,
  cosmetic_reward = excluded.cosmetic_reward,
  sort_order = excluded.sort_order;

insert into public.game_section_settings (id, label, description, enabled, sort_order)
values
  ('museum', 'Gem Museum', 'Curate exhibits, register collections and earn Museum Prestige.', true, 120),
  ('museum_public_visits', 'Museum public visits', 'Allow players to visit other museums.', false, 121),
  ('museum_weeklies', 'Museum weekly commissions', 'Weekly museum objectives and rewards.', false, 122),
  ('museum_events', 'Museum events', 'Limited-time museum exhibitions.', false, 123)
on conflict (id) do update set label = excluded.label, description = excluded.description;

create or replace function public.museum_specimen_score(p_gem public.inventory_gems)
returns numeric
language sql
immutable
as $$
  select round((
    20 * log(10, greatest(1, coalesce(p_gem.rarity, 1))::numeric)
    + least(180::numeric, 15 * log(10, greatest(1, coalesce(p_gem.effective_rarity, p_gem.rarity, 1))::numeric))
    + least(75::numeric, 25 * (ln(greatest(1, coalesce(p_gem.final_weight, 1) / greatest(coalesce(p_gem.base_weight, 1), 0.000001))) / ln(2)))
    + case cardinality(coalesce(p_gem.mutation_ids, '{}'::text[])) when 0 then 0 when 1 then 15 when 2 then 35 when 3 then 60 else 90 end
    + case
        when p_gem.serial_number = 1 then 100
        when p_gem.serial_number between 2 and 10 then 60
        when p_gem.serial_number between 11 and 50 then 35
        when p_gem.serial_number between 51 and 100 then 20
        when p_gem.serial_number between 101 and 500 then 10
        else 0
      end
  )::numeric, 2)
$$;

create or replace function public.museum_tier_for(p_prestige numeric)
returns integer language sql immutable as $$
  select case
    when p_prestige >= 75000 then 10 when p_prestige >= 50000 then 9
    when p_prestige >= 32500 then 8 when p_prestige >= 20000 then 7
    when p_prestige >= 12000 then 6 when p_prestige >= 7000 then 5
    when p_prestige >= 3500 then 4 when p_prestige >= 1500 then 3
    when p_prestige >= 500 then 2 else 1 end
$$;

create or replace function public.museum_collection_matches(p_requirements jsonb, p_specimens jsonb)
returns boolean language plpgsql immutable as $$
declare
  v_type text := p_requirements->>'type';
  v_count integer := coalesce((p_requirements->>'count')::integer, 1);
  v_result integer := 0;
begin
  if v_type = 'count' then
    v_result := jsonb_array_length(coalesce(p_specimens, '[]'::jsonb));
  elsif v_type = 'unique_gems' then
    select count(distinct x->>'gem_name') into v_result from jsonb_array_elements(coalesce(p_specimens, '[]'::jsonb)) x;
  elsif v_type = 'unique_mutations' then
    select count(distinct m) into v_result
    from jsonb_array_elements(coalesce(p_specimens, '[]'::jsonb)) x,
         jsonb_array_elements_text(coalesce(x->'mutation_ids', '[]'::jsonb)) m;
  elsif v_type = 'serial_count' then
    select count(*) into v_result from jsonb_array_elements(coalesce(p_specimens, '[]'::jsonb)) x
    where nullif(x->>'serial_number', '') is not null;
  elsif v_type = 'min_rarity' then
    select count(*) into v_result from jsonb_array_elements(coalesce(p_specimens, '[]'::jsonb)) x
    where coalesce((x->>'rarity')::numeric, 0) >= coalesce((p_requirements->>'min')::numeric, 0);
  end if;
  return v_result >= v_count;
end $$;

create or replace function public.museum_recalculate(p_player_id uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_exhibits jsonb;
  v_registered jsonb;
  v_exhibit_score numeric := 0;
  v_collection_score numeric := 0;
  v_total numeric;
  v_completed integer;
begin
  select coalesce(jsonb_agg(e.snapshot || jsonb_build_object('prestige', e.prestige)), '[]'::jsonb)
    into v_exhibits from public.museum_exhibits e where e.player_id = p_player_id;
  select coalesce(jsonb_agg(r.specimen_snapshot), '[]'::jsonb)
    into v_registered from public.museum_registrations r where r.player_id = p_player_id;

  select coalesce(sum(score * case occurrence when 1 then 1 when 2 then .5 when 3 then .25 else .1 end), 0)
    into v_exhibit_score
  from (
    select e.prestige score, row_number() over (partition by e.snapshot->>'gem_name' order by e.prestige desc) occurrence
    from public.museum_exhibits e where e.player_id = p_player_id
  ) ranked;

  insert into public.museum_collection_completions(player_id, collection_id)
  select p_player_id, d.id from public.museum_collection_definitions d
  where d.enabled and d.kind = 'permanent' and public.museum_collection_matches(d.requirements, v_registered)
  on conflict do nothing;

  select coalesce(sum(d.prestige_reward), 0), count(*) filter (where d.kind = 'permanent')
    into v_collection_score, v_completed
  from public.museum_collection_definitions d
  where d.enabled and (
    (d.kind = 'permanent' and exists (select 1 from public.museum_collection_completions c where c.player_id=p_player_id and c.collection_id=d.id))
    or (d.kind = 'showcase' and public.museum_collection_matches(d.requirements, v_exhibits))
  );

  v_total := round(v_exhibit_score + v_collection_score, 2);
  insert into public.museum_profiles(player_id, prestige, tier, collections_completed, highest_exhibit_score, updated_at)
  values (p_player_id, v_total, public.museum_tier_for(v_total), v_completed, v_exhibit_score, now())
  on conflict (player_id) do update set prestige=excluded.prestige, tier=excluded.tier,
    collections_completed=excluded.collections_completed, highest_exhibit_score=excluded.highest_exhibit_score, updated_at=now();
  return jsonb_build_object('prestige', v_total, 'tier', public.museum_tier_for(v_total));
end $$;

create or replace function public.museum_place_exhibit(p_player_id uuid, p_specimen_id bigint, p_slot integer)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_gem public.inventory_gems; v_capacity integer;
begin
  insert into public.museum_profiles(player_id) values(p_player_id) on conflict do nothing;
  select capacity into v_capacity from public.museum_profiles where player_id=p_player_id for update;
  if p_slot < 1 or p_slot > v_capacity then raise exception 'invalid_museum_slot'; end if;
  select * into v_gem from public.inventory_gems where id=p_specimen_id and player_id=p_player_id for update;
  if not found then raise exception 'specimen_not_found'; end if;
  if v_gem.museum_locked then raise exception 'specimen_already_exhibited'; end if;
  if exists(select 1 from public.museum_exhibits where player_id=p_player_id and slot=p_slot) then raise exception 'museum_slot_occupied'; end if;
  update public.inventory_gems set locked=true, museum_locked=true where id=p_specimen_id;
  insert into public.museum_exhibits(player_id,slot,specimen_id,prestige,snapshot)
  values(p_player_id,p_slot,p_specimen_id,public.museum_specimen_score(v_gem),
    jsonb_build_object('id',v_gem.id,'gem_name',v_gem.gem_name,'rarity',v_gem.rarity,'effective_rarity',v_gem.effective_rarity,
      'base_weight',v_gem.base_weight,'final_weight',v_gem.final_weight,'mutation_ids',to_jsonb(coalesce(v_gem.mutation_ids,'{}'::text[])),
      'serial_number',v_gem.serial_number,'value',v_gem.value));
  return public.museum_recalculate(p_player_id);
end $$;

create or replace function public.museum_remove_exhibit(p_player_id uuid, p_slot integer)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_specimen bigint;
begin
  select specimen_id into v_specimen from public.museum_exhibits where player_id=p_player_id and slot=p_slot for update;
  if not found then raise exception 'museum_slot_empty'; end if;
  delete from public.museum_exhibits where player_id=p_player_id and slot=p_slot;
  update public.inventory_gems set museum_locked=false where id=v_specimen and player_id=p_player_id;
  return public.museum_recalculate(p_player_id);
end $$;

create or replace function public.museum_expand(p_player_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_capacity integer; v_cost numeric; v_money numeric;
begin
  insert into public.museum_profiles(player_id) values(p_player_id) on conflict do nothing;
  select capacity into v_capacity from public.museum_profiles where player_id=p_player_id for update;
  if v_capacity >= 10 then raise exception 'museum_capacity_maxed'; end if;
  v_cost := case v_capacity+1 when 5 then 2000000 when 6 then 5000000 when 7 then 10000000 when 8 then 20000000 when 9 then 40000000 else 75000000 end;
  select money into v_money from public.players where id=p_player_id for update;
  if coalesce(v_money,0) < v_cost then raise exception 'not_enough_money'; end if;
  update public.players set money=money-v_cost where id=p_player_id;
  update public.museum_profiles set capacity=capacity+1,updated_at=now() where player_id=p_player_id;
  insert into public.museum_purchases(player_id,purchase_kind,money_removed,details)
  values(p_player_id,'capacity',v_cost,jsonb_build_object('slot',v_capacity+1));
  return jsonb_build_object('capacity',v_capacity+1,'cost',v_cost);
end $$;

create or replace function public.museum_register_specimen(p_player_id uuid, p_specimen_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_gem public.inventory_gems; v_snapshot jsonb;
begin
  select * into v_gem from public.inventory_gems where id=p_specimen_id and player_id=p_player_id for update;
  if not found then raise exception 'specimen_not_found'; end if;
  if v_gem.museum_locked then raise exception 'specimen_is_exhibited'; end if;
  if v_gem.locked then raise exception 'gem_locked'; end if;
  v_snapshot := jsonb_build_object('id',v_gem.id,'gem_name',v_gem.gem_name,'rarity',v_gem.rarity,'effective_rarity',v_gem.effective_rarity,
    'base_weight',v_gem.base_weight,'final_weight',v_gem.final_weight,'mutation_ids',to_jsonb(coalesce(v_gem.mutation_ids,'{}'::text[])),
    'serial_number',v_gem.serial_number,'value',v_gem.value,'prestige',public.museum_specimen_score(v_gem));
  insert into public.museum_registrations(player_id,original_specimen_id,specimen_snapshot) values(p_player_id,p_specimen_id,v_snapshot);
  delete from public.inventory_gems where id=p_specimen_id and player_id=p_player_id;
  return public.museum_recalculate(p_player_id);
end $$;

create or replace function public.get_museum_prestige_leaderboard(p_limit integer default 100)
returns table(rank bigint, player_id uuid, username text, avatar_url text, prestige numeric, tier integer, collections_completed integer, highest_exhibit_score numeric)
language sql stable security definer set search_path=public as $$
  select row_number() over(order by m.prestige desc,p.total_rolls desc,p.username),p.id,p.username,p.avatar_url,
    m.prestige,m.tier,m.collections_completed,m.highest_exhibit_score
  from public.museum_profiles m join public.players p on p.id=m.player_id
  where m.prestige > 0 order by m.prestige desc,p.total_rolls desc,p.username limit greatest(1,least(coalesce(p_limit,100),100));
$$;

create or replace function public.prevent_museum_specimen_mutation()
returns trigger language plpgsql as $$
begin
  if old.museum_locked and coalesce(current_setting('request.jwt.claim.role',true),'') <> 'service_role' then
    raise exception 'museum_specimen_protected';
  end if;
  return case when tg_op='DELETE' then old else new end;
end $$;
drop trigger if exists inventory_gems_museum_guard on public.inventory_gems;
create trigger inventory_gems_museum_guard before update or delete on public.inventory_gems
for each row execute function public.prevent_museum_specimen_mutation();

alter table public.museum_profiles enable row level security;
alter table public.museum_exhibits enable row level security;
alter table public.museum_registrations enable row level security;
alter table public.museum_collection_definitions enable row level security;
alter table public.museum_collection_completions enable row level security;
alter table public.museum_purchases enable row level security;

revoke all on public.museum_profiles,public.museum_exhibits,public.museum_registrations,public.museum_collection_completions,public.museum_purchases from anon,authenticated;
grant select on public.museum_collection_definitions to anon,authenticated;
grant all on public.museum_profiles,public.museum_exhibits,public.museum_registrations,public.museum_collection_definitions,public.museum_collection_completions,public.museum_purchases to service_role;
grant usage, select on sequence public.museum_registrations_id_seq, public.museum_purchases_id_seq to service_role;
revoke execute on function public.museum_place_exhibit(uuid,bigint,integer),public.museum_remove_exhibit(uuid,integer),public.museum_expand(uuid),public.museum_register_specimen(uuid,bigint),public.museum_recalculate(uuid) from public,anon,authenticated;
grant execute on function public.museum_place_exhibit(uuid,bigint,integer),public.museum_remove_exhibit(uuid,integer),public.museum_expand(uuid),public.museum_register_specimen(uuid,bigint),public.museum_recalculate(uuid) to service_role;
grant execute on function public.get_museum_prestige_leaderboard(integer) to anon,authenticated,service_role;

create policy museum_definitions_read on public.museum_collection_definitions for select using (enabled);
