-- v0.13.0 Beta: claimable achievements and permanent Achievement Points.
alter table public.private_feature_progress add column if not exists achievement_points_awarded integer not null default 0;
create table if not exists public.player_achievement_profiles(player_id uuid primary key references public.players(id) on delete cascade,achievement_points integer not null default 0 check(achievement_points>=0),updated_at timestamptz not null default now());
create table if not exists public.player_achievement_milestones(player_id uuid not null references public.players(id) on delete cascade,ap integer not null,claimed_at timestamptz not null default now(),primary key(player_id,ap));
alter table public.player_achievement_profiles enable row level security;alter table public.player_achievement_milestones enable row level security;
revoke all on public.player_achievement_profiles,public.player_achievement_milestones from public,anon,authenticated;grant all on public.player_achievement_profiles,public.player_achievement_milestones to service_role;

create or replace function public.award_achievement_points_v013() returns trigger language plpgsql security definer set search_path='' as $$declare points integer;
begin if new.completed and not old.completed then points:=greatest(0,coalesce((select (metadata->>'ap')::integer from public.private_feature_definitions where id=new.feature_id),0));new.achievement_points_awarded:=points;insert into public.player_achievement_profiles(player_id,achievement_points)values(new.player_id,points)on conflict(player_id)do update set achievement_points=public.player_achievement_profiles.achievement_points+excluded.achievement_points,updated_at=now();end if;return new;end$$;
drop trigger if exists award_achievement_points_v013_trg on public.private_feature_progress;create trigger award_achievement_points_v013_trg before update of completed on public.private_feature_progress for each row execute function public.award_achievement_points_v013();

create or replace function public.achievement_milestones_v013() returns jsonb language sql immutable set search_path='' as $$select jsonb_agg(jsonb_build_object('ap',ap,'rewards',rewards)order by ap)from(values(100,'[{"type":"money","amount":100000}]'::jsonb),(250,'[{"type":"potion","consumableId":"fortune-potion-2","name":"Fortune Potion II","amount":2}]'),(500,'[{"type":"cosmetic","cosmeticType":"badge","id":"achievement-novice","name":"Achievement Novice"}]'),(1000,'[{"type":"potion","consumableId":"legendary-potion","name":"Legendary Potion","amount":2}]'),(2000,'[{"type":"cosmetic","cosmeticType":"border","id":"milestone-bronze","name":"Milestone Bronze"}]'),(3500,'[{"type":"potion","consumableId":"mythic-potion","name":"Mythic Potion","amount":1}]'),(5000,'[{"type":"cosmetic","cosmeticType":"title","id":"achievement-hunter","name":"Achievement Hunter"}]'),(7500,'[{"type":"cosmetic","cosmeticType":"border","id":"milestone-diamond","name":"Milestone Diamond"}]'),(10000,'[{"type":"cosmetic","cosmeticType":"badge","id":"master-gem-incremental","name":"Master of Gem Incremental"},{"type":"cosmetic","cosmeticType":"title","id":"master-gem-incremental","name":"Master of Gem Incremental"}]'))x(ap,rewards)$$;

create or replace function public.grant_achievement_rewards_v013(p_uid uuid,p_rewards jsonb)returns void language plpgsql security definer set search_path='' as $$declare r jsonb;q integer;begin for r in select value from jsonb_array_elements(coalesce(p_rewards,'[]'))loop q:=greatest(1,coalesce((r->>'amount')::integer,1));if r->>'type'='money'then update public.players set money=money+coalesce((r->>'amount')::numeric,0)where id=p_uid;elsif r->>'type'='potion'then perform public.expedition_grant_consumable(p_uid,r->>'consumableId',q);elsif r->>'type'='capacity'then update public.players set inventory_capacity=inventory_capacity+q where id=p_uid;elsif r->>'type'='cosmetic'then insert into public.player_season_cosmetics(player_id,cosmetic_id,cosmetic_type)values(p_uid,r->>'id',r->>'cosmeticType')on conflict do nothing;end if;end loop;end$$;

create or replace function public.claim_achievement_reward_v013(p_player_id uuid,p_feature_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare p public.private_feature_progress%rowtype;d public.private_feature_definitions%rowtype;begin if auth.uid()is distinct from p_player_id then raise exception 'forbidden';end if;select * into p from public.private_feature_progress where player_id=p_player_id and feature_id=p_feature_id for update;if not found or not p.completed then raise exception 'achievement_not_completed';end if;if p.reward_granted then raise exception 'achievement_already_claimed';end if;select * into d from public.private_feature_definitions where id=p_feature_id and feature_kind='achievement';perform public.grant_achievement_rewards_v013(p_player_id,d.rewards);update public.private_feature_progress set reward_granted=true,reward_granted_at=now(),updated_at=now()where id=p.id;return jsonb_build_object('ok',true,'message','Achievement reward claimed','rewards',d.rewards);end$$;

create or replace function public.claim_achievement_milestone_v013(p_player_id uuid,p_ap integer)returns jsonb language plpgsql security definer set search_path='' as $$declare total integer;reward jsonb;begin if auth.uid()is distinct from p_player_id then raise exception 'forbidden';end if;select achievement_points into total from public.player_achievement_profiles where player_id=p_player_id;if coalesce(total,0)<p_ap then raise exception 'milestone_locked';end if;select value->'rewards' into reward from jsonb_array_elements(public.achievement_milestones_v013())where(value->>'ap')::integer=p_ap;if reward is null then raise exception 'milestone_not_found';end if;insert into public.player_achievement_milestones(player_id,ap)values(p_player_id,p_ap);perform public.grant_achievement_rewards_v013(p_player_id,reward);return jsonb_build_object('ok',true,'message','AP milestone reward claimed','rewards',reward);exception when unique_violation then raise exception 'milestone_already_claimed';end$$;

create or replace function public.get_player_achievements_v013(p_player_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare defs jsonb;prog jsonb;points integer;visible_total integer;visible_done integer;unclaimed integer;ranking bigint;milestones jsonb;begin if auth.uid()is distinct from p_player_id then raise exception 'forbidden';end if;perform public.ensure_private_feature_progress(p_player_id);select coalesce(jsonb_agg(to_jsonb(d)order by d.sort_order),'[]')into defs from public.private_feature_definitions d where d.enabled and d.feature_kind='achievement';select coalesce(jsonb_agg(to_jsonb(p)),'[]')into prog from public.private_feature_progress p join public.private_feature_definitions d on d.id=p.feature_id where p.player_id=p_player_id and d.feature_kind='achievement';select coalesce(achievement_points,0)into points from public.player_achievement_profiles where player_id=p_player_id;select count(*)filter(where coalesce((metadata->>'hidden')::boolean,false)=false)into visible_total from public.private_feature_definitions where enabled and feature_kind='achievement';select count(*)filter(where p.completed and coalesce((d.metadata->>'hidden')::boolean,false)=false),count(*)filter(where p.completed and not p.reward_granted)into visible_done,unclaimed from public.private_feature_progress p join public.private_feature_definitions d on d.id=p.feature_id where p.player_id=p_player_id and d.feature_kind='achievement';select rank into ranking from(select player_id,dense_rank()over(order by achievement_points desc)rank from public.player_achievement_profiles)x where player_id=p_player_id;select jsonb_agg(m||jsonb_build_object('unlocked',points>=(m->>'ap')::integer,'claimed',c.ap is not null)order by(m->>'ap')::integer)into milestones from jsonb_array_elements(public.achievement_milestones_v013())m left join public.player_achievement_milestones c on c.player_id=p_player_id and c.ap=(m->>'ap')::integer;return jsonb_build_object('definitions',defs,'progress',prog,'summary',jsonb_build_object('ap',points,'visibleCompleted',coalesce(visible_done,0),'visibleTotal',visible_total,'completionPercent',case when visible_total=0 then 0 else round(100.0*visible_done/visible_total,1)end,'rank',ranking,'unclaimed',coalesce(unclaimed,0)),'milestones',coalesce(milestones,'[]'));end$$;

revoke all on function public.award_achievement_points_v013(),public.achievement_milestones_v013(),public.grant_achievement_rewards_v013(uuid,jsonb),public.claim_achievement_reward_v013(uuid,uuid),public.claim_achievement_milestone_v013(uuid,integer),public.get_player_achievements_v013(uuid)from public,anon,authenticated;
grant execute on function public.claim_achievement_reward_v013(uuid,uuid),public.claim_achievement_milestone_v013(uuid,integer),public.get_player_achievements_v013(uuid)to authenticated,service_role;grant execute on function public.award_achievement_points_v013(),public.achievement_milestones_v013(),public.grant_achievement_rewards_v013(uuid,jsonb)to service_role;
