-- Normal Crystal Caverns V1 extraction progress, intensity, and run telemetry.
alter table public.crystal_cavern_runs alter column progress type numeric using progress::numeric;
alter table public.crystal_cavern_runs alter column instability type numeric using instability::numeric;
alter table public.crystal_cavern_runs add column intensity text not null default 'careful'
  constraint crystal_intensity check(intensity in('careful','forceful','fracturing'));
alter table public.crystal_cavern_runs add column event_log jsonb not null default '[]'::jsonb;

create or replace function public.crystal_log(p_log jsonb,p_kind text,p_message text,p_details jsonb default '{}'::jsonb)
returns jsonb language sql volatile set search_path='' as $$
 select coalesce((select jsonb_agg(value order by n) from(select value,n from jsonb_array_elements(coalesce(p_log,'[]'::jsonb)||jsonb_build_array(jsonb_build_object('kind',p_kind,'message',p_message,'details',p_details,'at',now())))with ordinality x(value,n) order by n desc limit 30)y),'[]'::jsonb)
$$;

create or replace function public.crystal_add_opportunities(p_run public.crystal_cavern_runs,p_pool text,p_count integer,p_base numeric,p_quality boolean default false) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare out jsonb:=p_run.unsecured_artifacts;a jsonb;i integer;bonus numeric:=coalesce((public.crystal_player_effects(p_run.player_id)->>'artifactChanceMultiplier')::numeric,1);begin for i in 1..p_count loop if random()<least(1,public.crystal_artifact_chance(p_base,floor(p_run.instability)::integer)*bonus)then a:=public.crystal_roll_artifact(p_run,p_pool,p_quality);if a is not null then out:=out||jsonb_build_array(a);end if;end if;end loop;return out;end $$;

create or replace function public.set_crystal_intensity(p_run_id bigint,p_intensity text)returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.crystal_cavern_runs;begin
 if p_intensity not in('careful','forceful','fracturing')then raise exception'invalid_crystal_intensity';end if;
 update public.crystal_cavern_runs set intensity=p_intensity,updated_at=now() where id=p_run_id and player_id=auth.uid() and status='active' returning*into r;
 if not found then raise exception'crystal_intensity_unavailable';end if;return to_jsonb(r);
end $$;

create or replace function public.fund_crystal_depth(p_run_id bigint,p_depth integer) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.crystal_cavern_runs;c numeric;m numeric;begin select*into r from public.crystal_cavern_runs where id=p_run_id and player_id=auth.uid()for update;if not found or r.overdepth<>0 or r.status<>'awaiting_funding'or p_depth<>r.depth+1 then raise exception'crystal_depth_unavailable';end if;c:=public.crystal_funding(p_depth);update public.players p set money=p.money-c where id=r.player_id and p.money>=c returning p.money into m;if not found then raise exception'insufficient_funds';end if;update public.crystal_cavern_runs set depth=p_depth,progress=0,target=100+p_depth*50,danger=public.crystal_base_danger(p_depth),status='active',total_funding=total_funding+c,event_log=public.crystal_log(event_log,'depth','Funded and entered D'||p_depth,jsonb_build_object('cost',c,'danger',public.crystal_base_danger(p_depth))),updated_at=now()where id=r.id returning*into r;return jsonb_build_object('run',to_jsonb(r),'money',m,'cost',c);end $$;

create or replace function public.crystal_apply_incident(p_run public.crystal_cavern_runs)returns public.crystal_cavern_runs language plpgsql volatile security definer set search_path='' as $$
declare sev text;loss numeric;kept jsonb;begin if random()>=p_run.danger/100.0 then return p_run;end if;sev:=public.crystal_severity(floor(p_run.instability)::integer);loss:=case sev when'minor'then .05+random()*.05 when'major'then .15+random()*.10 else .30+random()*.15 end;select coalesce(jsonb_agg(jsonb_set(value,'{value}',to_jsonb(round(coalesce((value->>'value')::numeric,0)*(1-loss))))),'[]')into kept from jsonb_array_elements(p_run.unsecured_cargo)value;p_run.unsecured_cargo:=kept;p_run.incident_log:=p_run.incident_log||jsonb_build_array(jsonb_build_object('severity',sev,'lossFraction',loss,'instability',p_run.instability,'at',now()));p_run.event_log:=public.crystal_log(p_run.event_log,'incident',initcap(sev)||' incident',jsonb_build_object('severity',sev,'lossFraction',loss));if sev='major'then p_run.instability:=p_run.instability+3;p_run.event_log:=public.crystal_log(p_run.event_log,'instability','Incident added 3 Instability');elsif sev='critical'then p_run.status:='forced_extraction';p_run.extraction_reason:='critical_incident';p_run.unsecured_artifacts:='[]';end if;return p_run;end $$;

create or replace function public.record_crystal_cavern_roll(p_player_id uuid,p_payload jsonb)returns void language plpgsql security definer set search_path='' as $$
declare r public.crystal_cavern_runs;bonus numeric:=0;base_progress numeric;progress_gain numeric;instability_gain numeric;newp numeric;base numeric;auto_i integer;pending jsonb:=null;old_i integer;new_i integer;old_cargo integer;old_artifacts integer;begin
 select*into r from public.crystal_cavern_runs where player_id=p_player_id and status='active'for update;if not found or nullif(p_payload->>'gemName','')is null then return;end if;
 if coalesce((p_payload->>'rarity')::numeric,0)>=50 then bonus:=bonus+1;end if;
 if coalesce((p_payload->>'rarity')::numeric,0)>=1000 then bonus:=bonus+3;end if;
 if coalesce((p_payload->>'rarity')::numeric,0)>=10000 then bonus:=bonus+7;end if;
 if jsonb_array_length(coalesce(p_payload->'mutationIds','[]'))>0 then bonus:=bonus+3;end if;
 -- The roll service sends final displayed weight / base weight here, not the raw rolled multiplier.
 if coalesce((p_payload->>'weightMultiplier')::numeric,0)>=2 then bonus:=bonus+3;end if;
 base_progress:=1+bonus*coalesce((public.crystal_player_effects(p_player_id)->>'bonusProgressMultiplier')::numeric,1);
 progress_gain:=base_progress*case r.intensity when'forceful'then 1.25 when'fracturing'then 1.60 else 1 end;
 instability_gain:=base_progress*case r.intensity when'forceful'then 2 when'fracturing'then 5 else 0 end/50.0;
 old_i:=floor(r.instability);r.instability:=r.instability+instability_gain;new_i:=floor(r.instability);
 if new_i>old_i then r.event_log:=public.crystal_log(r.event_log,'instability','Instability rose to '||new_i,jsonb_build_object('from',old_i,'to',new_i,'intensity',r.intensity));end if;
 newp:=least(r.target,r.progress+progress_gain);
 if r.progress<r.target and newp>=r.target then
  old_cargo:=jsonb_array_length(r.unsecured_cargo);old_artifacts:=jsonb_array_length(r.unsecured_artifacts);r:=public.crystal_apply_incident(r);
  if r.status<>'forced_extraction'then r.unsecured_cargo:=r.unsecured_cargo||jsonb_build_array(public.crystal_cargo(r.depth,r.overdepth));r.event_log:=public.crystal_log(r.event_log,'treasure','Recovered Crystal cargo',jsonb_build_object('depth',r.depth,'overdepth',r.overdepth));if r.overdepth>0 then auto_i:=case when r.overdepth<=3 then 8 when r.overdepth<=6 then 10 else 12 end;r.instability:=r.instability+auto_i;r.event_log:=public.crystal_log(r.event_log,'instability','Overdepth disturbance added '||auto_i||' Instability');base:=least(.40,.20+(r.overdepth-1)*.03);r.unsecured_artifacts:=public.crystal_add_opportunities(r,'od',1,base,false);if random()<.35 then pending:=jsonb_build_object('type','od_formation');else r.status:='ready_to_extract';end if;else base:=case when r.depth<=3 then .15 when r.depth<=6 then .20 when r.depth<=9 then .25 else .40 end;r.unsecured_artifacts:=public.crystal_add_opportunities(r,'general',1,base,false);if r.depth=10 then if random()<public.crystal_artifact_chance(.20,floor(r.instability)::integer)then r.unsecured_artifacts:=r.unsecured_artifacts||jsonb_build_array(public.crystal_roll_artifact(r,'d10-sphere'));end if;if random()<public.crystal_artifact_chance(1.0/9,floor(r.instability)::integer)then r.unsecured_artifacts:=r.unsecured_artifacts||jsonb_build_array(public.crystal_roll_artifact(r,'d10-heart'));end if;pending:=jsonb_build_object('type','d10_choice');elsif r.depth in(4,7,9)then pending:=jsonb_build_object('type','formation','depth',r.depth);elsif r.depth in(3,6)then pending:=jsonb_build_object('type','outpost','depth',r.depth);elsif r.depth in(2,5,8)and random()<.5 then pending:=jsonb_build_object('type','minor_event','event',(array['pocket','resonance','deposit'])[1+floor(random()*3)::integer]);else r.status:='awaiting_funding';end if;end if;if jsonb_array_length(r.unsecured_artifacts)>old_artifacts then r.event_log:=public.crystal_log(r.event_log,'artifact','Artifact discovered — unsecured and at risk',jsonb_build_object('count',jsonb_array_length(r.unsecured_artifacts)-old_artifacts));end if;if pending is not null then r.status:='decision';r.pending:=pending;r.event_log:=public.crystal_log(r.event_log,'event','New cavern decision: '||replace(pending->>'type','_',' '));end if;end if;
 end if;update public.crystal_cavern_runs set progress=newp,status=r.status,instability=r.instability,unsecured_cargo=r.unsecured_cargo,unsecured_artifacts=r.unsecured_artifacts,pending=r.pending,incident_log=r.incident_log,event_log=r.event_log,extraction_reason=r.extraction_reason,updated_at=now()where id=r.id;
end $$;

create or replace function public.continue_crystal_overdepth(p_run_id bigint)returns jsonb language plpgsql security definer set search_path='' as $$declare r public.crystal_cavern_runs;n integer;c numeric;m numeric;begin select*into r from public.crystal_cavern_runs where id=p_run_id and player_id=auth.uid()for update;if not found or r.status<>'ready_to_extract'or r.depth<>10 or not(coalesce((r.pending->>'fractured')::boolean,false)or r.overdepth>0)then raise exception'crystal_overdepth_unavailable';end if;n:=r.overdepth+1;c:=public.crystal_funding(10,n);update public.players p set money=p.money-c where id=r.player_id and p.money>=c returning p.money into m;if not found then raise exception'insufficient_funds';end if;update public.crystal_cavern_runs set overdepth=n,progress=0,target=600+n*50,danger=public.crystal_base_danger(10,n),status='active',pending=null,total_funding=total_funding+c,event_log=public.crystal_log(event_log,'depth','Funded and entered OD'||n,jsonb_build_object('cost',c,'danger',public.crystal_base_danger(10,n))),updated_at=now()where id=r.id returning*into r;return jsonb_build_object('run',to_jsonb(r),'money',m,'cost',c);end $$;

-- Preserve all existing decision effects while recording decision, securing, and instability events.
create or replace function public.resolve_crystal_decision(p_run_id bigint,p_choice text)returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.crystal_cavern_runs;t text;e text;c numeric:=0;di integer:=0;count_ integer:=0;quality boolean:=false;pool text:='formation';m numeric:=null;nextp jsonb:=null;before_artifacts integer;begin select*into r from public.crystal_cavern_runs where id=p_run_id and player_id=auth.uid()for update;if not found or r.status<>'decision'then raise exception'crystal_decision_unavailable';end if;t:=r.pending->>'type';before_artifacts:=jsonb_array_length(r.unsecured_artifacts);
 if t='minor_event'then e:=r.pending->>'event';if p_choice='leave'then null;elsif e='pocket'and p_choice='excavate'then di:=5;count_:=1;pool:='general';elsif e='resonance'and p_choice='trigger'then di:=8;count_:=1;quality:=true;elsif e='deposit'and p_choice='break'then di:=3;r.unsecured_cargo:=r.unsecured_cargo||jsonb_build_array(public.crystal_cargo(r.depth,0));r.event_log:=public.crystal_log(r.event_log,'treasure','Treasure found in crystal deposit');else raise exception'invalid_crystal_choice';end if;r.status:='awaiting_funding';
 elsif t in('formation','od_formation')then if p_choice='leave'then null;elsif t='od_formation'and p_choice='careful'then c:=public.crystal_funding(10,r.overdepth)*.20;di:=8;count_:=2;quality:=true;pool:='od';elsif t='od_formation'and p_choice='shatter'then di:=25;count_:=4;pool:='od';elsif t='formation'and p_choice='careful'then c:=case r.depth when 4 then 750000 when 7 then 2000000 else 4500000 end;di:=case r.depth when 4 then 4 when 7 then 6 else 8 end;count_:=case when r.depth=9 then 2 else 1 end;quality:=true;elsif t='formation'and p_choice='shatter'then di:=case r.depth when 4 then 12 when 7 then 18 else 25 end;count_:=case r.depth when 4 then 2 when 7 then 3 else 4 end;else raise exception'invalid_crystal_choice';end if;if t='od_formation'then r.status:='ready_to_extract';elsif r.depth=9 then nextp:=jsonb_build_object('type','outpost','depth',9);r.status:='decision';else r.status:='awaiting_funding';end if;
 elsif t='outpost'then if p_choice not in('secure','reinforce')then raise exception'invalid_crystal_choice';end if;c:=case r.depth when 3 then case p_choice when'secure'then 250000 else 500000 end when 6 then case p_choice when'secure'then 1000000 else 1750000 end else case p_choice when'secure'then 3500000 else 5500000 end end;if p_choice='reinforce'then r.danger:=greatest(0,r.danger-15);end if;r.secured_cargo:=r.secured_cargo||r.unsecured_cargo;r.unsecured_cargo:='[]';r.secured_artifacts:=r.secured_artifacts||r.unsecured_artifacts;r.unsecured_artifacts:='[]';r.status:='awaiting_funding';r.event_log:=public.crystal_log(r.event_log,'secured','Outpost secured all cargo and artifacts',jsonb_build_object('service',p_choice,'cost',c,'danger',r.danger));
 elsif t='d10_choice'then if p_choice='extract'then r.status:='ready_to_extract';elsif p_choice='fracture'then r.instability:=r.instability+30;r.event_log:=public.crystal_log(r.event_log,'instability','Fracturing the Heart added 30 Instability');r.status:='ready_to_extract';nextp:=jsonb_build_object('fractured',true);else raise exception'invalid_crystal_choice';end if;else raise exception'invalid_crystal_choice';end if;
 if c>0 then update public.players p set money=p.money-c where id=r.player_id and p.money>=c returning p.money into m;if not found then raise exception'insufficient_funds';end if;r.total_funding:=r.total_funding+c;end if;r.instability:=r.instability+di;if di>0 then r.event_log:=public.crystal_log(r.event_log,'instability','Cavern choice added '||di||' Instability');end if;if count_>0 then r.unsecured_artifacts:=public.crystal_add_opportunities(r,pool,count_,case when r.overdepth>0 then least(.40,.20+(r.overdepth-1)*.03)else case when r.depth<=6 then .20 else .25 end end,quality);end if;if jsonb_array_length(r.unsecured_artifacts)>before_artifacts then r.event_log:=public.crystal_log(r.event_log,'artifact','Artifact discovered — unsecured and at risk');end if;r.event_log:=public.crystal_log(r.event_log,'event','Resolved '||replace(t,'_',' ')||': '||p_choice);r.pending:=nextp;update public.crystal_cavern_runs set(status,instability,danger,secured_cargo,unsecured_cargo,secured_artifacts,unsecured_artifacts,pending,total_funding,event_log,updated_at)=(r.status,r.instability,r.danger,r.secured_cargo,r.unsecured_cargo,r.secured_artifacts,r.unsecured_artifacts,r.pending,r.total_funding,r.event_log,now())where id=r.id returning*into r;return jsonb_build_object('run',to_jsonb(r),'money',m,'cost',c);end $$;

create or replace function public.extract_crystal_caverns(p_run_id bigint)returns jsonb language plpgsql security definer set search_path='' as $$declare r public.crystal_cavern_runs;begin select*into r from public.crystal_cavern_runs where id=p_run_id and player_id=auth.uid()for update;if not found or r.status not in('ready_to_extract','forced_extraction')then raise exception'crystal_extraction_unavailable';end if;r.secured_cargo:=r.secured_cargo||r.unsecured_cargo;if r.status='forced_extraction'then r.unsecured_artifacts:='[]';else r.secured_artifacts:=r.secured_artifacts||r.unsecured_artifacts;end if;r.event_log:=public.crystal_log(r.event_log,'secured',case when r.status='forced_extraction'then'Emergency recovery secured surviving cargo'else'Extraction secured all cargo and artifacts'end);update public.crystal_cavern_runs set status='extracted',secured_cargo=r.secured_cargo,unsecured_cargo='[]',secured_artifacts=r.secured_artifacts,unsecured_artifacts='[]',event_log=r.event_log,extraction_reason=coalesce(extraction_reason,case when r.status='forced_extraction'then'critical_incident'else'voluntary'end),updated_at=now()where id=r.id returning*into r;return to_jsonb(r);end $$;

create or replace function public.get_crystal_caverns_dashboard()returns jsonb language plpgsql security definer set search_path='' as $$declare r public.crystal_cavern_runs;rj jsonb;a jsonb;m numeric;next_od numeric;next_danger integer;formation_cost numeric;begin if auth.uid()is null then raise exception'not_authenticated';end if;select*into r from public.crystal_cavern_runs x where player_id=auth.uid()and status<>'settled'order by id desc limit 1;rj:=case when r.id is null then null else to_jsonb(r)end;select p.money into m from public.players p where id=auth.uid();select coalesce(jsonb_agg(to_jsonb(x)order by x.sort_order),'[]')into a from(select c.*,exists(select 1 from public.museum_artifact_registrations z where z.player_id=auth.uid()and z.artifact_key=c.key)registered from public.crystal_cavern_artifacts c)x;if r.id is not null and r.depth=10 then next_od:=public.crystal_funding(10,r.overdepth+1);next_danger:=public.crystal_base_danger(10,r.overdepth+1);if r.overdepth>0 then formation_cost:=public.crystal_funding(10,r.overdepth)*.20;end if;end if;return jsonb_build_object('destination',jsonb_build_object('id','crystal-caverns','name','Crystal Caverns','identity','How much will you disturb?'),'run',rj,'money',m,'artifacts',a,'funding',to_jsonb(array[200000,300000,450000,650000,900000,1300000,2000000,3000000,4500000,7000000]),'danger',to_jsonb(array[0,3,7,12,18,26,35,45,57,70]),'nextOverdepthCost',next_od,'nextOverdepthDanger',next_danger,'overdepthFormationCost',formation_cost);end $$;

revoke all on function public.set_crystal_intensity(bigint,text)from public,anon;
grant execute on function public.set_crystal_intensity(bigint,text)to authenticated;
