-- Admin-authored update logs rendered on /updates.

create table if not exists public.update_logs (
  id bigint generated by default as identity primary key,
  version text not null check (char_length(version) between 1 and 40),
  title text not null check (char_length(title) between 1 and 120),
  published_on date not null,
  sections jsonb not null default '[]'::jsonb
    check (jsonb_typeof(sections) = 'array'),
  published boolean not null default false,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create index if not exists update_logs_public_order_idx
  on public.update_logs (published_on desc, published_at desc, id desc)
  where published = true;

alter table public.update_logs enable row level security;

revoke all on table public.update_logs from anon, authenticated;
grant select on table public.update_logs to anon, authenticated;
grant all on table public.update_logs to service_role;
grant usage, select on sequence public.update_logs_id_seq to service_role;

drop policy if exists "Published update logs are public" on public.update_logs;
create policy "Published update logs are public"
  on public.update_logs
  for select
  to anon, authenticated
  using (published = true);
