-- v0.9.0 Beta: server-authoritative Daily and Weekly Expeditions.
create table if not exists public.player_expeditions (
  id bigint generated by default as identity primary key,
  player_id uuid not null,
  cadence text not null check (cadence in ('daily','weekly')),
  difficulty text not null check (difficulty in ('standard','deep','void')),
  period_start timestamptz not null,
  period_end timestamptz not null,
  status text not null default 'active' check (status in ('active','completed','abandoned','expired')),
  entry_fee numeric not null,
  rerolls_used integer not null default 0,
  rerolls_max integer not null,
  reward jsonb,
  entered_at timestamptz not null default now(),
  completed_at timestamptz,
  ended_at timestamptz
);
create unique index if not exists player_expeditions_one_active
  on public.player_expeditions(player_id,cadence) where status='active';
create index if not exists player_expeditions_period on public.player_expeditions(player_id,cadence,period_start);

create table if not exists public.player_expedition_quests (
  id bigint generated by default as identity primary key,
  expedition_id bigint not null references public.player_expeditions(id) on delete cascade,
  position integer not null,
  category text not null,
  template text not null,
  title text not null,
  description text not null,
  target jsonb not null,
  progress jsonb not null default '{}',
  completed_at timestamptz,
  unique(expedition_id,position)
);

alter table public.player_expeditions enable row level security;
alter table public.player_expedition_quests enable row level security;

create or replace function public.expedition_period(p_cadence text, p_now timestamptz default now())
returns table(period_start timestamptz,period_end timestamptz)
language sql stable set search_path='' as $$
  select case when p_cadence='daily' then date_trunc('day',p_now at time zone 'UTC') at time zone 'UTC'
              else date_trunc('week',p_now at time zone 'UTC') at time zone 'UTC' end,
         case when p_cadence='daily' then (date_trunc('day',p_now at time zone 'UTC')+interval '1 day') at time zone 'UTC'
              else (date_trunc('week',p_now at time zone 'UTC')+interval '1 week') at time zone 'UTC' end;
$$;

create or replace function public.expedition_random_int(p_min integer,p_max integer)
returns integer language sql volatile set search_path='' as $$
  select p_min+floor(random()*(p_max-p_min+1))::integer;
$$;

create or replace function public.expedition_spec(p_category text,p_cadence text,p_difficulty text,p_allow_breakthrough boolean default true)
returns jsonb language plpgsql volatile set search_path='' as $$
declare v_roll numeric:=random(); v_template text; v_target jsonb; v_title text; v_description text;
begin
  if p_category='rolling' then
    if p_cadence='weekly' and v_roll<0.25 then
      v_template:='sustained_operation';
      v_target:=case p_difficulty when 'standard' then '{"daily":200,"days":2}' when 'deep' then '{"daily":500,"days":3}' else '{"daily":1000,"days":4}' end::jsonb;
      v_title:='Sustained Operation'; v_description:='Meet the roll quota across distinct UTC days.';
    elsif p_difficulty<>'standard' and v_roll>=0.95 then
      v_template:='rapid_extraction';
      v_target:=case when p_cadence='daily' and p_difficulty='deep' then '{"count":150,"seconds":1800}' when p_cadence='daily' then '{"count":350,"seconds":2700}' when p_difficulty='deep' then '{"count":500,"seconds":5400}' else '{"count":1000,"seconds":10800}' end::jsonb;
      v_title:='Rapid Extraction'; v_description:='Complete the quota within the window. Failed attempts reset.';
    else
      v_template:='excavation_quota';
      v_target:=jsonb_build_object('count',case when p_cadence='daily' and p_difficulty='standard' then public.expedition_random_int(100,150) when p_cadence='daily' and p_difficulty='deep' then public.expedition_random_int(300,450) when p_cadence='daily' then public.expedition_random_int(750,1000) when p_difficulty='standard' then public.expedition_random_int(1000,1500) when p_difficulty='deep' then public.expedition_random_int(3000,4500) else public.expedition_random_int(7000,10000) end);
      v_title:='Excavation Quota'; v_description:='Complete genuine rolls.';
    end if;
  elsif p_category='rarity' then
    if p_cadence='weekly' and p_allow_breakthrough and v_roll<0.10 then
      v_template:='rarity_breakthrough';
      v_target:=case p_difficulty when 'standard' then '{"rarity":22000,"fallback":75}' when 'deep' then '{"rarity":70000,"fallback":180}' else '{"rarity":190000,"fallback":400}' end::jsonb;
      v_title:='Rare Breakthrough'; v_description:='Find a gem beyond the threshold or fill the Rarity Score fallback.';
    elsif v_roll<0.45 then
      v_template:='rarity_score';
      v_target:=jsonb_build_object('score',case when p_cadence='daily' and p_difficulty='standard' then public.expedition_random_int(10,15) when p_cadence='daily' and p_difficulty='deep' then public.expedition_random_int(20,30) when p_cadence='daily' then public.expedition_random_int(40,60) when p_difficulty='standard' then public.expedition_random_int(75,100) when p_difficulty='deep' then public.expedition_random_int(150,220) else public.expedition_random_int(325,475) end);
      v_title:='Rarity Score'; v_description:='Earn score from Legendary and rarer genuine finds.';
    else
      v_template:='rarity_quota';
      v_target:=jsonb_build_object('rarity',case when p_difficulty='standard' then 1000 else 10000 end,'count',case when p_cadence='daily' and p_difficulty='standard' then public.expedition_random_int(5,8) when p_cadence='daily' and p_difficulty='deep' then public.expedition_random_int(2,4) when p_cadence='daily' then public.expedition_random_int(6,9) when p_difficulty='standard' then public.expedition_random_int(25,35) when p_difficulty='deep' then public.expedition_random_int(15,20) else public.expedition_random_int(30,40) end);
      v_title:='Rarity Quota'; v_description:='Find enough gems at or above the base-rarity threshold.';
    end if;
  elsif p_category='weight' then
    if p_cadence='weekly' and p_allow_breakthrough and v_roll<0.10 then
      v_template:='exceptional_specimen'; v_target:=case p_difficulty when 'standard' then '{"multiplier":3,"fallback":70}' when 'deep' then '{"multiplier":4,"fallback":150}' else '{"multiplier":5,"fallback":300}' end::jsonb;
      v_title:='Exceptional Specimen'; v_description:='Roll an exceptional weight multiplier or fill the Weight Score fallback.';
    elsif v_roll<0.45 then
      v_template:='weight_score';
      v_target:=jsonb_build_object('score',case when p_cadence='daily' and p_difficulty='standard' then public.expedition_random_int(15,20) when p_cadence='daily' and p_difficulty='deep' then public.expedition_random_int(30,40) when p_cadence='daily' then public.expedition_random_int(60,80) when p_difficulty='standard' then public.expedition_random_int(90,120) when p_difficulty='deep' then public.expedition_random_int(180,240) else public.expedition_random_int(350,450) end);
      v_title:='Weight Score'; v_description:='Earn score from heavy rolled multipliers.';
    else
      v_template:='heavy_haul';
      v_target:=jsonb_build_object('multiplier',case when p_difficulty='standard' then 1.5 when p_difficulty='deep' then 2 else 2.5 end,'count',case when p_cadence='daily' and p_difficulty='standard' then public.expedition_random_int(4,6) when p_cadence='daily' and p_difficulty='deep' then public.expedition_random_int(4,6) when p_cadence='daily' then public.expedition_random_int(5,7) when p_difficulty='standard' then public.expedition_random_int(20,30) when p_difficulty='deep' then public.expedition_random_int(20,30) else public.expedition_random_int(25,35) end);
      v_title:='Heavy Haul'; v_description:='Find specimens meeting the rolled weight multiplier.';
    end if;
  elsif p_category='mutation' then
    if p_cadence='weekly' and p_allow_breakthrough and v_roll<0.10 then
      v_template:='mutation_breakthrough'; v_target:=case p_difficulty when 'standard' then '{"rank":2,"fallback":12}' when 'deep' then '{"rank":3,"fallback":35}' else '{"rank":4,"fallback":90}' end::jsonb;
      v_title:='Mutation Breakthrough'; v_description:='Find the requested mutation tier or fill the Mutation Score fallback.';
    elsif v_roll<0.40 then
      v_template:='mutation_score'; v_target:=jsonb_build_object('score',case when p_cadence='daily' and p_difficulty='standard' then public.expedition_random_int(2,3) when p_cadence='daily' and p_difficulty='deep' then public.expedition_random_int(5,8) when p_cadence='daily' then public.expedition_random_int(12,18) when p_difficulty='standard' then public.expedition_random_int(18,25) when p_difficulty='deep' then public.expedition_random_int(45,65) else public.expedition_random_int(100,150) end);
      v_title:='Mutation Score'; v_description:='Earn score from genuinely rolled mutations.';
    else
      v_template:='mutation_quota'; v_target:=jsonb_build_object('count',case when p_cadence='daily' and p_difficulty='standard' then 1 when p_cadence='daily' and p_difficulty='deep' then public.expedition_random_int(2,3) when p_cadence='daily' then public.expedition_random_int(5,7) when p_difficulty='standard' then public.expedition_random_int(8,12) when p_difficulty='deep' then public.expedition_random_int(20,30) else public.expedition_random_int(40,55) end);
      v_title:='Mutation Quota'; v_description:='Find specimens with at least one mutation.';
    end if;
  elsif p_category='collection' then
    if v_roll<0.20 then
      v_template:='tier_survey'; v_target:=jsonb_build_object('tiers',case when p_cadence='daily' and p_difficulty='standard' then 3 when p_cadence='daily' and p_difficulty='deep' then 4 when p_cadence='daily' then 5 when p_difficulty='standard' then 4 when p_difficulty='deep' then 5 else 6 end);
      v_title:='Tier Survey'; v_description:='Find gems from different base-rarity tiers.';
    elsif v_roll<0.50 then
      v_template:='sample_collection'; v_target:=jsonb_build_object('copies',case when p_cadence='daily' and p_difficulty='standard' then 2 when p_cadence='daily' and p_difficulty='deep' then 3 when p_cadence='daily' then 4 when p_difficulty='standard' then 5 when p_difficulty='deep' then 7 else 10 end,'names',case when p_cadence='daily' and p_difficulty='standard' then 3 when p_cadence='daily' and p_difficulty='deep' then 4 when p_cadence='daily' then 5 when p_difficulty='standard' then 6 when p_difficulty='deep' then 8 else 10 end);
      v_title:='Sample Collection'; v_description:='Collect several copies of multiple gem types.';
    else
      v_template:='mineral_diversity'; v_target:=jsonb_build_object('names',case when p_cadence='daily' and p_difficulty='standard' then public.expedition_random_int(5,7) when p_cadence='daily' and p_difficulty='deep' then public.expedition_random_int(8,10) when p_cadence='daily' then public.expedition_random_int(11,14) when p_difficulty='standard' then public.expedition_random_int(15,18) when p_difficulty='deep' then public.expedition_random_int(20,25) else public.expedition_random_int(28,34) end);
      v_title:='Mineral Diversity'; v_description:='Find different gem names during this expedition.';
    end if;
  elsif p_category='potion' then
    if (p_cadence='weekly' or p_difficulty<>'standard') and v_roll<0.15 then
      v_template:='high_grade_mining'; v_target:=jsonb_build_object('tier',case when p_difficulty='void' then 3 else 2 end,'count',case when p_cadence='daily' and p_difficulty='deep' then public.expedition_random_int(40,60) when p_cadence='daily' then public.expedition_random_int(100,140) when p_difficulty='standard' then public.expedition_random_int(80,120) when p_difficulty='deep' then public.expedition_random_int(200,300) else public.expedition_random_int(350,500) end);
      v_title:='High-Grade Mining'; v_description:='Complete rolls while a high-tier timed potion is active.';
    elsif v_roll<0.45 then
      v_template:='alchemical_variety'; v_target:=jsonb_build_object('families',case when p_cadence='daily' and p_difficulty='standard' then 2 when p_cadence='daily' and p_difficulty='deep' then 3 when p_cadence='weekly' and p_difficulty='standard' then 3 else 4 end,'per_family',case when p_cadence='daily' and p_difficulty='standard' then 15 when p_cadence='daily' and p_difficulty='deep' then 25 when p_cadence='daily' then 40 when p_difficulty='standard' then 60 when p_difficulty='deep' then 120 else 250 end);
      v_title:='Alchemical Variety'; v_description:='Complete rolls under several different potion families.';
    else
      v_template:='potion_assisted'; v_target:=jsonb_build_object('count',case when p_cadence='daily' and p_difficulty='standard' then public.expedition_random_int(40,60) when p_cadence='daily' and p_difficulty='deep' then public.expedition_random_int(120,180) when p_cadence='daily' then public.expedition_random_int(250,350) when p_difficulty='standard' then public.expedition_random_int(250,400) when p_difficulty='deep' then public.expedition_random_int(700,1000) else public.expedition_random_int(1500,2200) end);
      v_title:='Potion-Assisted Mining'; v_description:='Complete genuine rolls while timed potions are active.';
    end if;
  else
    if p_cadence='weekly' and p_difficulty<>'standard' and p_allow_breakthrough and v_roll<0.15 then
      v_template:='ancient_breakthrough'; v_target:=case p_difficulty when 'deep' then '{"ancient":1,"points":8,"rolls":8000}' else '{"ancient":2,"points":20,"rolls":18000}' end::jsonb;
      v_title:='Ancient Breakthrough'; v_description:='Find Ancient Relics, earn Discovery Points, or reach the bad-luck ceiling.';
    elsif v_roll<0.45 then
      v_template:='relic_offering'; v_target:=jsonb_build_object('points',case when p_cadence='daily' and p_difficulty='deep' then 1 when p_cadence='daily' then 3 when p_difficulty='standard' then 3 when p_difficulty='deep' then 8 else 18 end);
      v_title:='Relic Offering'; v_description:='Consume relics through enchanting or the Masterwork Forge.';
    else
      v_template:='relic_discovery'; v_target:=jsonb_build_object('points',case when p_cadence='daily' and p_difficulty='deep' then 1 when p_cadence='daily' then 3 when p_difficulty='standard' then 5 when p_difficulty='deep' then 12 else 25 end,'rolls',case when p_cadence='daily' and p_difficulty='deep' then 600 when p_cadence='daily' then 1600 when p_difficulty='standard' then 3000 when p_difficulty='deep' then 8000 else 18000 end);
      v_title:='Relic Discovery'; v_description:='Find genuine relics or reach the bad-luck roll ceiling.';
    end if;
  end if;
  return jsonb_build_object('template',v_template,'title',v_title,'description',v_description,'target',v_target);
end; $$;

create or replace function public.expedition_fee(p_cadence text,p_difficulty text)
returns numeric language sql immutable set search_path='' as $$
 select case when p_cadence='daily' and p_difficulty='standard' then 200000 when p_cadence='daily' and p_difficulty='deep' then 1000000 when p_cadence='daily' then 3500000 when p_difficulty='standard' then 2000000 when p_difficulty='deep' then 8000000 else 25000000 end;
$$;

create or replace function public.enter_expedition(p_cadence text,p_difficulty text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_uid uuid:=auth.uid(); v_start timestamptz; v_end timestamptz; v_fee numeric; v_money double precision; v_id bigint; v_count integer; v_optional integer; v_pos integer:=1; v_cat text; v_spec jsonb; v_breakthrough boolean:=false;
begin
 if v_uid is null then raise exception 'not_authenticated'; end if;
 if p_cadence not in ('daily','weekly') or p_difficulty not in ('standard','deep','void') then raise exception 'invalid_expedition'; end if;
 select period_start,period_end into v_start,v_end from public.expedition_period(p_cadence);
 if (p_cadence='daily' and v_end-now()<interval '30 minutes') or (p_cadence='weekly' and v_end-now()<interval '6 hours') then raise exception 'expedition_entry_closed'; end if;
 perform pg_advisory_xact_lock(hashtext('expedition-'||v_uid::text||p_cadence));
 update public.player_expeditions set status='expired',ended_at=now() where player_id=v_uid and cadence=p_cadence and status='active' and period_end<=now();
 if exists(select 1 from public.player_expeditions where player_id=v_uid and cadence=p_cadence and status='active') then raise exception 'expedition_already_active'; end if;
 select count(*) into v_count from public.player_expeditions where player_id=v_uid and cadence=p_cadence and period_start=v_start;
 if (p_cadence='daily' and v_count>=2) or (p_cadence='weekly' and v_count>=1) then raise exception 'expedition_limit_reached'; end if;
 if p_cadence='daily' and p_difficulty='void' and exists(select 1 from public.player_expeditions where player_id=v_uid and cadence='daily' and difficulty='void' and period_start=v_start) then raise exception 'daily_void_used'; end if;
 v_fee:=public.expedition_fee(p_cadence,p_difficulty);
 update public.players set money=money-v_fee where id=v_uid and money>=v_fee returning money into v_money;
 if not found then raise exception 'insufficient_funds'; end if;
 insert into public.player_expeditions(player_id,cadence,difficulty,period_start,period_end,entry_fee,rerolls_max) values(v_uid,p_cadence,p_difficulty,v_start,v_end,v_fee,case when p_cadence='daily' then 1 else 2 end) returning id into v_id;
 v_spec:=public.expedition_spec('rolling',p_cadence,p_difficulty,true);
 insert into public.player_expedition_quests(expedition_id,position,category,template,title,description,target) values(v_id,v_pos,'rolling',v_spec->>'template',v_spec->>'title',v_spec->>'description',v_spec->'target');
 v_optional:=case when p_cadence='daily' and p_difficulty='standard' then 1 when p_cadence='daily' and p_difficulty='deep' then 2 when p_cadence='daily' then 3 when p_difficulty='standard' then 3 when p_difficulty='deep' then 4 else 5 end;
 for v_cat in select category from (values('rarity',20),('collection',20),('weight',18),('potion',16),('mutation',14),('relic',12)) x(category,weight) where not(p_cadence='daily' and p_difficulty='standard' and category='relic') order by -ln(greatest(random(),0.000001))/weight limit v_optional loop
   v_pos:=v_pos+1; v_spec:=public.expedition_spec(v_cat,p_cadence,p_difficulty,not v_breakthrough);
   if v_spec->>'template' in ('rarity_breakthrough','exceptional_specimen','mutation_breakthrough','ancient_breakthrough') then v_breakthrough:=true; end if;
   insert into public.player_expedition_quests(expedition_id,position,category,template,title,description,target) values(v_id,v_pos,v_cat,v_spec->>'template',v_spec->>'title',v_spec->>'description',v_spec->'target');
 end loop;
 return jsonb_build_object('id',v_id,'money',v_money);
end; $$;

create or replace function public.abandon_expedition(p_expedition_id bigint)
returns void language plpgsql security definer set search_path='' as $$
begin
 update public.player_expeditions set status='abandoned',ended_at=now() where id=p_expedition_id and player_id=auth.uid() and status='active';
 if not found then raise exception 'expedition_not_active'; end if;
end; $$;

create or replace function public.reroll_expedition_quest(p_quest_id bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_uid uuid:=auth.uid(); v_e public.player_expeditions%rowtype; v_q public.player_expedition_quests%rowtype; v_spec jsonb; v_cost numeric; v_money double precision; v_allow_breakthrough boolean; i integer;
begin
 select q.* into v_q from public.player_expedition_quests q join public.player_expeditions e on e.id=q.expedition_id where q.id=p_quest_id and e.player_id=v_uid and e.status='active' for update of q;
 if not found or v_q.completed_at is not null then raise exception 'quest_not_rerollable'; end if;
 select * into v_e from public.player_expeditions where id=v_q.expedition_id for update;
 if v_e.rerolls_used>=v_e.rerolls_max then raise exception 'reroll_limit_reached'; end if;
 v_allow_breakthrough:=not exists(select 1 from public.player_expedition_quests where expedition_id=v_e.id and id<>v_q.id and template in ('rarity_breakthrough','exceptional_specimen','mutation_breakthrough','ancient_breakthrough'));
 v_spec:=public.expedition_spec(v_q.category,v_e.cadence,v_e.difficulty,v_allow_breakthrough);
 for i in 1..5 loop exit when v_spec->>'template'<>v_q.template; v_spec:=public.expedition_spec(v_q.category,v_e.cadence,v_e.difficulty,v_allow_breakthrough); end loop;
 if v_spec->>'template'=v_q.template then raise exception 'no_alternative_quest'; end if;
 v_cost:=v_e.entry_fee*case when v_e.cadence='daily' then 0.20 else 0.15 end;
 update public.players set money=money-v_cost where id=v_uid and money>=v_cost returning money into v_money;
 if not found then raise exception 'insufficient_funds'; end if;
 update public.player_expeditions set rerolls_used=rerolls_used+1 where id=v_e.id;
 update public.player_expedition_quests set template=v_spec->>'template',title=v_spec->>'title',description=v_spec->>'description',target=v_spec->'target',progress='{}',completed_at=null where id=v_q.id;
 return jsonb_build_object('money',v_money,'cost',v_cost);
end; $$;

revoke all on function public.expedition_period(text,timestamptz),public.expedition_random_int(integer,integer),public.expedition_spec(text,text,text,boolean),public.expedition_fee(text,text) from public;
revoke all on function public.enter_expedition(text,text),public.abandon_expedition(bigint),public.reroll_expedition_quest(bigint) from public;
grant execute on function public.enter_expedition(text,text),public.abandon_expedition(bigint),public.reroll_expedition_quest(bigint) to authenticated;

create or replace function public.expedition_rarity_rank(p_rarity numeric)
returns integer language sql immutable set search_path='' as $$
 select case when p_rarity<10 then 0 when p_rarity<50 then 1 when p_rarity<100 then 2 when p_rarity<1000 then 3 when p_rarity<10000 then 4 when p_rarity<100000 then 5 when p_rarity<1000000 then 6 when p_rarity<10000000 then 7 else 8 end;
$$;
create or replace function public.expedition_rarity_score(p_rarity numeric)
returns integer language sql immutable set search_path='' as $$
 select case when p_rarity>=10000000 then 200 when p_rarity>=1000000 then 50 when p_rarity>=100000 then 15 when p_rarity>=10000 then 4 when p_rarity>=1000 then 1 else 0 end;
$$;
create or replace function public.expedition_weight_score(p_multiplier numeric)
returns integer language sql immutable set search_path='' as $$
 select case when p_multiplier>=4 then 20 when p_multiplier>=3 then 10 when p_multiplier>=2 then 5 when p_multiplier>=1.5 then 2 when p_multiplier>=1.25 then 1 else 0 end;
$$;
create or replace function public.expedition_mutation_score(p_ids jsonb)
returns integer language sql immutable set search_path='' as $$
 select coalesce(sum(case value#>>'{}' when 'polished' then 1 when 'gilded' then 4 when 'prismatic' then 15 when 'celestial' then 50 when 'corrupted' then 200 else 0 end),0)::integer from jsonb_array_elements(coalesce(p_ids,'[]'));
$$;
create or replace function public.expedition_mutation_rank(p_ids jsonb)
returns integer language sql immutable set search_path='' as $$
 select coalesce(max(case value#>>'{}' when 'polished' then 1 when 'gilded' then 2 when 'prismatic' then 3 when 'celestial' then 4 when 'corrupted' then 5 else 0 end),0)::integer from jsonb_array_elements(coalesce(p_ids,'[]'));
$$;

create or replace function public.expedition_grant_consumable(p_uid uuid,p_id text,p_qty integer)
returns void language sql security definer set search_path='' as $$
 insert into public.player_consumables(player_id,consumable_id,quantity,updated_at) values(p_uid,p_id,p_qty,now())
 on conflict(player_id,consumable_id) do update set quantity=public.player_consumables.quantity+excluded.quantity,updated_at=now();
$$;
create or replace function public.expedition_grant_relic(p_uid uuid,p_name text,p_qty integer)
returns void language sql security definer set search_path='' as $$
 insert into public.inventory_gems(player_id,gem_name,rarity,base_weight,value_per_gram,rolled_weight_multiplier,rolled_weight,final_weight,value,locked)
 select p_uid,p_name,case when p_name='Ancient Relic' then 1500 else 250 end,0,0,1,0,0,0,false from generate_series(1,p_qty);
$$;

create or replace function public.expedition_finish_if_ready(p_expedition_id bigint)
returns void language plpgsql security definer set search_path='' as $$
declare v_e public.player_expeditions%rowtype; v_roll numeric; v_rewards jsonb:='[]'; v_id text; v_bonus text;
begin
 if exists(select 1 from public.player_expedition_quests where expedition_id=p_expedition_id and completed_at is null) then return; end if;
 update public.player_expeditions set status='completed',completed_at=now(),ended_at=now() where id=p_expedition_id and status='active' returning * into v_e;
 if not found then return; end if;
 if v_e.cadence='daily' and v_e.difficulty='standard' then
   for v_id in select x from unnest(array['lucky-potion-2','speed-potion-2','fortune-potion-2','mass-potion-2']) x order by random() limit 2 loop perform public.expedition_grant_consumable(v_e.player_id,v_id,1); v_rewards:=v_rewards||jsonb_build_array(jsonb_build_object('type','consumable','id',v_id,'quantity',1,'guaranteed',true)); end loop;
 elsif v_e.cadence='daily' and v_e.difficulty='deep' then
   for v_id in select x from unnest(array['lucky-potion-3','speed-potion-3','fortune-potion-3','mass-potion-3']) x order by random() limit 2 loop perform public.expedition_grant_consumable(v_e.player_id,v_id,1); v_rewards:=v_rewards||jsonb_build_array(jsonb_build_object('type','consumable','id',v_id,'quantity',1,'guaranteed',true)); end loop;
 elsif v_e.cadence='daily' then
   perform public.expedition_grant_consumable(v_e.player_id,'legendary-potion',1); v_rewards:=v_rewards||jsonb_build_array('{"type":"consumable","id":"legendary-potion","quantity":1,"guaranteed":true}'::jsonb);
 elsif v_e.difficulty='standard' then
   for v_id in select x from unnest(array['lucky-potion-3','speed-potion-3','fortune-potion-3','mass-potion-3']) x order by random() limit 3 loop perform public.expedition_grant_consumable(v_e.player_id,v_id,1); v_rewards:=v_rewards||jsonb_build_array(jsonb_build_object('type','consumable','id',v_id,'quantity',1,'guaranteed',true)); end loop;
 elsif v_e.difficulty='deep' then
   perform public.expedition_grant_consumable(v_e.player_id,'legendary-potion',1); perform public.expedition_grant_relic(v_e.player_id,'Enchant Relic',1);
   v_rewards:=v_rewards||'[{"type":"consumable","id":"legendary-potion","quantity":1,"guaranteed":true},{"type":"relic","id":"Enchant Relic","quantity":1,"guaranteed":true}]'::jsonb;
 else
   perform public.expedition_grant_consumable(v_e.player_id,'legendary-potion',2); perform public.expedition_grant_relic(v_e.player_id,'Enchant Relic',2);
   v_rewards:=v_rewards||'[{"type":"consumable","id":"legendary-potion","quantity":2,"guaranteed":true},{"type":"relic","id":"Enchant Relic","quantity":2,"guaranteed":true}]'::jsonb;
 end if;
 v_roll:=random();
 if v_e.cadence='daily' and v_e.difficulty='standard' then
   if v_roll<0.65 then v_bonus:='tier2x2'; elsif v_roll<0.90 then v_bonus:='tier3'; elsif v_roll<0.98 then v_bonus:='enchant1'; else v_bonus:='legendary'; end if;
 elsif v_e.cadence='daily' and v_e.difficulty='deep' then
   if v_roll<0.45 then v_bonus:='tier3x2'; elsif v_roll<0.70 then v_bonus:='legendary'; elsif v_roll<0.90 then v_bonus:='enchant1'; elsif v_roll<0.98 then v_bonus:='enchant2'; else v_bonus:='ancient1'; end if;
 elsif v_e.cadence='daily' then
   if v_roll<0.35 then v_bonus:='legendary'; elsif v_roll<0.60 then v_bonus:='enchant2'; elsif v_roll<0.80 then v_bonus:='tier3x3distinct'; elsif v_roll<0.95 then v_bonus:='ancient1'; else v_bonus:='mythic'; end if;
 elsif v_e.difficulty='standard' then
   if v_roll<0.60 then v_bonus:='enchant1'; elsif v_roll<0.90 then v_bonus:='legendary'; else v_bonus:='ancient1'; end if;
 elsif v_e.difficulty='deep' then
   if v_roll<0.45 then v_bonus:='enchant2'; elsif v_roll<0.75 then v_bonus:='legendary'; elsif v_roll<0.95 then v_bonus:='ancient1'; else v_bonus:='mythic'; end if;
 else
   if v_roll<0.35 then v_bonus:='enchant3'; elsif v_roll<0.65 then v_bonus:='ancient1'; elsif v_roll<0.85 then v_bonus:='ancient2'; elsif v_roll<0.95 then v_bonus:='mythic'; else v_bonus:='mythic_ancient'; end if;
 end if;
 if v_bonus like 'tier2%' then
   for v_id in select x from unnest(array['lucky-potion-2','speed-potion-2','fortune-potion-2','mass-potion-2']) x order by random() limit 2 loop perform public.expedition_grant_consumable(v_e.player_id,v_id,1); v_rewards:=v_rewards||jsonb_build_array(jsonb_build_object('type','consumable','id',v_id,'quantity',1)); end loop;
 elsif v_bonus like 'tier3%' then
   for v_id in select x from unnest(array['lucky-potion-3','speed-potion-3','fortune-potion-3','mass-potion-3']) x order by random() limit case when v_bonus='tier3' then 1 when v_bonus='tier3x2' then 2 else 3 end loop perform public.expedition_grant_consumable(v_e.player_id,v_id,1); v_rewards:=v_rewards||jsonb_build_array(jsonb_build_object('type','consumable','id',v_id,'quantity',1)); end loop;
 elsif v_bonus='legendary' then perform public.expedition_grant_consumable(v_e.player_id,'legendary-potion',1); v_rewards:=v_rewards||'[{"type":"consumable","id":"legendary-potion","quantity":1}]'::jsonb;
 elsif v_bonus='mythic' then perform public.expedition_grant_consumable(v_e.player_id,'mythic-potion',1); v_rewards:=v_rewards||'[{"type":"consumable","id":"mythic-potion","quantity":1}]'::jsonb;
 elsif v_bonus='enchant1' then perform public.expedition_grant_relic(v_e.player_id,'Enchant Relic',1); v_rewards:=v_rewards||'[{"type":"relic","id":"Enchant Relic","quantity":1}]'::jsonb;
 elsif v_bonus='enchant2' then perform public.expedition_grant_relic(v_e.player_id,'Enchant Relic',2); v_rewards:=v_rewards||'[{"type":"relic","id":"Enchant Relic","quantity":2}]'::jsonb;
 elsif v_bonus='enchant3' then perform public.expedition_grant_relic(v_e.player_id,'Enchant Relic',3); v_rewards:=v_rewards||'[{"type":"relic","id":"Enchant Relic","quantity":3}]'::jsonb;
 elsif v_bonus='ancient1' then perform public.expedition_grant_relic(v_e.player_id,'Ancient Relic',1); v_rewards:=v_rewards||'[{"type":"relic","id":"Ancient Relic","quantity":1}]'::jsonb;
 elsif v_bonus='ancient2' then perform public.expedition_grant_relic(v_e.player_id,'Ancient Relic',2); v_rewards:=v_rewards||'[{"type":"relic","id":"Ancient Relic","quantity":2}]'::jsonb;
 else perform public.expedition_grant_consumable(v_e.player_id,'mythic-potion',1); perform public.expedition_grant_relic(v_e.player_id,'Ancient Relic',1); v_rewards:=v_rewards||'[{"type":"consumable","id":"mythic-potion","quantity":1},{"type":"relic","id":"Ancient Relic","quantity":1}]'::jsonb;
 end if;
 update public.player_expeditions set reward=jsonb_build_object('bonus',v_bonus,'items',v_rewards) where id=v_e.id;
end; $$;

create or replace function public.record_expedition_roll(p_player_id uuid,p_payload jsonb)
returns void language plpgsql security definer set search_path='' as $$
declare v_e record; v_q record; p jsonb; t jsonb; done boolean; n integer; score integer; rank integer; gem text:=p_payload->>'gemName'; rarity numeric:=coalesce((p_payload->>'rarity')::numeric,0); wm numeric:=coalesce((p_payload->>'weightMultiplier')::numeric,0); mids jsonb:=coalesce(p_payload->'mutationIds','[]'); families jsonb:=coalesce(p_payload->'boostFamilies','[]'); tiers jsonb:=coalesce(p_payload->'boostTiers','{}'); relic text:=p_payload->>'relicName'; today text:=to_char(now() at time zone 'UTC','YYYY-MM-DD');
begin
 for v_e in select * from public.player_expeditions where player_id=p_player_id and status='active' and period_end>now() for update loop
  for v_q in select * from public.player_expedition_quests where expedition_id=v_e.id and completed_at is null order by position for update loop
   p:=coalesce(v_q.progress,'{}'); t:=v_q.target; done:=false;
   if v_q.template='excavation_quota' then n:=coalesce((p->>'count')::int,0)+1; p:=jsonb_build_object('count',n); done:=n>=(t->>'count')::int;
   elsif v_q.template='sustained_operation' then n:=coalesce((p#>>array['days',today])::int,0)+1; p:=jsonb_set(p,'{days}',coalesce(p->'days','{}'),true); p:=jsonb_set(p,array['days',today],to_jsonb(n),true); select count(*) into score from jsonb_each_text(coalesce(p->'days','{}')) where value::int>=(t->>'daily')::int; done:=score>=(t->>'days')::int;
   elsif v_q.template='rapid_extraction' then
    if p->>'startedAt' is null or (p->>'startedAt')::timestamptz+make_interval(secs=>(t->>'seconds')::int)<now() then p:=jsonb_build_object('count',1,'startedAt',now()); n:=1; else n:=coalesce((p->>'count')::int,0)+1; p:=jsonb_set(p,'{count}',to_jsonb(n)); end if; done:=n>=(t->>'count')::int;
   elsif relic is null and v_q.template='rarity_quota' then n:=coalesce((p->>'count')::int,0)+case when rarity>=(t->>'rarity')::numeric then 1 else 0 end; p:=jsonb_build_object('count',n); done:=n>=(t->>'count')::int;
   elsif relic is null and v_q.template in ('rarity_score','rarity_breakthrough') then score:=coalesce((p->>'score')::int,0)+public.expedition_rarity_score(rarity); p:=jsonb_build_object('score',score,'best',greatest(coalesce((p->>'best')::numeric,0),rarity)); done:=case when v_q.template='rarity_score' then score>=(t->>'score')::int else rarity>=(t->>'rarity')::numeric or score>=(t->>'fallback')::int end;
   elsif relic is null and v_q.template='heavy_haul' then n:=coalesce((p->>'count')::int,0)+case when wm>=(t->>'multiplier')::numeric then 1 else 0 end; p:=jsonb_build_object('count',n); done:=n>=(t->>'count')::int;
   elsif relic is null and v_q.template in ('weight_score','exceptional_specimen') then score:=coalesce((p->>'score')::int,0)+public.expedition_weight_score(wm); p:=jsonb_build_object('score',score,'best',greatest(coalesce((p->>'best')::numeric,0),wm)); done:=case when v_q.template='weight_score' then score>=(t->>'score')::int else wm>=(t->>'multiplier')::numeric or score>=(t->>'fallback')::int end;
   elsif relic is null and v_q.template='mutation_quota' then n:=coalesce((p->>'count')::int,0)+case when jsonb_array_length(mids)>0 then 1 else 0 end; p:=jsonb_build_object('count',n); done:=n>=(t->>'count')::int;
   elsif relic is null and v_q.template in ('mutation_score','mutation_breakthrough') then score:=coalesce((p->>'score')::int,0)+public.expedition_mutation_score(mids); rank:=greatest(coalesce((p->>'bestRank')::int,0),public.expedition_mutation_rank(mids)); p:=jsonb_build_object('score',score,'bestRank',rank); done:=case when v_q.template='mutation_score' then score>=(t->>'score')::int else rank>=(t->>'rank')::int or score>=(t->>'fallback')::int end;
   elsif relic is null and v_q.template='mineral_diversity' then p:=jsonb_set(p,'{names}',coalesce(p->'names','[]')||to_jsonb(gem),true); p:=jsonb_set(p,'{names}',(select jsonb_agg(x) from (select distinct value x from jsonb_array_elements_text(p->'names')) s),true); done:=jsonb_array_length(p->'names')>=(t->>'names')::int;
   elsif relic is null and v_q.template='tier_survey' then rank:=public.expedition_rarity_rank(rarity); p:=jsonb_set(p,'{tiers}',coalesce(p->'tiers','[]')||to_jsonb(rank),true); p:=jsonb_set(p,'{tiers}',(select jsonb_agg(x) from (select distinct value x from jsonb_array_elements(p->'tiers')) s),true); done:=jsonb_array_length(p->'tiers')>=(t->>'tiers')::int;
   elsif relic is null and v_q.template='sample_collection' then n:=coalesce((p#>>array['counts',gem])::int,0)+1; p:=jsonb_set(p,'{counts}',coalesce(p->'counts','{}'),true); p:=jsonb_set(p,array['counts',gem],to_jsonb(n),true); select count(*) into score from jsonb_each_text(coalesce(p->'counts','{}')) where value::int>=(t->>'copies')::int; done:=score>=(t->>'names')::int;
   elsif v_q.template='potion_assisted' then n:=coalesce((p->>'count')::int,0)+case when jsonb_array_length(families)>0 then 1 else 0 end; p:=jsonb_build_object('count',n); done:=n>=(t->>'count')::int;
   elsif v_q.template='alchemical_variety' then p:=jsonb_set(p,'{families}',coalesce(p->'families','{}'),true); for gem in select value#>>'{}' from jsonb_array_elements(families) loop n:=coalesce((p#>>array['families',gem])::int,0)+1; p:=jsonb_set(p,array['families',gem],to_jsonb(n),true); end loop; select count(*) into score from jsonb_each_text(coalesce(p->'families','{}')) where value::int>=(t->>'per_family')::int; done:=score>=(t->>'families')::int;
   elsif v_q.template='high_grade_mining' then n:=coalesce((p->>'count')::int,0)+case when exists(select 1 from jsonb_each_text(tiers) where value::int>=(t->>'tier')::int) then 1 else 0 end; p:=jsonb_build_object('count',n); done:=n>=(t->>'count')::int;
   elsif v_q.template in ('relic_discovery','ancient_breakthrough') then score:=coalesce((p->>'points')::int,0)+case relic when 'Ancient Relic' then 6 when 'Enchant Relic' then 1 else 0 end; n:=coalesce((p->>'rolls')::int,0)+1; rank:=coalesce((p->>'ancient')::int,0)+case when relic='Ancient Relic' then 1 else 0 end; p:=jsonb_build_object('points',score,'rolls',n,'ancient',rank); done:=case when v_q.template='relic_discovery' then score>=(t->>'points')::int or n>=(t->>'rolls')::int else rank>=(t->>'ancient')::int or score>=(t->>'points')::int or n>=(t->>'rolls')::int end;
   end if;
   update public.player_expedition_quests set progress=p,completed_at=case when done then now() else null end where id=v_q.id;
  end loop;
  perform public.expedition_finish_if_ready(v_e.id);
 end loop;
end; $$;

create or replace function public.record_expedition_relic_spend(p_player_id uuid,p_enchant integer,p_ancient integer)
returns void language plpgsql security definer set search_path='' as $$
declare v_e record; v_q record; points integer:=greatest(0,p_enchant)+greatest(0,p_ancient)*6; n integer;
begin
 if points=0 then return; end if;
 for v_e in select * from public.player_expeditions where player_id=p_player_id and status='active' and period_end>now() for update loop
  for v_q in select * from public.player_expedition_quests where expedition_id=v_e.id and template='relic_offering' and completed_at is null for update loop
   n:=coalesce((v_q.progress->>'points')::int,0)+points;
   update public.player_expedition_quests set progress=jsonb_build_object('points',n),completed_at=case when n>=(v_q.target->>'points')::int then now() else null end where id=v_q.id;
  end loop;
  perform public.expedition_finish_if_ready(v_e.id);
 end loop;
end; $$;

create or replace function public.expedition_view_active(p_uid uuid,p_cadence text)
returns jsonb language sql security definer stable set search_path='' as $$
 select case when e.id is null then null else to_jsonb(e)||jsonb_build_object('quests',coalesce((select jsonb_agg(to_jsonb(q) order by q.position) from public.player_expedition_quests q where q.expedition_id=e.id),'[]'::jsonb)) end
 from (select * from public.player_expeditions where player_id=p_uid and cadence=p_cadence and status='active' limit 1)e;
$$;

create or replace function public.get_expedition_dashboard()
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_uid uuid:=auth.uid(); d_start timestamptz; d_end timestamptz; w_start timestamptz; w_end timestamptz; result jsonb;
begin
 if v_uid is null then raise exception 'not_authenticated'; end if;
 select period_start,period_end into d_start,d_end from public.expedition_period('daily'); select period_start,period_end into w_start,w_end from public.expedition_period('weekly');
 update public.player_expeditions set status='expired',ended_at=now() where player_id=v_uid and status='active' and period_end<=now();
 select jsonb_build_object(
  'daily',jsonb_build_object('periodStart',d_start,'periodEnd',d_end,'entriesUsed',(select count(*) from public.player_expeditions where player_id=v_uid and cadence='daily' and period_start=d_start),'voidUsed',exists(select 1 from public.player_expeditions where player_id=v_uid and cadence='daily' and difficulty='void' and period_start=d_start),'active',public.expedition_view_active(v_uid,'daily')),
  'weekly',jsonb_build_object('periodStart',w_start,'periodEnd',w_end,'entriesUsed',(select count(*) from public.player_expeditions where player_id=v_uid and cadence='weekly' and period_start=w_start),'active',public.expedition_view_active(v_uid,'weekly')),
  'fees',jsonb_build_object('daily',jsonb_build_object('standard',200000,'deep',1000000,'void',3500000),'weekly',jsonb_build_object('standard',2000000,'deep',8000000,'void',25000000)),
  'history',coalesce((select jsonb_agg(to_jsonb(e) order by e.entered_at desc) from (select id,cadence,difficulty,status,entry_fee,reward,entered_at,completed_at,ended_at from public.player_expeditions where player_id=v_uid order by entered_at desc limit 20)e),'[]'::jsonb)
 ) into result;
 return result;
end; $$;

revoke all on function public.expedition_rarity_rank(numeric),public.expedition_rarity_score(numeric),public.expedition_weight_score(numeric),public.expedition_mutation_score(jsonb),public.expedition_mutation_rank(jsonb) from public;
revoke all on function public.expedition_grant_consumable(uuid,text,integer),public.expedition_grant_relic(uuid,text,integer),public.expedition_finish_if_ready(bigint),public.record_expedition_roll(uuid,jsonb),public.record_expedition_relic_spend(uuid,integer,integer),public.expedition_view_active(uuid,text) from public;
grant execute on function public.record_expedition_roll(uuid,jsonb),public.record_expedition_relic_spend(uuid,integer,integer) to service_role;
revoke all on function public.get_expedition_dashboard() from public;
grant execute on function public.get_expedition_dashboard() to authenticated;
